### ISSUE TITLE
Credits should be added in read me!

### ISSUE THREAD

**Issue by ollo69** [Vaskivskyi/ha-asusrouter#10]
Hey @Vaskivskyi ,

looks like this integration is fully based on my work in native HA integration and above all on my additional work implemented [here](https://github.com/ollo69/ha_asuswrt_custom).
Of course in open source word you are free to do whatever you want with public code, but is good practice at least mention the source from where your code come from.

Thanks 👍

**Comment by Vaskivskyi** [comment]
Hi @ollo69,

Please, check PR #12 if this is fine with you
