### ISSUE TITLE
[Device support] Netgear R7000

### ISSUE THREAD

**Issue by elRadix** [Vaskivskyi/ha-asusrouter#111]
### The problem

Everything is working great so far.
![SmartSelect_20220605-134411_Chrome](https://user-images.githubusercontent.com/6258894/172048887-22240cfa-8d08-407a-944b-381e1f3f36f2.jpg)

### Your device model

Netgear R7000 

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.2_4

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello, @elRadix,

Thanks for your feedback! 👍🏻 

I am glad, everything works for your device.

PR #112 will add it to the supported devices list (under Non-Asus devices) and will close this issue.

In case you will experience any problems or you would like to submit a feature request, please open a new [issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose)
