### ISSUE TITLE
[Device support] 

### ISSUE THREAD

**Issue by Davrebelo** [Vaskivskyi/ha-asusrouter#117]
### Your device model

ZenWiFi AX Mini (XD4)

### Firmware type

Stock

### Firmware version

3.0.0.4.386_48790

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hey, @Davrebelo,

Thank you for the feedback! 👍🏻 

PR #118 will add your device to the list of supported and will close this issue.

In case you will experience any problems with the integration, please open a new [issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose).

Have a nice day! 🙂
