### ISSUE TITLE
[Bug] Exception: invalid literal for int() with base 10: '<i>off</i>'`

### ISSUE THREAD

**Issue by sepodele** [Vaskivskyi/ha-asusrouter#121]
### The problem

I'm getting this error in HA but the integration seems to work:

`Logger: asusrouter.connection
Source: /usr/local/lib/python3.9/site-packages/asusrouter/connection.py:122
First occurred: 10. juni 2022, 10:02:30 (2770 occurrences)
Last logged: 09:07:13

Error sending a command to ajax_sysinfo.asp. Exception: invalid literal for int() with base 10: '<i>off</i>'`

### Your device model

RT-AC68U

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.5_2

### Integration version with the issue

0.4.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2022.6.4

**Comment by Vaskivskyi** [comment]
Hello, @sepodele,

Thank you for your feedback! 👍🏻 

Seems like your device is reporting values, which are not expected in the SysInfo. Or, to be more exact something is not an integer number, but `off`. We would need to find out, which value is giving the exception.

Could you please log in to the web panel of the device from a browser and then navigate to `https://router:port/ajax_sysinfo.asp` (this page can be only accessed directly, so just change whatever page address to the `ajax_sysinfo.asp`).

The page will have some info similar to this (probably not formatted):

```
etherstate = "[]";
rtkswitch = [];
hndswitch = { "portSpeed": { "WAN 0": "M", "LAN 1": "G", "LAN 2": "G", "LAN 3": "X", "LAN 4": "X", "LAN 5": "X", "LAN 6": "X", "LAN 7": "G", "LAN 8": "X" }, "portCount": { "wanCount": 1, "lanCount": 8 } };
wlc_24_arr = ["13", "13", "13"];
wlc_51_arr = ["4", "4", "4"];
wlc_52_arr = ["0", "0", "0"];
conn_stats_arr = ["566","55"];
mem_stats_arr = ["882.37", "538.87", "0.00", "22.24", "0.00", "0.00", "76858", "2.83 / 63.00 MB"];
cpu_stats_arr = ["3.82", "3.82", "3.82"];
```

Could you please share the content of this page? As you see, it should contain different status values of the device.

**Comment by sepodele** [comment]
`etherstate = "Switch: enabled >Port 0: 1000FD enabled stp: none vlan: 2 jumbo: off mac: 00:27:90:ff:44:29>Port 1: 100FD enabled stp: none vlan: 1 jumbo: off mac: 00:0c:39:95:ef:7b>Port 2: 1000FD enabled stp: none vlan: 1 jumbo: off mac: 00:11:42:cf:32:df>Port 3: 1000FD enabled stp: none vlan: 1 jumbo: off mac: 44:09:c8:76:84:83>Port 4: DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00>Port 5: 1000FD enabled stp: none vlan: 2 jumbo: off mac: 10:a4:be:de:de:47>Port 7: DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00>Port 8: DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00>"; rtkswitch = []; hndswitch = { "portSpeed": { "WAN 0": "G", "LAN 1": "M", "LAN 2": "G", "LAN 3": "G", "LAN 4": "X" }, "portCount": { "wanCount": 1, "lanCount": 4 } }; wlc_24_arr = ["23", "23", "23"]; wlc_51_arr = ["off", "off", "off"]; wlc_52_arr = ["0", "0", "0"]; conn_stats_arr = ["553","185"]; mem_stats_arr = ["249.72", "88.74", "3.65", "26.33", "0.00", "0.00", "62496", "7.41 / 62.75 MB"]; cpu_stats_arr = ["0.61", "0.31", "0.26"];`

I replaced the MAC addresses with bogus values.

**Comment by Vaskivskyi** [comment]
The problem was with the wlc_51_arr. I will prepare the fix. Will be released in the next version of the integration.

I will notify you when released

**Comment by Vaskivskyi** [comment]
Hey, @sepodele,

The latest version 0.5.0 should have fixed the issue. Can you check it and let me know?

**Comment by sepodele** [comment]
No errors in the log so far. Thanks a bunch.

**Comment by Vaskivskyi** [comment]
Great!

If you will experience any other problems with the integration, please, feel free to open a new issue.

Thanks for helping me make the integration better! 👍🏻
