### ISSUE TITLE
[Feature] List devices as attributes under connected devices sensor?

### ISSUE THREAD

**Issue by sepodele** [Vaskivskyi/ha-asusrouter#133]
### The problem

I often would like to know what devices are connected and it's tiresome to check the router ui. Can we have the names and IPs of the connected devices as attributes of the connected devices sensor?

**Comment by Vaskivskyi** [comment]
Hey,

PR #172 is adding a list of the devices (including MAC, IP and name) as a `devices` attribute for the `connected_devices` sensor.

This feature will be included in the next release. The readme will be updated with the info on the new attribute.
