### ISSUE TITLE
[Bug] Failed parsing value 'internetMode'.

### ISSUE THREAD

**Issue by RealGandy** [Vaskivskyi/ha-asusrouter#135]
### The problem

Following Error reported in logs:

2022-06-14 23:17:13 WARNING (MainThread) [asusrouter.util.parsers] Failed parsing value 'internetMode'. Please report this issue. Exception summary: ("Wrong value time of type <class 'str'>", None)

### Your device model

DSL-AC68U

### Firmware type

Merlin

### Firmware version

386.04-gnuton2

### Integration version with the issue

5.0.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Container.  Home Assistant Core 2022.6.3

**Comment by Vaskivskyi** [comment]
Hello, @RealGandy,

Thank you for your feedback! 👍🏻 

Seems like you are having an issue similar to #29.

Could you please run this python snippet from any environment with AsusRouter library installed? Or you can install the library via `pip3 install asusrouter` in any environment. Just put the code into some `script.py` and then run it with `python3 script.py`

Just put your router data at the end of the code, as stated.

```python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
import asyncio


async def gather_data(host, username, password, port, use_ssl, cert_check):
    """Method to gether all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, port = port, use_ssl = use_ssl, cert_check = cert_check)

    # Connect
    await router.connection.async_connect()

    # Get all the boolean data in raw
    data = await router.async_hook("get_clientlist()")
    for device in data["get_clientlist"]:
        try:
            info = data["get_clientlist"][device]
            print(f"internet_mode:{info['internetMode']}")
        except Exception as ex:
            print(f"Exception: {ex}")
            continue

    # Disconnect
    await router.connection.async_disconnect()


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_port = 0
_use_ssl = True
_cert_check = False

loop.run_until_complete(gather_data(_host, _username, _password, _port, _use_ssl, _cert_check))

loop.close()
```

Please, copy the output here. It will show either of:
- `internet_mode:block`
- `internet_mode:allow`
- some exception

I still don't know why would it report `time` there, but should finally find this out. Also would be nice to know, if this happens for lots of connected devices or only for some random one.

**Comment by Vaskivskyi** [comment]
Yes, probably this is the reason. I will check this with my device later today (I am not using parental control, so never tested its features). If so and the fix is simple, it would be available either today or tomorrow. If a bit more to change - during the weekend with the next version of the integration

I will let you know

**Comment by Vaskivskyi** [comment]
Hey,

With the new version [0.5.1](https://github.com/Vaskivskyi/ha-asusrouter/releases/tag/0.5.1) you should not get such warnings anymore

Please, check it out

**Comment by RealGandy** [comment]
Yes, all good now thanks.
