### ISSUE TITLE
[Feature] Change port forward settings

### ISSUE THREAD

**Issue by Tekno-man** [Vaskivskyi/ha-asusrouter#136]
### The problem

Hi, I just stumbled upon your integration and it looks great, so many more features than the standard HA asuswrt one. I'm not sure what the limitations are of the api you are using but wondered if it gave you access to different settings specifically the port forward settings? Ultimately wanting to change port forward settings through automations and update the source IPs through HA. I looked at IP tables but doesn't seem possible on standard firmware.

**Comment by Salvora** [comment]
I think it is possible to add an on/off switch but configuring the details might be a little too hard.
I use a custom script to turn on and off the port forwarding if I notice suspicious activity from the Home Assistant frontend.

**Comment by iMarkus** [comment]
Hi @Salvora,
would you mind posting your custom script to turn on / off port forwarding or a link to it?

**Comment by Vaskivskyi** [comment]
Hey, I am happy to announce, that the requested feature is already in the development/testing state. So it will definitely be implemented 📢

**Comment by Vaskivskyi** [comment]
Hey. The feature is already available in the new 0.19.0 version. Check it out

**Comment by iMarkus** [comment]
Hi,
I can confirm that on/off is working fine but the switch state itself is always "turned off".

**Comment by Vaskivskyi** [comment]
@iMarkus, hey. Can you please open a new issue with the steps on how to reproduce the problem and info about your device and HA log errors(if any)? Thanks!
