### ISSUE TITLE
[Feature] : Device blocking

### ISSUE THREAD

**Issue by NachoMas** [Vaskivskyi/ha-asusrouter#146]
### The problem

So far the device tracker only has a sensor that reports Internet:true or false. I would like to be able to block the device from HA as in the native Asus GUI

**Comment by Vaskivskyi** [comment]
Hello, @NachoMas,

Thanks for your feedback! 👍🏻 

This function is already planned for the integration

**Comment by NachoMas** [comment]
Excellent! And thanks so much for an great addon! I've been fiddling with ssh commands to try to implement some of the functionality the addon delivers and this is a very welcomed improvement!

**Comment by jacquesvzijp** [comment]
That would be a great feature, blocking (and unblocking of course), to make some smarter screentime for the kids playstation and so... Thanks for the great work!

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.12.0, which adds functionality to allow/block internet access for a single device. [More info here](https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/211?u=vaskivskyi)

**Comment by jacquesvzijp** [comment]
Hi
Thanks made a quick check for now, it seems to work so really happy, just to build some automations and UI. Great
Jacques

**Comment by Vaskivskyi** [comment]
Since the feature is already implemented in 0.12.0 and other users do not report any problems with it, I will close this issue.
