### ISSUE TITLE
RT-AX86S working

### ISSUE THREAD

**Issue by cjescudero** [Vaskivskyi/ha-asusrouter#148]
### Anything you want to mention?

I have tested ASUS Router integration on a Home Assistant (2022.6.7), with an Asus RT-AX86S Router, which is a simplified model of the RT-AX86U (half the memory and CPUs).

It works perfectly, except that the identified model is the RT-AX86U.
<img width="334" alt="Captura de Pantalla 2022-07-01 a las 10 26 31" src="https://user-images.githubusercontent.com/2061498/176856614-e27bd188-665d-4786-936f-b157a0e741cf.png">

### Your device model

RT-AX86S

### Firmware type

Stock

### Firmware version

3.0.0.4.386_49447

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello, @cjescudero,

Thanks for your feedback! 👍🏻 

PR #150 will add your device to the supported list with a remark about being reported as RT-AX86U and close this issue.

The model name is reported from the device NVRAM. There happen to be some problems with the 'similar models'. Apparently, this is the case.

I will in any case look into this, even though this is only a cosmetic issue, but cannot promise any timeframe for now.
