### ISSUE TITLE
 RT-AX86U

### ISSUE THREAD

**Issue by WalkeLee** [Vaskivskyi/ha-asusrouter#15]
Thank you very much for the program provided, but it didn't work on my RT-AX86U. Hope it fits in, and I'll try to help.
![image](https://user-images.githubusercontent.com/39288935/167259171-38a9c04e-d4cb-4fde-b7d3-42b42d5784ad.png)

**Comment by Vaskivskyi** [comment]
Hi @WalkeLee ,

First of all, thank you for your feedback! 👍🏻 

Could you please provide a bit more information, so I will be able to help you and implement fixes into the integration?

### At which step did something go wrong?

1. Did you install the integration from HACS or manually copied the repository to your Home Assistant folder?
2. Were you able to add your RT-AX86U to HA or did the installation step fail?
3. If the device was added, did it show any sensors (entities)? Did sensors show any values or were they `unavailable`?

### Check Home Assistant Log

Could you please check your HA log? Are there any errors or warnings from AsusRouter integration?

To open the log, please follow this link: [![Open your Home Assistant instance and show your Home Assistant logs.](https://my.home-assistant.io/badges/logs.svg)](https://my.home-assistant.io/redirect/logs/)

Or in your HA follow `Settings -> System -> Logs` (versions 2022.5.0+) or `Configuration -> Settings -> Logs` (versions up to 2022.4.7). You would need also to click `Load Full Logs`.

Messages from the integration would look like this:

`2022-05-07 01:23:45 ERROR (MainThread) [homeassistant.custom_components.asusrouter] Error message in here`

Errors or warnings in the log can appear either during HA start (if integration cannot start at all) or during the process of setting it up and connecting to you router.

Thanks in advance!

**Comment by WalkeLee** [comment]
1. I'm install the integration from HACS
2. I cant add my RT-AX86U to HA ，It looks like this
![image](https://user-images.githubusercontent.com/39288935/167280463-5b4b5eda-767d-4e47-8e3b-10fca087261d.png)
![image](https://user-images.githubusercontent.com/39288935/167280495-fad1dd54-cfe5-4a35-82ba-cf02efd248e6.png)


此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/asusrouter/bridge.py:201
Integration: ASUS Router (documentation, issues)
First occurred: 11:22:27 (1 occurrences)
Last logged: 11:22:27

Error setting up entry 192.168.50.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 17, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 264, in setup
    self._mac = await self._api.get_mac()
  File "/config/custom_components/asusrouter/bridge.py", line 234, in get_mac
    await self._async_get_device_info()
  File "/config/custom_components/asusrouter/bridge.py", line 201, in _async_get_device_info
    await self._api.async_initialize()
  File "/usr/local/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 599, in async_initialize
    await self.async_monitor_misc()
  File "/usr/local/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 384, in async_monitor_misc
    monitor_misc["PORTS"][type][number] = await helpers.async_transform_port_speed(data["portSpeed"][value])
  File "/usr/local/lib/python3.9/site-packages/asusrouter/helpers.py", line 112, in async_transform_port_speed
    raise NotImplementedError("Conversion for this value is not implemented")
NotImplementedError: Conversion for this value is not implemented

I'm sorry I'm not a developer.

**Comment by Vaskivskyi** [comment]
It's fine. We've already found the reason - your device has 2.5G WAN/LAN port, which was not yet supported.

Now we need to find out, what exactly value it sends and then I'll prepare a fix in the code.

Can you please log in to the web panel of your device? (like http://192.168.50.1/). After logging in, in the address bar of your browser change the address to http://192.168.50.1/ajax_ethernet_ports.asp (so just add `ajax_ethernet_ports.asp` at the end and press Enter to load this page.

This is the address from where information on the router ports is collected. It would look like this:

```
get_wan_lan_status = { "portSpeed": { "WAN 0": "M", "LAN 1": "G", "LAN 2": "G", "LAN 3": "X", "LAN 4": "X" }, "portCount": { "wanCount": 1, "lanCount": 4 } };
```

I would need to know what values your router provides.

**Comment by WalkeLee** [comment]
get_wan_lan_status = { "portSpeed": { "WAN 0": "G", "LAN 1": "X", "LAN 2": "X", "LAN 3": "G", "LAN 4": "G", "LAN 5": "Q" }, "portCount": { "wanCount": 1, "lanCount": 5 } };

**Comment by Vaskivskyi** [comment]
I've implemented the needed changes into the library behind this integration.

The problem will be solved with the next release of the integration. It could take a couple of days. I'll let you know

Thanks again for your help! 👍🏻

**Comment by Vaskivskyi** [comment]
@WalkeLee ,

Please, check if the new version 0.2.0 available now from HACS has solved this problem.

If you are experiencing any other problems, please open a new issue

**Comment by WalkeLee** [comment]
Problem solved, have a nice day
