### ISSUE TITLE
[Feature] Support for WOL?

### ISSUE THREAD

**Issue by c0j0s** [Vaskivskyi/ha-asusrouter#151]
### The problem

Hi, great work on the integration 👍. 
Currently I'm trying to implement a at-home automation in HA, I wanted the router to wake my WOL device when someone comes back home.

Asuswrt WebUI internally make a POST call with a ether-wake command payload to apply.cgi endpoint.

Here is the payload content.
```
current_page: Main_WOL_Content.asp  
next_page: Main_WOL_Content.asp  
group_id:   
modified: 0  
action_mode:  Refresh  
action_script:  
action_wait:  
first_time: 
preferred_lang: CN
SystemCmd: ether-wake -i br0 -b 00:00:00:00:00:00
firmver: 3.0.0.4
destIP: 00:00:00:00:00:00
wollist_macAddr: 
```

Would be useful for automation if It's possible, Thank you.

**Comment by sfortis** [comment]
Why bothering? It is build in into HA.

For example you can create a WOL / sleep switch ( in my case, im posting a MQTT message to PUSH2RUN for the sleep command)

switch:
   - platform: wake_on_lan
     name: "your switch name"
     mac: XX:XX:XX:XX:XX:XX
     host: 192.168.1.XX
     turn_off:
      service: mqtt.publish
      data:
        payload: sleep
        topic: push2run

**Comment by c0j0s** [comment]
> Why bothering? It is build in into HA.
> 
> For example you can create a WOL / sleep switch ( in my case, im posting a MQTT message to PUSH2RUN for the sleep command)
> 
> switch:
> 
> * platform: wake_on_lan
>   name: "your switch name"
>   mac: XX:XX:XX:XX:XX:XX
>   host: 192.168.1.XX
>   turn_off:
>   service: mqtt.publish
>   data:
>   payload: sleep
>   topic: push2run

My HA instance is on a different network, I've tried the buildin wol, doesn't seem to work, so I'm just exploring different options.

I'll try your approach too, thank you.

**Comment by Vaskivskyi** [comment]
Hi, @c0j0s,

As @sfortis has already mentioned, WOL is of course a part of HA already. But maybe it will come to AsusRouter as well. Unfortunately, I cannot guarantee any timeframe currently, but I will look into this idea.

P.S. If you are trying to send WOL between networks, you should make sure that the port for WOL is allowed to pass your router(s). I suppose, the default port is either 7 or 9, but you better check it.

**Comment by c0j0s** [comment]
Hi @Vaskivskyi,

Thank you for your suggestion, I've explored further and able to get the built-in HA WOL working.
I'm using openvpn to tunnel my HA instance back, seems like it needs a L2 bridge for the WOL package to work as it's a L2 protocol. Took some time to test the setup and resolve configuration issues to get it running. 
If AsusRouter allows for remote wol service then it would much simpler to setup, people would not need to mess with networking layers. 

Anyways, it's not an essential function, I doubt there's real demand for it, Thank you for your time.
