### ISSUE TITLE
[Device support] RT-AC51U

### ISSUE THREAD

**Issue by tux2000** [Vaskivskyi/ha-asusrouter#153]
### Anything you want to mention?

LED Support and several sensors seem not to be available. These are the sensor that were set up:
![image](https://user-images.githubusercontent.com/1639672/178120441-783aebd4-d100-429c-9fa4-402fa1d4b70f.png)

### Your device model

RT-AC51U

### Firmware type

Stock

### Firmware version

3.0.0.4.380_8591-ga8dd632

### Does everything work well?

No

**Comment by Vaskivskyi** [comment]
Hello, @tux2000,

Thank you for your feedback 👍🏻  and sorry for the late reply.

Unfortunately, firmware 3.0.0.4.380 is too old and does not support some features (including LED control). But there definitely should be more sensors than traffic/speeds on the network interfaces.

Could you please check if there are any disabled sensor entities? Most of the sensors are created in the disabled state by default. Just open the device page of your router in HA and check for "entities not shown" in the list of sensors.
![image](https://user-images.githubusercontent.com/6554415/180390271-a3e26e09-0a3b-462a-b5f8-d29e24e5a378.png)

**Comment by tux2000** [comment]
Indeed, there were several deactivated sensor. Now I got:
![image](https://user-images.githubusercontent.com/1639672/180399881-ecaefdf4-6136-4760-8ff5-02aa3dbc2e21.png)

**Comment by Vaskivskyi** [comment]
PR #169 will add `RT-AC51U` to the supported devices list with a remark, that LED control is not available due to the FW limitations. It will also close this issue.

If you are experiencing any other issues, please open [a new report](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose)
