### ISSUE TITLE
[Feature] Reboot button

### ISSUE THREAD

**Issue by vwt12eh8** [Vaskivskyi/ha-asusrouter#155]
### The problem

I would like a button entity to reboot the router.

This would allow for more control over the reboot scheduler, detecting that the router has become unstable and rebooting it.

### Specific device(s)?

No

### Firmware type

No

**Comment by Vaskivskyi** [comment]
Hey, @vwt12eh8,

Reboot service is coming with PR #180 and will be available in the next release of the integration.

![image](https://user-images.githubusercontent.com/6554415/182693080-200680fc-5d29-4b36-9161-6fa649ba1438.png)
