### ISSUE TITLE
[Feature] Display Ethernet Ports Status

### ISSUE THREAD

**Issue by fookyuanloh** [Vaskivskyi/ha-asusrouter#158]
### The problem

Feature request to get/display status per Ethernet port
Something like below:

![image](https://user-images.githubusercontent.com/79247061/179436508-0d19ac19-f84c-4aff-aaa3-dd294f70f577.png)

Need to capture which port is active - up/down

The one on your desc. may not fit/show the real case:
Ports connection sensors
(disabled by default)

names: lan_speed / wan_speed
units: Mb/s
attributes:
lan_X / wan_X - represents speed of each port x in Mb/s
description: Sensor value represents the total speed on all the connected LAN / WAN ports. E.g. if 2 ports arer connected in 1 Gb/s mode and 1 - in 100 Mb/s mode, this value will be 2100 Mb/s.

### Firmware type

Yes

**Comment by Vaskivskyi** [comment]
Hey, @fookyuanloh,

Thanks for your feedback! 👍🏻 

Could you please provide a bit more info on what you would like to see in the integration? Currently, the attributes for `lan_speed` and `wan_speed` show the following (depending on the number of ports, of course):

![image](https://user-images.githubusercontent.com/6554415/180393160-0678ed4f-ba8d-45fb-b02c-944d198563e8.png)

In principle, this is an `on`/`off` state with more than one value for `on`. In case there is `0`, the port is disconnected, anything else - is connected.

**Comment by fookyuanloh** [comment]
Noted
Thanks for the advise, technically your explanation of speed to indicate ON/OFF could be a workaround now.

Happy to live with that
Let's close this item

**Comment by Vaskivskyi** [comment]
I am happy, this has helped you!
