### ISSUE TITLE
[Device support] Asus DSL-AC68VG Connect. - unknown error 

### ISSUE THREAD

**Issue by xxLexanixx** [Vaskivskyi/ha-asusrouter#159]
### Anything you want to mention?

I can connet to the Router. unkown error

### Your device model

DSL-AC68VG

### Firmware type

Stock

### Firmware version

Version 5.00.09_build274

### Does everything work well?

No

**Comment by Vaskivskyi** [comment]
Hey, @xxLexanixx,

Thanks for your feedback! 👍🏻 

Unfortunately, your device's firmware (5.*) is not supported by the integration (at least, not yet). This is a specific firmware for some Asus devices only and I don't have a device for testing it.

As far as I know, there are AsusWRT-Merlin builds (https://gnuton.github.io/asuswrt-merlin.ng/) which might be compatible with your device (but you should check it and what do other owners say). But ***I cannot recommend*** flashing any other firmware on the device unless you are completely sure it will work. Merlin will work with the integration. That is a decision up to you.

I will add a remark into the readme, that such firmware (and devices) are not supported yet. In case I get any of such devices for testing, the support might eventually come.

Sorry for not being able to help you.

**Comment by Vaskivskyi** [comment]
Since information on the FW 5.* is already added to the readme, I will close this issue. Unfortunately, until I get any such device for tests, I cannot implement any change to the integration
