### ISSUE TITLE
[Bug] Connected device not update

### ISSUE THREAD

**Issue by tintin814** [Vaskivskyi/ha-asusrouter#160]
### The problem

I used this integration with my R7000 router by applying default setup.  Everything works fine except number of connected device doesn't updated until I click the "Download diagnostics" button.  For example, there is 10 devices connected to the router.  After I left home, it should become 9.  It is updated in Asus app, but in this integration it remains 10 for 2 hours later until I click the button.  How can I make an auto refresh?

### Your device model

R7000

### Firmware type

Merlin

### Firmware version

3.0.0.4.380.70_0-X7.9

### Integration version with the issue

0.5.1

### Method of the integration installation

Manual (stable branch)

### What version and type of Home Assistant installation do you use

Frontend 20220707.1 - latest

**Comment by Vaskivskyi** [comment]
Hey, @tintin814,

Thanks for your feedback! 👍🏻 

The integration does suppose to automatically update the number of connected devices. This behaviour you have is out of the usual. Is there anything in the HA log? By default, there will be only Warnings or Errors shown, but that should be enough for now.

Do other sensors update normally or also behave like this?

**Comment by Vaskivskyi** [comment]
Hey, @tintin814,

Can you please check if the issue still persists on the 0.6.0 version? Unfortunately, I don't have R7000 for the tests, but integration seems to handle device trackers well on Merlin 380.70 on Asus devices

By the way, how is it with the other sensors from the integration? Do they work properly? Do you have any errors or warnings in the HA log?

**Comment by tintin814** [comment]
Hi @Vaskivskyi

This issue perisists more than a week and now I moved to nmap tracker without any issue.  Device status is updated automatically in frw minutes when I connect/disconnect from the router.

There was no log/error notification in HA.  Let me know if you need further information.

**Comment by Vaskivskyi** [comment]
[Version 0.6.0](https://github.com/Vaskivskyi/ha-asusrouter/releases/tag/0.6.0) of the integration which I mentioned was released yesterday night and has stability and connection improvements. Since you marked that you installed the integration manually from the stable branch, you would need to update it manually as well. BTW, why didn't you use HACS installation?

**Comment by tintin814** [comment]
Let me try tonight. I'm unable to install HACS because my HA is installed as a docker in my NAS environment.  I know it can be installed through terminal, but unfortunately my NAS doesn't provide any terminal application.

**Comment by Vaskivskyi** [comment]
Hello, @tintin814,

Do you mind checking the new version 0.8.0? I am curious if your device will still experience any problems

**Comment by tintin814** [comment]
Hello @Vaskivskyi , I replaced my R7000 router with a new one for better performance.  R7000 was discharged. Sorry can't help.

**Comment by Vaskivskyi** [comment]
Of course, it's not a problem. I will close the issue since it cannot be tested with the new version by either of us.
