### ISSUE TITLE
[Device support] TUF-AX5400 - [Bug] AiMesh Routers

### ISSUE THREAD

**Issue by BrendanxP** [Vaskivskyi/ha-asusrouter#161]
### Anything you want to mention?

**Confirmed fully working on a TUF-AX5400, including light control!**

Moreover, I have 2 more AiMesh routers; RT-AX82U and BLUE CAVE. When I added the IP of the RT-AX82U, the control for its light did not pop-up under its configuration. However, after I added the BLUE CAVE, both the RT-AX82U and the BLUE CAVE are labelled BLUE CAVE and they both got the control for the light on the RT-AX82U. The light control for the BLUE CAVE did not show up on either. Meanwhile, the main router TUF-AX5400 is still listed properly with only the control for its own light. On the AiMesh routers, the controls for VPN also seem get doubled somehow.

TUF-AX54000
![image](https://user-images.githubusercontent.com/25636915/180471155-2062034b-ef69-481d-a3a2-44d5b255acb7.png)

RT-AX82U auto-labelled as BLUE CAVE
![image](https://user-images.githubusercontent.com/25636915/180471334-47ca8c48-a756-4445-9a94-dafafe25322a.png)

BLUE CAVE
![image](https://user-images.githubusercontent.com/25636915/180471535-9ac1881b-20f8-4f78-ae21-bd136b35e493.png)

### Your device model

RT-AX5400

### Firmware type

Stock

### Firmware version

3.0.0.4.386_48664-g7ded0a1

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hey, @BrendanxP,

Thanks for your feedback! 👍🏻 

I am glad, your AX5400 works well.

Unfortunately, AIMesh support is still in progress for the integration, since I don't have any such device for tests. Eventually, it will be fully implemented, but I cannot guarantee any timeframe yet.

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.17.0 of the integration which implements some of the AiMesh features. [More details here](https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/363?u=vaskivskyi). Also, multiple device usage is improved
