### ISSUE TITLE
[Device support]  Netgear R6300V2 + Merlin 380.70 fully working

### ISSUE THREAD

**Issue by richardzone** [Vaskivskyi/ha-asusrouter#182]
### Anything you want to mention?

After https://github.com/Vaskivskyi/asusrouter/issues/101 is fixed, Netgear R6300V2 is now fully working. Thanks for this awesome integration!

### Your device model

Netgear R6300V2

### Firmware type

Merlin

### Firmware version

380.70

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hey, @richardzone,

Thanks for your feedback! 👍🏻 

I am glad, the integration works well for you. PR #183 will add the device to the supported list and will close this issue. If you experience any problem with the integration or would like to submit a feature request, feel free to open [a new issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose)
