### ISSUE TITLE
[Bug] Connected devices

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#185]
### The problem

To my Router connected 35 device in HA i see only 16 why?, in HA i see only device which are integrated with HA.

### Your device model

RT-AC57U V3

### Firmware type

Stock

### Firmware version

3.0.0.4.386_21649-g7401a04

### Integration version with the issue

on all versions i have this problem

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.8.4

### Is there anything useful in the logs?

```txt
CLEAR
```

### Diagnostics information

[config_entry-asusrouter-5306a76a30591afab7b1c787fc5f2701.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/9331813/config_entry-asusrouter-5306a76a30591afab7b1c787fc5f2701.json.txt)

### Additional information

![image](https://user-images.githubusercontent.com/42905545/184503454-8d6fd372-e34b-49ee-99fc-eb89ad927f29.png)

**Comment by Vaskivskyi** [comment]
Hello, @milandzuris,

Thank you for your feedback! 👍🏻 

The default HA way of handling device trackers is the following:

If the connected device's MAC address is known to Home Assistant (e.g. it was set up by another integration ABC), its device_tracker will be added to that device in the enabled state. Moreover, this device will be showing for both integrations: AsusRouter and ABC

So if your devices' MACs are unknown to HA, they will be created in a disabled state. You can enable them by going to all the entities of AsusRouter integration - click on the number of entities, select the ones you want to enable and click `Enable selected`.

![image](https://user-images.githubusercontent.com/6554415/184541899-bf461179-d5e0-4c35-a305-1ecc8654f7eb.png)
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/6554415/184541932-d813161d-4eef-4aca-b1bb-a4033d28cda3.png">

**Comment by Vaskivskyi** [comment]
Hey, @milandzuris,

Have you tried enabling all the device trackers which are disabled by default in HA? Do you see all the connected devices in this case?

**Comment by milandzuris** [comment]
yes and working

**Comment by Vaskivskyi** [comment]
In this case, since everything is working, I am closing this issue. If you experience any other problem, feel free to open [a new issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose)
