### ISSUE TITLE
[Device support] GT-AX6000

### ISSUE THREAD

**Issue by fi6** [Vaskivskyi/ha-asusrouter#186]
### Anything you want to mention?

As gt-ax6000 being the main router of Asus-merlin's maintainer, it would be nice to have support for such device. However, I can't find my ax6000 in ha-asusrouter and it would be very helpful if this could be fixed. Thanks!

### Your device model

GT-AX6000

### Firmware type

Merlin

### Firmware version

386.7_2

### Does everything work well?

No

**Comment by Vaskivskyi** [comment]
Hello, @fi6,

Thanks for your feedback! 👍🏻 

The list of supported devices does show only those of them tested by me (RT-AX88U and RT-AC66U) or reported by other users. The integration should work with all the other Asus devices (and not only Asus when Merlin is used) as well.

Unfortunately, direct testing of the integration for all the available models on market is not possible (e.g. GT-AX6000 is 380 EUR on Amazon, which is much above my threshold for buying something just to play with) 🙂 

As the practice shows, there are not many bugs related to the exact models of the device (except for some much older models).  So if you experience some problems with the device, please open a bug report - it will be fixed as soon as possible. Alternatively, if you have checked that AsusRouter integration works well with the device - I will add the device model to the list of supported.

**Comment by Vaskivskyi** [comment]
Hey, @fi6,

Did you try AsusRouter integration with your GT-AX6000? Does it work well or does it have any bugs? In the first case, please write it here - I will add the device to the supported list. In the last case, please open a [bug report](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose), so I can solve any issues.

I will close this issue, but you will still be able to reopen it and comment here.
