### ISSUE TITLE
[Bug] Could the addon cause a memory leak?

### ISSUE THREAD

**Issue by gmariotti** [Vaskivskyi/ha-asusrouter#187]
### The problem

Hi, I had the addon installed for less than a week and started to notice the memory usage of my router slowly increasing from 50% to more than 80% in just a couple of days. Using `top`, I noticed that the process with high memory usage is `httpds -s -i br0` so I decided to do a quick test. Disabled the addon, reboot the router, and see the memory usage of the process. Nothing really changed until I started to log in using the WebUI, showing that the memory used by the process increased a bit. Does the addon use the WebUI somehow?

### Your device model

RT-AX58U

### Firmware type

Merlin

### Firmware version

386.7_2

### Integration version with the issue

0.6.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

OS 8.4

**Comment by Vaskivskyi** [comment]
Hey, @gmariotti,

Thanks for your feedback! 👍🏻 

The integration is using the same API, as the WebUI or mobile apps. Even though RAM usage increases with time, this should not be a problem. As soon as it reaches something between 80 and 90% of usage (depending on the model and the FW), the device is supposed to start freeing up some RAM. This is a feature of the Asus firmware.

If you are afraid of RAM usage going up too fast, you might decrease the time for polling the sensors by the integration.

Unfortunately, this is not something that can be completely fixed from my side but there are already some optimizations to decrease the polling intensity implemented, as well as some more coming to the integration soon. Moreover, with the next release of AsusRouter, a new service to reboot the device is coming, which will allow automating device reboot for those models, struggling with a lack of RAM and other bugs coming from the device FW.

**Comment by gmariotti** [comment]
Hey @Vaskivskyi, thanks for the answer, I should have probably tried to see first if the router would free the RAM or not 😅 I'm happy to know that this has nothing to do with the addon, hopefully, it's something that will be addressed at the firmware level.

(BTW, I really love the work you did)
