### ISSUE TITLE
[Feature] Split sensors update intervals

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#189]
### The problem

Make for every category or sensor update interval, i need for tracker update interval 1 second and for ram 30second, the fact that I had it set to 1 second my database increased by 20 GB this is big problem, and bigger for sd and rpi.

**Comment by Vaskivskyi** [comment]
Hello, @milandzuris,

I will check the possibility to split sensor update intervals for different sensors and will let you know whether it can be implemented.

But, in general, I do not recommend polling your router more regularly than with 5 seconds step.

**Comment by Vaskivskyi** [comment]
PR #240 implements this feature and will close this issue. The feature will be available with the next release.
