### ISSUE TITLE
[Bug] Some devices shown in the router page are not in the entities list

### ISSUE THREAD

**Issue by roc634** [Vaskivskyi/ha-asusrouter#190]
### The problem

Hi Vaskivskyi, thank you for creating such a powerful integration. It provides more features than the ASUSWRT integration. However, I can't see some of my devices in the entities list, which are very important to me. I used the ASUSWRT integration last year and it worked like a charm until I upgraded Home Assistant to a new version beginning with 2022. The devices I want to track don't show in the entities list anymore. 
After searching around, I found the integration you created, but I still can't see the devices I want to track showing up in the list. Could you please help me with that?

The circled two devices are the ones that I want to track how many hours do I use in a week. They are TV and treadmill. I can see them in the page of router like below:
<img width="694" alt="2022-8-22 1-04-48" src="https://user-images.githubusercontent.com/49619054/186487427-22aa7572-e658-4cae-9485-e0a71457e5de.png">
But I can't find them in the entities list:
<img width="904" alt="2022-8-25 1-42-39" src="https://user-images.githubusercontent.com/49619054/186487509-065a7c89-93c7-4d4c-bffd-e7fa4aa80216.png">
I've selected most of the interfaces to monitor in configurations
<img width="306" alt="2022-8-25 1-43-13" src="https://user-images.githubusercontent.com/49619054/186487699-43926f22-170c-4b60-b990-364e55972bac.png">

I've been searching online and tried all the means I can figure out, but there is still no luck. Your help will be greatly appreciated. Thanks!

### Your device model

R6300V2

### Firmware type

Merlin

### Firmware version

380.70_0-X7.9.1

### Integration version with the issue

0.6.0

### Method of the integration installation

Manual (stable branch)

### What version and type of Home Assistant installation do you use

Core 2022.5.5

**Comment by Vaskivskyi** [comment]
Hello, @roc634,

Thanks for your feedback! 👍🏻 

Let's try to determine whether this is only a `device_tracker` problem or an API problem.

Does the `sensor.{device_name}_connected_devices` show the correct number of connected devices? It has also the attribute `devices`, which is the complete list of `MAC/IP/Hostname` values. Are your missing devices listed there, when you can see them in the WebUI?

**Comment by roc634** [comment]
> 

Thanks for your prompt reply , @Vaskivskyi .
After posting my question here, I tried the nmap mathod. This morning when I use treadmill, namp can detect it while ha-asusrouter can't. Please see the screenshot below.
Nmap gets 18 devices:
<img width="222" alt="2022-8-25 10-32-34" src="https://user-images.githubusercontent.com/49619054/186561528-d362105a-66ef-4412-b2a8-3689490b2c23.png">
while ha-asusrouter gets 15 devices:
<img width="424" alt="2022-8-25 10-32-54" src="https://user-images.githubusercontent.com/49619054/186561575-892f41ef-8060-4641-86ee-fecdbdeb5ed0.png">
The treadmill is in the nmap entities list but it in neither the entities list of ha-asusrouter nor attributes of the sensor.r6300v2_connected_devices.

**Comment by Vaskivskyi** [comment]
For me, NMAP is always showing something random (lots of devices are missing in comparison to the router report).

Could you please compare `sensor.{device_name}_connected_devices` to the client list in the AsusWRT web panel? Is it smaller? On your first screenshot, there were both devices marked. If they are not reported by the integration in HA, `connected devices` should be smaller.
![image](https://user-images.githubusercontent.com/6554415/186583498-62c60321-3899-4a61-bdec-400f74c21330.png)

Is there anything in the HA logs as warnings or errors from the AsusRouter?

**Comment by roc634** [comment]
> 

Thanks for your help. The number of clients will change since some of my neighbours and friends connect to my router and my family members will turn on and off some devices. However, as you suggest, I find two lines of error message in the log, please see below:
`2022-08-25 15:48:21 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.2.1' for asusrouter integration not ready yet: ("Cannot connect to host 192.168.2.1:8443 ssl:True [Connect call failed ('192.168.2.1', 8443)]", None); Retrying in background`
`2022-08-25 15:49:00 ERROR (MainThread) [asusrouter.connection] Error sending a command hook=get_clientlist() to appGet.cgi. Exception: Expecting property name enclosed in double quotes: line 1 column 20 (char 19)
`
What can I do to solve this?

**Comment by Vaskivskyi** [comment]
The first one is fine - it is just a notification, that something went wrong during the connection to the router.

The second one should be related to the problem. But with the reported error, you should not get any data from the client list. So your HA `device_tracker`s, as well as the `connected_devices` sensor, should not update at all.

Does this error show up regularly? I would guess, no, but let's find that out.

I will prepare some Python code for you to run, so we can test the raw output from the device API and find the reason for the error. But this could take a bit of time.

**Comment by roc634** [comment]
> 
Thank you very much for your patience. 
I'm not sure if this error show up regularly or not. I didn't check the log before until you reminded me of this. I used the offcial asuswrt integration until this year and it worked fine. I updated Home Assistant to some version beginning with 2022 this year and suddenly I noticed that device tracker didn't work for some devices. And then I found your integration, I'd like to stick to it if it works since this integration offer more features and can control my router. 
I'm not sure if it's the problem of my router or not. I'd appreciate that you write a specific tool for me to test and help me find out the reason.

**Comment by Vaskivskyi** [comment]
Hello, @roc634,

### Read this the first -->
When running the code, the RAW answer of your device might contain the MAC and IP (local) addresses of your devices. Please check it before posting anything from the output here as an answer. It is a good idea not to post those 🙂 **<-- Read this the first**

### Answer
Sorry for the delay. Could you please try running this Python script from any python environment with the AsusRouter library installed? Just put the code to some `script.py` and then run the `python3 script.py` command (or another correct command for your environment). If you are missing the AsusRouter library, you might install it running `pip3 install asusrouter`. But it is already installed if you will try to run the script from the HA venv.

Don't forget to change the hostname, username and password for the correct ones.

<details>
<summary>Code</summary>

```python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
import asyncio
import json
from typing import Any


LIST_PI = [
    "amesh_papMac",
    "mac",
    "ip",
]


def echo(data: str) -> None:
    """Echo data"""

    print(json.dumps(data, indent = 4))


async def hide_pi(data: dict[str, Any]) -> dict[str, Any]:
    """Hide private information from the dict"""

    result = dict()

    i = 0
    for el in data:
        id = f"redacted_{i}"
        result[id] = data[el]
        for item in LIST_PI:
            if item in result[id]:
                result[id][item] = "-=REDACTED=-"

        i += 1

    return result


async def gather_data(host, username, password, port, use_ssl, cert_check):
    """Method to gether all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, port = port, use_ssl = use_ssl, cert_check = cert_check)

    command = "hook=get_clientlist()"
    endpoint = "appGet.cgi"

    # Connect
    await router.connection.async_connect()

    # Send a command / request

    if router.connection._token is None:
        await router.connection.async_connect()
    else:
        if router.connection._token is not None:
            try:
                result = await router.connection.async_request(command, endpoint, router.connection._headers)
                result = await hide_pi(result["get_clientlist"])
                echo(result)
            except Exception as ex:
                print(ex)
                try:
                    async with router.connection._session.post(
                        url="{}://{}:{}/{}".format(
                            router.connection._http, router.connection._host, router.connection._port, endpoint
                        ),
                        data=urllib.parse.quote(command),
                        headers=router.connection._headers,
                        ssl=router.connection._ssl,
                    ) as r:
                        string_body = await r.text()
                        print(string_body)
                except Exception as ex:
                    print(ex)

    # Disconnect
    await router.connection.async_disconnect()


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "hostname"
_username = "admin"
_password = "password"
_port = 0
_use_ssl = True
_cert_check = False

loop.run_until_complete(gather_data(_host, _username, _password, _port, _use_ssl, _cert_check))

loop.close()
```
</details>

If this will run successfully, you will get an output in your console similar to the following (with IPs and MACs being redacted already):

<details>
<summary>Example of successful output</summary>

```
{
    "redacted_0": {
        "type": "0",
        "defaultType": "0",
        "name": "Intel Corporate",
        "nickName": "",
        "ip": "-=REDACTED=-",
        "mac": "-=REDACTED=-",
        "from": "networkmapd",
        "macRepeat": "0",
        "isGateway": "0",
        "isWebServer": "0",
        "isPrinter": "0",
        "isITunes": "0",
        "dpiType": "",
        "dpiDevice": "",
        "vendor": "Intel Corporate",
        "isWL": "0",
        "isGN": "",
        "ssid": "",
        "isLogin": "0",
        "opMode": "0",
        "rssi": "0",
        "curTx": "",
        "curRx": "",
        "totalTx": "",
        "totalRx": "",
        "wlConnectTime": "",
        "ipMethod": "Manual",
        "ROG": "0",
        "group": "",
        "callback": "",
        "keeparp": "",
        "qosLevel": "",
        "wtfast": "0",
        "internetMode": "allow",
        "internetState": "1",
        "amesh_bind_mac": "",
        "amesh_bind_band": "0",
        "isOnline": "1"
    },
### And much more data for each connected device
}
```
</details>

If not successfully, the output will be the raw answer from the device. In this case, **IT WILL CONTAIN IPs AND MACs** - please, **DO NOT POST** it as an answer here.

In the latter case, you might manually edit the sensitive information before posting it.

You can also send me the data by email (Yevhenii@Vaskivskyi.com) or via [Telegram](https://t.me/Vaskivskyi) if you don't want to bother with redacting it and you trust me enough 🙂 In this case, please send it in a text file.

**Comment by roc634** [comment]
> 

Wow, thank you so much for writing a specific tool for me. But I'm under quarantine now. Hopefully I can go home within 2 or 3 days. I'll get back to you again. Sorry for the inconvenience.

**Comment by Vaskivskyi** [comment]
Hey,

Could you please check whether you still have the same issue after updating to the new version 0.11.0 of the integration? The integration has already quite a several features implemented, which are helping with the connected devices list.

**Comment by roc634** [comment]
Hi Vaskivskyi, thanks for your heads-up. I'll try it right away and will get back to you asap. Have a nice day!
>

**Comment by roc634** [comment]
Hi @Vaskivskyi , I try to replace the whole folder with that that of the new version but it fails to setup. Please refer to the screenshot below:
<img width="578" alt="2022-11-3 23-57-16" src="https://user-images.githubusercontent.com/49619054/200035059-9494b4c4-2325-443a-bb9c-6f4c90882075.png">
and I can find only one line in the log:
`WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.2.1' for asusrouter integration not ready yet: 'NoneType' object is not subscriptable; Retrying in background`
I try to restart and reboot but both fail. 

prior to this, when I try to use the previous version, the devices I would like to track show online all the time even though they are actually offline. Pleae refer to the screenshot below. 
<img width="300" alt="2022-9-20 23-59-51" src="https://user-images.githubusercontent.com/49619054/200037060-ce2c4ec4-9990-47e7-bb21-c676cc14e3fc.png">
<img width="294" alt="2022-9-21 0-0-4" src="https://user-images.githubusercontent.com/49619054/200037087-179d243b-fa79-4533-8f97-5c088fc10950.png">

After trying for quite some time I have to switch back to the ASUSWRT integration. I thought I've reported that to you, but I didn't realized I haven't done that until you reminded me the new version several days ago. Sorry for the inconvenience. Could you please help me solve this? Thanks very much!

**Comment by Vaskivskyi** [comment]
Hey, @roc634,

Please, check the new version 0.11.3, which is already available via HACS. It should solve the integration setup problem

**Comment by roc634** [comment]
> Hey, @roc634,
> 
> Please, check the new version 0.11.3, which is already available via HACS. It should solve the integration setup problem

I don't have HACS so I download the files from github. However, the problem is the same. The devices appear online all the time. Actually they are online for just one or two hours. Please see the screenshots below. 
<img width="299" alt="2022-11-7 2-9-18" src="https://user-images.githubusercontent.com/49619054/200187734-4c5a5d73-6262-460b-a9b7-196c8440b4d5.png">
<img width="295" alt="2022-11-7 2-9-39" src="https://user-images.githubusercontent.com/49619054/200187742-7dc35aab-c14a-48f5-aca0-2b48bc378e23.png">

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.17.0 of the integration. Improvement of device trackers has been implemented
