### ISSUE TITLE
[Feature] Add attribute in device tracker "connected_in" (Node in Aimesh)

### ISSUE THREAD

**Issue by wallacemreis** [Vaskivskyi/ha-asusrouter#203]
### The problem

Is it possible to add an attribute in device_tracker that shows which node (Aimesh) the device is connected ?

This would help a lot in bayesian sensors for presence detection or device balancing

**Comment by Vaskivskyi** [comment]
Hello, @wallacemreis,

Thanks for your feedback! 👍🏻 

The full AiMesh functionality is planned for the integration. Unfortunately, I still don't have a second device for all the needed tests, so I cannot yet guarantee any timeframe. But it will be implemented. I'll check if a node attribute for the device_tracker can be implemented sooner.

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.17.0 of the integration which implements some of the AiMesh features. [More details here](https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/363?u=vaskivskyi)

**Comment by dennisgranasen** [comment]
The AiMesh functions in 0.17.0 are good. I'd love the feature that @wallacemreis requests as well, and this looks like a promising start.

A question out of curiosity, the "level" attribute that is displayed on my AiMesh nodes is always 0. What does it mean?

**Comment by Vaskivskyi** [comment]
@dennisgranasen,

Hello. Actually, device trackers already have attribute showing which node they are connected to. It's called `node` and shows the MAC address of the node.

The level is literally the level in the AiMesh hierarchy. The main router is always `0`. All the nodes connected with a `wired` connection are also `0` (by AiMesh definition). Nodes connected wirelessly to level `0` (parents) are level `1` (children). The next children will be level 2 and so on.

In case all of your nodes are level `0` - I suppose - they are connected in the wired mode? If not, please, open a new issue regarding the topic.

**Comment by dennisgranasen** [comment]
Wow, thanks. I failed to notice that attribute on device trackers, that's
great!
You are right that my mesh nodes use a wired backbone, so level 0 is
correct then! Thanks for clarifying. Perhaps this information should be in
the wiki, or maybe it is too obvious to everyone but me?





Den tis 10 jan. 2023 kl 16:41 skrev Yevhenii Vaskivskyi <
***@***.***>:

**Comment by Vaskivskyi** [comment]
@dennisgranasen,

Unfortunately, I did not have time yet to add all the details to the documentation - development itself and debugging is taking too much time to fit into 24 hours. But I will add this info as well as some more soon

**Comment by dennisgranasen** [comment]
You are doing great work Yevhenii!

**Comment by wallacemreis** [comment]
I think we can close this issue
