### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by Wyman42** [Vaskivskyi/ha-asusrouter#212]
### The problem

Hello, I installed this integration via HACS (on HA OS and Raspberry pi3).
The installation is OK when I search for "AsusRouteur" via the additional modules of HA, I only find the native integration AsusWRT ?

### Your device model

RT-AC52U B1

### Firmware type

Stock

### Firmware version

3.0.0.4.380

### Integration version with the issue

0.8.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Home Assistant 2022.8.7

**Comment by Vaskivskyi** [comment]
Hello,

After installing the integration, did you restart your Home Assistant? This is required for the HA to discover new integration

**Comment by Wyman42** [comment]
Yes...

**Comment by Wyman42** [comment]
After uninstall a unless integration and another reboot, it's OK I have AsusRouteur.
Thanks for your time.
