### ISSUE TITLE
[Feature] enable and disable guest networks

### ISSUE THREAD

**Issue by nchieffo** [Vaskivskyi/ha-asusrouter#213]
### The problem

Would be good to have a switch to enable and disable the 6 guest networks that can be configured in the router

**Comment by Vaskivskyi** [comment]
Hello, @nchieffo,

Thanks for your feedback! 👍🏻 

This feature is already planned for integration and will be coming in one of the future releases. Let's say somewhere in September (since there are also some new features and bugs with higher priority).

**Comment by Vaskivskyi** [comment]
Hey,

PR #284 adds the requested feature and many other ways to control guest WiFi networks. When merged, the PR will close this issue.

The feature will be released in the following integration version (by the end of the month)
