### ISSUE TITLE
[Bug]  this integration does not support configuration via UI error

### ISSUE THREAD

**Issue by tismofied** [Vaskivskyi/ha-asusrouter#214]
### The problem

Running HA on proxmox. I had this integration before but I have had to delete to test something. Now I want to install it back and I keep getting this error

### Your device model

RT-ACRH17

### Firmware type

Stock

### Firmware version

3.0.0.4.382.52517

### Integration version with the issue

0.8

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.8.7

### Additional information

I get this error when trying to add the integration through HA devices and integration menu. 

![FF440BFD-0B29-4369-9E12-37233AA14750](https://user-images.githubusercontent.com/90809124/187990465-222b6f19-5539-4833-b1dc-4d5721af1346.jpeg)

**Comment by tismofied** [comment]
I rolled back and it worked

**Comment by Vaskivskyi** [comment]
Hello, @tismofied,

Nothing has been changed in the integration configuration flow between versions 0.7.0 and 0.8.0, as you can check in the [commits history](https://github.com/Vaskivskyi/ha-asusrouter/commits/main).

Was there anything in the logs when you have seen the message on the snapshot in your issue? With such an error, it is not just a problem for loading the configuration flow (that one is different), but not a possibility for HA to find `config_flow.py` at all.

**Comment by tismofied** [comment]
I'll do a backup and update to 0.8 and try again.

**Comment by Vaskivskyi** [comment]
Hello, @tismofied,

Do you have any updates on the issue? Did you have a chance to check whether there are any errors in the log?

**Comment by tismofied** [comment]
I don't know what happened then but removed everything from hacks and from integrations and restarted the host. Everything came back online. Funny thing is Paulus himself got an error like mine in his Bluetooth _proxy stream with a different integration and he looked confused lol. Anyways, your inouïs running flawless now with 2 Asus routers. Rt-ACRh17 as an AP and RT-N66U ( running latest supported Merlin) as a repeater. 

PS: the only thing I noticed and this could be me not knowing how to do things is the speeds displayed seems very low to what actual speeds of the modem are. Maybe something I missed in settings?
![image](https://user-images.githubusercontent.com/90809124/193021001-d58c6f48-285a-40fc-8d0b-fbf8c225826a.jpeg)

**Comment by Vaskivskyi** [comment]
Can you please compare these values to the ones you see in the Asus Web UI for real-time traffic? Having low enough speeds when devices are not actively communicating is completely fine, but as soon as you try transferring data, you should see relatively high peaks.

**Comment by tismofied** [comment]
Sorry I had some stuff going on and I totally forgot about this.
