### ISSUE TITLE
question

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#215]
### The problem

whats the wired and bridge trafic monitor?, lan trafic?

### Your device model

*************

### Firmware type

Stock

### Firmware version

**************

### Integration version with the issue

***********

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

*********

**Comment by Vaskivskyi** [comment]
Hello, @milandzuris,

`Wired` traffic is all the traffic passed over the physical ports of the device.

`Bridge` traffic is all the traffic over the device's local network (LAN).

**Comment by Vaskivskyi** [comment]
I suppose, your question was solved? In this case, I will close the issue. Feel free to reopen it or open a new one if you have any more questions or experience any problem with the integration.
