### ISSUE TITLE
[Bug] RAM leak

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#216]
### The problem

my HA ram before instaled your integration they have 60-65% ram usage, after instaled integration my HA ram usage is 85-95%, and crash HA, im try set time update to 30-60 and more don't solve my problem, optimize integration please, this integration so good and have one problem.

today my HA crash 15 times when im delete integration ha working on 100%

### Your device model

RT-AC57U V3

### Firmware type

Stock

### Firmware version

*****************

### Integration version with the issue

*********************

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

******************

**Comment by Vaskivskyi** [comment]
Hello, @milandzuris,

Could you please specify the following:

- Version of integration with a problem
- Did this start with the last version of the integration? Did it work well before?
- Version and type of installation of your HA
- What hardware do you use and how do you monitor RAM usage

- What configurations of the integration are you using?
- How regularly do you poll the sensors? This is the `Interval to update entities` value which can be selected during the configuration.

- **Does the HA log show any errors from the integration?**

Please, opening the issue, do not ignore the template, which does explicitly ask half of the questions from the above. This will help speed up any troubleshooting and bug fixing.

**Comment by Vaskivskyi** [comment]
Hello,

Unfortunately, without the information I have asked for, I cannot help you with the issue. RAM leak was never reported before by other users and I have never observed it yet.

If you would like to add any more information, that would help with diagnosing and solving the issue, feel free to reopen this issue.
