### ISSUE TITLE
[Device support]

### ISSUE THREAD

**Issue by tismofied** [Vaskivskyi/ha-asusrouter#217]
### Anything you want to mention?

**### Attributes the integration pulled!**

**Sensors:**

2.4Ghz Download Speed
5Ghz Download Speed
RT-AC82U BRIDGE Download
RT-AC82U BRIDGE Download Speed
RT-AC82U BRIDGE Upload
RT-AC82U BRIDGE Upload Speed
WIRED Download
WIRED Download Speed
WIRED Upload
WIRED Upload Speed
WLAN0 Download
WLAN0 Upload
WLAN0 Upload Speed
WLAN1 Download
WLAN1 Upload
WLAN1 Upload Speed
Wireless 2.4 GHz
Wireless 5 GHz
RT-AC82U OpenVPN Client 1
RT-AC82U OpenVPN Client 2
RT-AC82U OpenVPN Client 3
RT-AC82U OpenVPN Client 4
RT-AC82U OpenVPN Client 5

**Diagnostic:**

Boot Time
CPU
Connected Devices
LAN Speed
RAM
WAN
WAN IP
WAN Speed

The only thing I could add is the router came up as a different model than the one I have. I have **RT-ARCH17** but the integration is showing attributes under model **RT-AC82U**

### Your device model

RT-ACRH17

### Firmware type

Stock

### Firmware version

3.0.0.4.382_52517

### Does everything work well?

No

**Comment by Vaskivskyi** [comment]
Hello, @tismofied,

Thank you for your feedback! 👍🏻 

As I see, you don't have LED control (which is probably due to firmware 382 limitation). Is any other sensor missing from what you would expect? Don't you have WAN speed and traffic sensors (WAN Upload, WAN Download, WAN Upload Speed and WAN Download Speed) or you just didn't select the WAN interface for monitoring?

With model names, it happens for some models. Unfortunately, Asus does not make it easy, having 5 different names saved in the device memory, with only some of them being correct.

**Comment by Vaskivskyi** [comment]
The device will be added to the supported list in PR #219 with a remark of a wrong model reporting in HA and LED control not being available. If you have any other comments, you can post them here. If you want to report any problem running the integration, please open a new issue.

**Comment by tismofied** [comment]
> Hello, @tismofied,
> 
> 
> 
> Thank you for your feedback! 👍🏻 
> 
> 
> 
> As I see, you don't have LED control (which is probably due to firmware 382 limitation). Is any other sensor missing from what you would expect? Don't you have WAN speed and traffic sensors (WAN Upload, WAN Download, WAN Upload Speed and WAN Download Speed) or you just didn't select the WAN interface for monitoring?
> 
> 
> 
> With model names, it happens for some models. Unfortunately, Asus does not make it easy, having 5 different names saved in the device memory, with only some of them being correct.

I don't know why WAN is not exposed from my router. These are the snaps of configuration I get.![image](https://user-images.githubusercontent.com/90809124/188698713-3037135b-bba1-43be-8609-a538fde8fcd7.png)

![image](https://user-images.githubusercontent.com/90809124/188698804-85aa9529-5e9e-43ca-a129-fefbfe1708ff.png)

![image](https://user-images.githubusercontent.com/90809124/188698825-85096532-7066-4a0f-9470-c6886937683b.png)

**Comment by Vaskivskyi** [comment]
In the router web panel, you can try going to the Traffic monitor page (Fig. 1).

<details>
<summary>Fig. 1</summary>

![image](https://user-images.githubusercontent.com/6554415/188731565-071b2da5-8451-4b6c-b618-161a1c4c6c30.png)
</details>

After that press F12 to open the Developer tools of your browser. Find a tab called Network (which might vary depending on your browser). You will see all the requests sent from the web panel and the replies (Fig. 2).

<details>
<summary>Fig. 2</summary>

![image](https://user-images.githubusercontent.com/6554415/188732043-9a9b9527-3ee5-4c48-baad-a94127392af7.png)
</details>

Find the one to `update.cgi` (any of them, they are sent each 1-3 seconds). Its reply should be similar to the following. 

```
netdev = {
    'BRIDGE':{rx:0x3d0557dc0,tx:0x2630b46dcd},
    'INTERNET':{rx:0x17ed28b028,tx:0x25f6778dd},
    'WIRED':{rx:0x346ae54b5,tx:0x1e8ad8aa7b},
    'WIRELESS0':{rx:0x401bb39e,tx:0x23a8920b},
    'WIRELESS1':{rx:0x157cbfafd,tx:0x77a82dd95}
}
```

Post it here, please. We'll try to find out, why you don't have WAN in the integration.

**Comment by Vaskivskyi** [comment]
Yes, in AP mode, WAN monitoring does not work the way it works for the router mode
