### ISSUE TITLE
[Device support] GT-AX11000

### ISSUE THREAD

**Issue by ToasterDEV** [Vaskivskyi/ha-asusrouter#218]
### Anything you want to mention?

So far when trying to configure the router both via IP and hostname with or without SSL I get stuck at the "Connection Refused" step. I'm trying to add both this model and my RT-AX86U, which the latter so far functions perfectly while using the same firmware version.

### Your device model

GT-AX11000

### Firmware type

Merlin

### Firmware version

386.7_2

### Does everything work well?

No

**Comment by Vaskivskyi** [comment]
Hello, @ToasterDEV,

Thanks for your feedback! :+1:

When you are getting a `Connection refused` error on the simplified setup on the initial configuration of the integration, you are redirected to the [full setup mode](https://github.com/Vaskivskyi/ha-asusrouter/blob/main/docs/setup.md#2b-complete-device-setup).

At this step, you can enter some more values, including the `port` manually, if you are using a non-standard one. But the most important part is, if the full setup fails as well with the same error, its details will be shown in the Home Assistant log. Please, check the log and let me know, what it says.

**Comment by ToasterDEV** [comment]
Hello @Vaskivskyi,

Oddly enough I just retried the setup today and it went through without a problem, even while still using full setup mode and changing the SSL port to 443. Now both devices are working with all of the available sensors.

I'm not sure what changed between yesterday and today, though I have a suspicion it might have something to do with having recently logged in yesterday to the admin panel before configuring the integration.

In any case, thanks for the swift reply, and kudos for creating the software!

I believe the device could be added to the support list now, now all that's left for me is AiMesh support.
