### ISSUE TITLE
[Feature] Add check for available firmware

### ISSUE THREAD

**Issue by sepodele** [Vaskivskyi/ha-asusrouter#222]
### The problem

Can you add a diagnostic update entity that checks for new firmware available?

**Comment by Vaskivskyi** [comment]
Hello, @sepodele,

Thanks for your feedback! :+1:

This feature is possible and I will add it to the `to-do` list. Unfortunately, I cannot yet guarantee the exact timeframe to implement it.

**Comment by Vaskivskyi** [comment]
![image](https://user-images.githubusercontent.com/6554415/198712179-0939a21f-9212-4f27-93a7-80baa0466604.png)

Will be available in 0.11.0 soon
