### ISSUE TITLE
[Feature] Enabling/disabling OpenVPN server?

### ISSUE THREAD

**Issue by sepodele** [Vaskivskyi/ha-asusrouter#224]
### The problem

Possible to make a switch that enables/disables OpenVPN server? That would be really neat.

**Comment by Vaskivskyi** [comment]
Hello, @sepodele,

Thanks for your feedback! :+1:

This feature is possible. I will add it to the list of future improvements.

**Comment by Vaskivskyi** [comment]
Coming in 0.11.0 soon

<details>
<summary>Snapshot 1</summary>

![image](https://user-images.githubusercontent.com/6554415/198824407-c31a5a99-5e19-40df-9c6b-3bdba28aac54.png)
</details>

<details>
<summary>Snapshot 2</summary>

![image](https://user-images.githubusercontent.com/6554415/198824402-77caa8ba-47ab-4ac2-b1c0-80586a4fb977.png)
</details>
