### ISSUE TITLE
[Bug] Wireless password as attribute 

### ISSUE THREAD

**Issue by snp88** [Vaskivskyi/ha-asusrouter#255]
### The problem

Hi I notice that Wireless sensors for this integration show Wireless password in plain text as entity attribute 
Is such an action intentional?
Displaying the wireless network password is not the best idea 
We can make it as an option ? 

### Your device model

RT-AX92U

### Firmware type

Stock

### Firmware version

3.0.0.4.386_46061-g9a06866

### Integration version with the issue

0.91

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.10

**Comment by Vaskivskyi** [comment]
Hello, @snp88,

Thank you for your feedback! :+1:

The integration in this case mimics the official Asus app for phones. Passwords are only shown inside HA and are not exported in the diagnostics (as well as any other sensitive information).

In principle, I would consider the HA instance as already secure enough to not worry about WiFi passwords.

But of course, if you suppose your HA can be used by someone, who should not have access to this information, I can try to add a switch to disable password in the attributes. Would it be a valid solution?

**Comment by Vaskivskyi** [comment]
![image](https://user-images.githubusercontent.com/6554415/197348742-57ca2e3a-e8e7-4444-a081-361efe012f5a.png)

PR #271 is implementing a switch to hide passwords (do not add such attributes at all) from any sensors. When merged, the PR will close this issue.

The change will be released with the next AsusRouter version (planned in the following two days)

**Comment by snp88** [comment]
Great job thx can't wait for this update ;)
