### ISSUE TITLE
Ability to enable/disable internet access for specific clients

### ISSUE THREAD

**Issue by poida97** [Vaskivskyi/ha-asusrouter#258]
### The problem

Per comment at :
https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/69

It would be great if we had the ability to control (on/off) internet access for certain clients.
Objective is to have HA manage "smarter" daily internet limits for the kids devices.

**Comment by poida97** [comment]
maybe similar to #146

**Comment by Vaskivskyi** [comment]
Hello, @poida97,

Thanks for your feedback! :+1:

Yes, this feature is the same as suggested in #146 and is already in development.

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.12.0, which adds functionality to allow/block internet access for a single device. [More info here](https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/211?u=vaskivskyi)

**Comment by Vaskivskyi** [comment]
Since the feature is already implemented in 0.12.0 and other users do not report any problems with it, I will close this issue.

**Comment by dominicusmento** [comment]
@Vaskivskyi this should be reopened as it's not available anymore in new version but there are people who are using it..

**Comment by Vaskivskyi** [comment]
@dominicusmento, #673
