### ISSUE TITLE
[Device support] Asus RT-AC5300

### ISSUE THREAD

**Issue by Salvora** [Vaskivskyi/ha-asusrouter#259]
### Anything you want to mention?

Works with no visible problem.

### Your device model

RT-AC5300

### Firmware type

Merlin

### Firmware version

386.7_2

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello, @Salvora,

Thank you for your feedback! :+1:

I am glad, the integration works well for your device. PR #260 will add it to the supported devices list and close this issue.
