### ISSUE TITLE
[Bug] Aimesh node issue (Tracking the node status)

### ISSUE THREAD

**Issue by Salvora** [Vaskivskyi/ha-asusrouter#261]
### The problem

Basically, I want to be notified when a node goes down and show this on the frontend. I have partially managed to get this working on the HA Asus integration though it is not very reliable. So, I wanted to switch over this custom integration which I find surprisingly well made. Kudos for that. Thanks for your work.

I will briefly mention the HA integration. When nodes are in ethernet backhaul mode, everything looks good, however, if one node switches to the wireless backhaul, the integration creates another device_tracker entity with a different randomly generated MAC address which makes it hard to keep track of all the changes.

To get around that, I needed to create an overly complex setup by publishing `nvram get cfg_device_list` results via snmp.

Anyway, I have setup the integration and my nodes showed up as device_tracker entities with connection_type attributes which is exactly what I wanted. In theory, there should be  4 (3 if you combine 5G-1 and 5G-2) states for the connection_type (2.4G, 5G-1, 5G-2, Wired)

- The first problem I noticed was the connection type. I purposely switched one node to Wi-Fi but the integration reported it as 2.4 GHz. It should have been 5G (I have double checked this from within the router GUI).
- When a node switches from wifi to wired, the connection_type does not change and stays as 2.4 GHz. This is a huge deal breaker for me because I cannot accurately track the node status. **I didn't test it yet but this might also be true for any device which can connect by LAN or Wi-Fi like a printer or a pc.**
**Edit:** On second thought, it is not possible for other devices because they have different MAC addresses for different NICs.

I know that aimesh support is requested [here](https://github.com/Vaskivskyi/ha-asusrouter/issues/203) but I want to pitch in and suggest that if/when you add aimesh support, please add a separate attribute like **node_backhaul_status** which reports 3 values **Offline**, **Wireless**, and **Wired**

I also would like to suggest adding another **last_known_ip** attribute to the device_tracker entities. It is especially useful when you try to track nodes but it will not hurt to have it for all device_trackers.

Again, thanks for your hard work and great job.

### Your device model

RT-AC5300

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.7_2

### Integration version with the issue

0.9.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

core-2022.10.4

### Is there anything useful in the logs?

```txt
None
```

**Comment by Vaskivskyi** [comment]
Hello, @Salvora,

Thanks for your feedback! :+1:

Unfortunately, I don't have any possibility of implementing AiMesh support yet - for that, I would require an additional device with AiMesh to perform all the needed tests.

But as soon as I have such a possibility, I will start implementing the AiMesh functionality. Of course, I will consider your suggestions as well. And I will add this issue as a reference to the development status in the README.

**Comment by edwardtfn** [comment]
@Vaskivskyi, do you have a router with AiMesh support? I mean, do you need just one additional device, or you need both in order to setup your testing AiMesh network?
I'm also interested in the support for AiMesh, so perhaps the community here can try to help funding so you can get a second device... (no promises, just an idea).

**Comment by Vaskivskyi** [comment]
@edwardtfn, my main device (RT-AX88U) has full AiMesh support. But yes, I need one more device with AiMesh for all the tests.

I cannot just ask users of the integration to "buy me a device for tests". That would be not really polite. So I am just saying - as soon as I get a device, I'll start work on the feature. Maybe there would be some good deals on Amazon for Black Friday 🙂

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.17.0 of the integration which implements some of the AiMesh features. [More details here](https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/363?u=vaskivskyi)

**Comment by Salvora** [comment]
Hmm, I checked the notes but I cannot make sense of the aimesh node mode. Is it for adding the nodes as separate devices to the HA?
If so, it might be troublesome because the node ips are not static most of the time and assigning satic ips to the nodes are not advisable since all the ips and comms are managed by the main router.
Under **Connected Devices** tab of the main router in the integration devices, I can see all my nodes just fine but I only see the "**connected**"status. Is it possible to discern whether it uses wired or wireless backhaul?

**Comment by Vaskivskyi** [comment]
@Salvora, hello,

Actually, you don't have to add each AiMesh node separately - only if you want to monitor their temperatures, RAM / CPU usage and so on - so those features are marked in the release notes as available for the `node` mode of integrating device.

---

If your main router is added to AsusRouter as a `router` device (enabling all the features), you are getting 1 `binary_sensor` per each AiMesh device in your network. This sensor shows the connection state (connected/disconnected) and its attributes provide other AiMesh-related data (check the snapshot)

<details>
<summary>Snapshot</summary>

![image](https://user-images.githubusercontent.com/6554415/211609957-41be5248-2999-4861-a213-9afbbe761797.png)
</details>

These binary sensors are created in a HA devices - one sensor per one device

![image](https://user-images.githubusercontent.com/6554415/211610675-dff2e7be-0a9c-4ade-ab51-3f87cd592507.png)

Also, you are getting AiMesh sensor showing number of nodes (+ router) with useful node data in attributes
![image](https://user-images.githubusercontent.com/6554415/211610353-2c0fd7ec-77dd-404a-a11f-ccb546b88f6d.png)

---

Adding each node separately as a `node` will add some sensors, but is not obligatory. Also, does the IP of the node change? I have performed lots of tests with my AiMesh network and never node changed IP (even though, they are not set manually via DHCP)

**Comment by Vaskivskyi** [comment]
I hope it will work well for you.

If you would like to suggest a new feature or report a bug, please open a new report :+1:
