### ISSUE TITLE
[DEVICES] Not reporting WAN traffic / speed <- add in here, please

### ISSUE THREAD

**Issue by Vaskivskyi** [Vaskivskyi/ha-asusrouter#30]
:lady_beetle: Some Asus devices are known to not report WAN traffic. That means also the speed cannot be calculated. I am currently looking in the walk-around to get this data for the full user experience.

In case, you are experiencing this issue, please add your device model and firmware version in the comments.

List of known devices not reporting WAN data:
- RT-AC86U (FW: 3.0.0.4.386_48260) (via https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/8)
- RT-AX88U (FW: 3.0.0.4.386_45934) (via https://github.com/Vaskivskyi/ha-asusrouter/issues/16#issuecomment-1121311921)

**Comment by Vaskivskyi** [comment]
An RT-AX88U (FW: 3.0.0.4.386_48631) does NOT show such a problem. Could it be related to the AiMesh? The one with the problems in the original issue was using it. This one does not 🤔

**Comment by leonidfeldman1977** [comment]
> An RT-AX88U (FW: 3.0.0.4.386_48631) does NOT show such a problem. Could it be related to the AiMesh? The one with the problems in the original issue was using it. This one does not 🤔

Hi, for me not work on FW: 3.0.0.4.386_48631
![Screenshot 2022-05-20 131550](https://user-images.githubusercontent.com/81618680/169507536-e26ba57a-048f-49c4-a8b3-84c0a1b234ef.jpg)

**Comment by Vaskivskyi** [comment]
Hey, @leonidfeldman1977,

Can you please enter the web panel of your device and go to the `Traffic analyzer -> Traffic monitor` (as on the snapshot 1).

Then you would need to open Developer Tools in your browser (F12 on keyboard), there tab `Network` and find one of the requests to `update.cgi` (as on the snapshot 2).

I would need the response for one of such requests. It includes something similar to:

```
netdev = {
 'BRIDGE':{rx:0x466aebec4,tx:0x15af576701}
,'INTERNET':{rx:0x146f3e3ca5,tx:0x43f8c2d43}
,'WIRED':{rx:0x16fa833cd8,tx:0x6f5557c3c}
,'WIRELESS0':{rx:0xf847fae4,tx:0xfe463937}
,'WIRELESS1':{rx:0x2195ed1a7,tx:0xa9227f7b8}
}
```

This could help in solving the problem of the WAN absence from the integration. Thanks!

<details>
<summary>snapshots</summary>

![image](https://user-images.githubusercontent.com/6554415/170856382-135a53f4-f1bd-4d6f-9be5-fe960eb501ff.png)
![image](https://user-images.githubusercontent.com/6554415/170856396-901775a8-2b4a-43cf-93fa-a947d465996b.png)

</details>

**Comment by Vaskivskyi** [comment]
Unfortunately, this issue cannot be solved from the integration point of view. If a device is not reporting some data in the API endpoints, the only way to troubleshoot it will be to get direct access to the device for tests. Other devices of the same models and/or firmware versions are working well.

In case this issue happens to any other user and device, I suggest updating the firmware to the latest version and performing a factory reset (all the settings will be lost in this case).
