### ISSUE TITLE
[Bug]Device is connected in no-control mode. Sending commands is blocked

### ISSUE THREAD

**Issue by Jozziej** [Vaskivskyi/ha-asusrouter#306]
### The problem

Errorlog shows the following error
"Device is connected in no-control mode. Sending commands is blocked"

### Your device model

RT-AC87u

### Firmware type

Merlin

### Firmware version

384.13_10

### Integration version with the issue

0.11.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.10.5

### Is there anything useful in the logs?

```txt
Device is connected in no-control mode. Sending commands is blocked
```

**Comment by Vaskivskyi** [comment]
Hey. This is a normal thing when you have not selected "Enable device control".

Just go to `Configure` for the integration.
![image](https://user-images.githubusercontent.com/6554415/198899656-b3b80bf2-6573-4ecc-8589-ff30b61e578b.png)
![image](https://user-images.githubusercontent.com/6554415/198899665-d4599c0a-bebc-4ff5-9b26-ea1c576de064.png)

So this is not a bug by itself. The question is, how did you get to it? Apparently, you accidently have access to a feature which should be disabled from the integration. And this would be a bug.

**Comment by Jozziej** [comment]
That solved it indeed, but no clue why I got the error now, since I'm running the integration already for a long period of time.
