### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#343]
### The problem

Hi, You make so good work on this integration thank you, i want one change in this integration, make update interval for 1. Device Tracker Done, 2. Sensors, 3. Diagnostics

![image](https://user-images.githubusercontent.com/42905545/202002746-8c2ae431-20ce-43b9-a1cb-0ee96f387815.png)
![image](https://user-images.githubusercontent.com/42905545/202002805-db758e50-6809-48a9-840c-37c7d1ca4bfd.png)

### Specific device(s)?

No

### Firmware type

No

**Comment by Vaskivskyi** [comment]
Hey,

There are already separate update intervals for the following entity groups:
- CPU
- Guest WLAN (all guest WLAN binary sensors or switches)
- Light (LEDs)
- Misc (boot time sensor)
- Network stat (all the network traffic and speeds sensors - WAN, USB, WLAN, WIRED, ...)
- Ports (WAN / LAN speed sensors)
- RAM
- Sysinfo (load average)
- Temperature
- VPN (all the OpenVPN entities - clients and servers)
- WAN (IP sensor and WAN binary sensor)
- WLAN (WiFi 2.4 and 5 GHz binary sensors and switches)

You just need to enable this option in the integration configuration.

<details>
<summary>Snapshots</summary>

<img width="307" alt="image" src="https://user-images.githubusercontent.com/6554415/202033082-b3333c01-4efc-4a2d-9ac5-c5d92b9767f5.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/6554415/202033161-c70dd201-77b7-4bff-bdbe-a0a0174424b7.png">
<img width="304" alt="image" src="https://user-images.githubusercontent.com/6554415/202033224-bfe8756e-cf87-4a75-b6b5-b795e545b601.png">
</details>

As well as there is an interval for device trackers.

The groups are based on the API endpoints from where the data is polled. So almost every group is a single endpoint.

Which other separate update intervals you would like to know?

**Comment by milandzuris** [comment]
Ou sorry THX so much this is i need good work
