### ISSUE TITLE
See connected devices names?

### ISSUE THREAD

**Issue by n00bster-za** [Vaskivskyi/ha-asusrouter#35]
Is there a way to see the name and mac address of the connected devices.

**Comment by Vaskivskyi** [comment]
Hi, @n00bster-za ,

For each connected device an entity `device_tracker.{some_name}` is generated. It has attributes `mac` and `host_name` (for the device name). Of course, `device_tracker` entity has to be enabled to access this data.

You can access them e.g. from templates. For the example from the image below, it would look like this:

```
state_attr('device_tracker.nmcu_black', 'mac')
state_attr('device_tracker.nmcu_black', 'host_name')
```

![device_tracker](https://user-images.githubusercontent.com/6554415/167716332-8079a9db-647a-4dc0-9ece-c3b3f8e3fcca.png)

Is this what you are looking for?

**Comment by Vaskivskyi** [comment]
Hello, @n00bster-za,

Is this what you were looking for? In this case, I will close the issue. If you experience any problems with device trackers `host_name` and `mac` attributes, please reopen this issue. If you have any other problems with the integration - you are welcome to open a new one

Have a nice time! 🙂
