### ISSUE TITLE
[Bug] Platform asusrouter does not generate unique IDs.

### ISSUE THREAD

**Issue by blavak68** [Vaskivskyi/ha-asusrouter#372]
### The problem

When I have two devices connected in the network and integrated into HA, I find the following error in the log:

Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:520
Integration: Sledovanie zariadenia (documentation, issues)
First occurred: 15:57:18 (1 occurrences)
Last logged: 15:57:18

Platform asusrouter does not generate unique IDs. ID 08:3a:f2:aa:3c:5c already exists - ignoring device_tracker.esp32cam_branka

------------------------------------------------------------------------------------
if I have only one router integrated, everything is OK

one AX55 is router
second AX55 is mesh

I think that the problem is that both devices want to create the same device_trucker

### Your device model

RT-AX55 both is the sme models and have the same firmware

### Firmware type

Stock

### Firmware version

3.0.0.4.386_50410

### Integration version with the issue

0.14.2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

core 2022.12.0

**Comment by blavak68** [comment]
in AiMesh mode

**Comment by Vaskivskyi** [comment]
Ok, great, thanks!

I should soon finally get an additional device to implement AiMesh features and this will be part of AiMesh support

**Comment by Vaskivskyi** [comment]
The device trackers unique_id bug will be fixed in 0.17.0
