### ISSUE TITLE
[Bug] Entities allways home

### ISSUE THREAD

**Issue by bernardovalente** [Vaskivskyi/ha-asusrouter#383]
### The problem

Same as bug #221 that I reported which was randomly resolved, the integration had been working almost 100% since then but broke a few HA releases ago and is now showing the same behaviour. Other sensors such as speed sensors, dw/up stats, switches, etc, are working.

### Your device model

RT-AX56_XD4

### Firmware type

Stock

### Firmware version

3.0.0.4.386_49599-g8352df7

### Integration version with the issue

0.14.3

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.12.6

**Comment by Vaskivskyi** [comment]
Hello,

Unfortunately, this problem arises from time to time. I am still searching for the reason.

As soon as I will be able to reproduce the issue, I hope, I will be able to fix it.

I will let you know if some more info is needed from you.

**Comment by dlo747** [comment]
Same issue here 😕

**Comment by Vaskivskyi** [comment]
@dlo747,

Please, provide your router model and firmware version

**Comment by dlo747** [comment]
AXE16000
3.0.0.4.388_21617-g1288c22
Not Merlin

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.17.0 of the integration. Improvement of device trackers has been implemented

**Comment by dlo747** [comment]
> Please, check the new version 0.17.0 of the integration. Improvement of device trackers has been implemented

Working good for me so far. Thank you so much 👏

**Comment by Vaskivskyi** [comment]
For now, I will close the issue, since it is supposedly fixed.

In case the issue will repeat, please reopen this issue or open a new one.
