### ISSUE TITLE
[Bug] Failed parsing value 'isGN'

### ISSUE THREAD

**Issue by zSprawl** [Vaskivskyi/ha-asusrouter#384]
### The problem

I setup the Asusrouter addon for use with my new XT8 wifi mesh. I only set it up on the primary router though since I know you aren't supporting AIMesh yet. I don't think this error is related, but it could be. I've never used this addon before but it seems to be working just fine, except for this error over and over again in the logs.

### Your device model

ZenWiFi AX (XT8)

### Firmware type

Merlin

### Firmware version

386.07_2-gnuton1

### Integration version with the issue

0.14.3

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.12.6

### Is there anything useful in the logs?

```txt
Logger: asusrouter.util.parsers
Source: custom_components/asusrouter/bridge.py:230
Integration: AsusRouter ([documentation](https://asusrouter.vaskivskyi.com/), [issues](https://github.com/Vaskivskyi/ha-asusrouter/issues))
First occurred: 2:31:27 PM (42 occurrences)
Last logged: 2:41:27 PM
Failed parsing value 'isGN'. Please report this issue. Exception summary: ("Wrong value 5 of type <class 'str'>", None)
```

**Comment by zSprawl** [comment]
I rebooted multiple times before opening this ticket, but somewhere between updating my firmware to the latest, installing amtm, and setting up snmp, the error stopped repeating in the logs. I'll repost if it returns, so I guess thanks for reading so far. Addon has been working great!

**Comment by Vaskivskyi** [comment]
Hello,

This is an issue with the parsing of the guest network data by the background library. So it happens only when devices are connected to some guest networks.

The fix is already ready and will be released with the next AsusRouter version.

**Comment by zSprawl** [comment]
Ahh THAT is what GN stood for. I couldn't make a guess.

I did indeed disable the option. Thanks for the reply, fix, and great improvement over the core integration.
