### ISSUE TITLE
[Bug] Unique id is already in use

### ISSUE THREAD

**Issue by danielbanfi47** [Vaskivskyi/ha-asusrouter#450]
### The problem

For me the 0.17.1 can not start: 
ValueError: Unique id 'asusrouter_04:42:1a:79:0d:c0_temperature_cpu' is already in use by 'sensor.tuf_ax5400_temperature_cpu'

### Your device model

TUF-AX5400

### Firmware type

Stock

### Firmware version

3.0.0.4.388_21224-g702a50f

### Integration version with the issue

0.17.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.2

### Is there anything useful in the logs?

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 24, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 680, in setup
    entity_reg.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 749, in async_update_entity
    return self._async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 695, in _async_update_entity
    raise ValueError(
ValueError: Unique id 'asusrouter_04:42:1a:79:0d:c0_temperature_cpu' is already in use by 'sensor.tuf_ax5400_temperature_cpu'
```

**Comment by Vaskivskyi** [comment]
Hello. Unfortunately, it seems like your configuration did not manage to migrate between the integration versions. The easiest way would be to remove and setup again this device.

Sorry for this. It was working well on both the testing environments I have and most of users do not experience any problems. But it was already once reported in #443

Sorry once more

**Comment by Vaskivskyi** [comment]
Please, let me know, whether you went with the suggested step and if afterwords integration works fine

**Comment by danielbanfi47** [comment]
Hi,

thank you for the suggestion. With the reinstall it works fine.

**Comment by Vaskivskyi** [comment]
Great! Thanks!
