### ISSUE TITLE
[Bug] RT-AC87U in Media Bridge mode with v0.17.1 -  object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by mihsu81** [Vaskivskyi/ha-asusrouter#451]
### The problem

RT-AC87U in Media Bridge mode throws an error when loading after updating from v0.16.1 to v0.17.1

```TypeError: object of type 'NoneType' has no len()```

### Your device model

RT-AC87U

### Firmware type

Merlin

### Firmware version

3.0.0.4.384.13_10

### Integration version with the issue

0.17.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.2

### Is there anything useful in the logs?

```txt
Logger: homeassistant.config_entries
Source: helpers/device_registry.py:129
First occurred: 09:51:06 (1 occurrences)
Last logged: 09:51:06

Error setting up entry 192.168.45.240 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 24, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 665, in setup
    entry.entity_id, new_unique_id=f"{self.mac}_{uid}"
  File "/config/custom_components/asusrouter/router.py", line 1097, in mac
    return format_mac(self._identity.mac)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 129, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
TypeError: object of type 'NoneType' has no len()
```

**Comment by raffaelevall** [comment]
I have the same problem with RT-AC87U:
`
Logger: homeassistant.config_entries
Source: helpers/device_registry.py:129
First occurred: 12:48:43 (5 occurrences)
Last logged: 15:19:40

Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 24, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 676, in setup
    new_uid = uid.replace(self._conf_name, self.mac)
  File "/config/custom_components/asusrouter/router.py", line 1097, in mac
    return format_mac(self._identity.mac)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 129, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
TypeError: object of type 'NoneType' has no len()
`

Tks

**Comment by Vaskivskyi** [comment]
@raffaelevall, is your device in router mode or in any other of modes (AP / AiMesh node / etc)?

**Comment by raffaelevall** [comment]
> @raffaelevall, is your device in router mode or in any other of modes (AP / AiMesh node / etc)?

Router mode ;-)

**Comment by ejpenney** [comment]
Getting the same error with 0.17.0 and 0.17.1.  This is with RT-AC66U (Merlin, 3.0.0.4.380.70_0) in AP mode.  Tried running your script:

```
$ python script.py
MAC address: `None`
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001CC3E0391F0>
```

**Comment by mihsu81** [comment]
Running the script with Python 3.10.9 returns:

```
/root/script.py:27: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
MAC address: `None`
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8e1aaec520>
```

**Comment by Vaskivskyi** [comment]
Interesting. Your devices do not have `label_mac` saved in the NVRAM. Merlin feature?

Try this code:

```python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
from asusrouter.util import compilers
import asyncio


async def gather_data(host, username, password, use_ssl):
    """Method to gather all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, use_ssl = use_ssl)

    try:
        # Connect and identify
        await router.connection.async_connect()

        # Get raw NVRAM data
        hook = compilers.nvram(["lan_hwaddr", "wan_hwaddr", "label_mac"])
        data = await router.async_hook(hook)
        print(data)

        # Disconnect
        await router.connection.async_disconnect()
    except Exception as ex:
        raise ex


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_use_ssl = True

loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))

loop.close()
```

The output will be similar to:

```
{
    "lan_hwaddr": "AA:BB:11:CC:22:00",
    "wan_hwaddr": "AA:BB:11:CC:22:00",
    "label_mac": None
}
```

Are the `lan_hwaddr` or `wan_hwaddr` your device actual MACs? We need to find a fallback option for your case

**Comment by mihsu81** [comment]
The values are:

lan_hwaddr=38:2C:4A:AA:5F:60
wan_hwaddr=38:2C:4A:AA:5F:60
label_mac

38:2C:4A:AA:5F:60 is ndeed the MAC of the device.

**Comment by ejpenney** [comment]
I get both:

```
{
  'lan_hwaddr': 'D8:50:E6:A9:41:E0',
  'wan_hwaddr': 'D8:50:E6:A9:41:E0',
  'label_mac': ''
}
```

**Comment by Vaskivskyi** [comment]
Great. Preparing the fix

**Comment by raffaelevall** [comment]
> Grande. Preparazione della correzione

sorry but i didn't have time. I hope other people's contributions helped, thanks

**Comment by Vaskivskyi** [comment]
@mihsu81, @ejpenney,

Please install the new version of the `asusrouter` library using `pip install --upgrade asusrouter==0.17.0` and then try again the first code from https://github.com/Vaskivskyi/ha-asusrouter/issues/451#issuecomment-1376054682

If you cannot install the library immediately, you might need to wait a minute and try again - the release was just published, so may take a moment to become available for everyone.

Hopefully, it will return you 

```
MAC address: `AA:BB:11:CC:22:00`
```

**Comment by ejpenney** [comment]
Looks good to me:

```
$ python script.py
MAC address: `D8:50:E6:A9:41:E0`
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002299986B430>
```

**Comment by mihsu81** [comment]
Working fine for me as well.
MAC address: `38:2C:4A:AA:5F:60`

Thank you 😊.

**Comment by Vaskivskyi** [comment]
Please, try the newly released integration version 0.17.3 (https://github.com/Vaskivskyi/ha-asusrouter/releases/tag/0.17.3)

If HACS does not show it yet, just reload HACS - it will show the update.

**Comment by ejpenney** [comment]
Loaded successfully, though I am seeing this in the log:

```
This error originated from a custom integration.

Logger: custom_components.asusrouter.router
Source: custom_components/asusrouter/router.py:760
Integration: AsusRouter (documentation, issues)
First occurred: 2:15:14 PM (17 occurrences)
Last logged: 2:23:16 PM

Error connecting to '192.168.86.34' for device update: None
```

I can't say if this is new or not, so I'm not sure if it's related to this, or another issue.

**Comment by ejpenney** [comment]
This message is piling up in my log, connected devices count says 0.  I think something else is not right on my setup.

**Comment by Vaskivskyi** [comment]
@ejpenney,

Please, try the 0.17.4 update

**Comment by ejpenney** [comment]
The errors are gone but I'm still seeing zero connected devices. I feel like sometimes that list takes a while to populate, right?

**Comment by ejpenney** [comment]
The errors are gone but I'm still seeing zero connected devices. I feel like sometimes that list takes a while to populate, right?

**Comment by Vaskivskyi** [comment]
@ejpenney,

please, open a new issue with the following info:
- Do device tracker entities work? Or are they unavailable
- By 0 connected devices you mean `sensor.{device}_connected_devices` value? What does `sensor.{device}_latest_connected` state?
- Do other sensors work?

**Comment by mihsu81** [comment]
Works for me as well. Updated to 0.17.4.
Thanks again @Vaskivskyi
