### ISSUE TITLE
[Bug] Devices Connected entity/sensor not showing up after setting up integration

### ISSUE THREAD

**Issue by Kickbut101** [Vaskivskyi/ha-asusrouter#455]
### The problem

XT8 (RT-AX95Q) device. Setup as "AI-Mesh" mode, not router mode

I was having some issues with entities not being deletable or editable so I figured I'd just nuke the integration and reinstall it.

Upon reinstallation however I cannot figure out why I can't get the "Connected Devices" information to show back up. I've re-setup the router 2-3 times now by deleting integration and re-configuring but each time I am missing anything to do with how many devices are connected.

### Your device model

RT-AX95Q

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.7_2-gnuton1

### Integration version with the issue

0.17.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

 Home Assistant 2023.1.0 Supervisor 2022.12.1 Operating System 9.4 Frontend 20230104.0 - latest

**Comment by Vaskivskyi** [comment]
Hello, @Kickbut101,

Only the `router` mode reports connected devices info. The AiMesh node is missing this data as not reliable.

[As per release notes](https://community.home-assistant.io/t/custom-component-asusrouter-integration/416111/363?u=vaskivskyi):
- Devices in `Router` mode support all the features of AsusRouter (including devices monitoring)
- Devices in `AiMesh node` mode support the following feature groups: Main, CPU, LED, Load average, Network, Ports, RAM, Temperature. Other features are disabled as unreliable / duplicating

This is defined by the way data is shared across the AiMesh nodes - only the main router knows all the connected devices, which nodes they are connected to and what type of connection is established. Nodes can report properly only about devices connected directly but do not explicitly specify them - so creating a mess of devices.

Please, use your main AiMesh router in the `router` mode - it will show all the needed data.

**Comment by Kickbut101** [comment]
Ah, I was perusing this - https://asusrouter.vaskivskyi.com/features/connected-devices.html
and this - https://github.com/Vaskivskyi/ha-asusrouter

On both I saw device connected and wasn't aware it was a router only thing.

I can understand why that is, but I missed the release note mention of it.

Can I in my case "switch" the mode? My actual home network does have the nodes set in AP mode. Will it work just the same if I configure this in "Router" mode?
