### ISSUE TITLE
[Feature] Multiple WAN IP

### ISSUE THREAD

**Issue by merlin-zaraza** [Vaskivskyi/ha-asusrouter#464]
### The problem

I have Asus RT-AC86U connected by PPPoE. Somehow it shows me two WAN IPs: seems like one is internal and another one is external. Integration returns only one IP address. Could you please add all that router assigns?

<img width="301" alt="Screenshot 2023-01-10 at 11 24 38" src="https://user-images.githubusercontent.com/5223485/211513853-8ceb9fbc-7de2-4e11-9d32-f57bd26bf516.png">

### Specific device(s)?

None

### Firmware type

None

**Comment by merlin-zaraza** [comment]
That was quick reply. Thanks!

**Comment by Vaskivskyi** [comment]
Hello, this feature will be added in the next release.

Binary sensor `wan` and sensor `wan_ip` will get additional attributes related to the secondary WAN connection:
- `xdns`
- `xgateway`
- `xip`
- `xip_type`
- `xmask`

providing DNS, gateway, IP, IP type and mask info for the local connection.

**Comment by Vaskivskyi** [comment]
Since the feature is already released, I will close the issue
