### ISSUE TITLE
[Bug] Router Connected Devices sensor - IP of devices connected to Mesh nodes appear as null

### ISSUE THREAD

**Issue by mihsu81** [Vaskivskyi/ha-asusrouter#466]
### The problem

In the sensor Connected Devices of a router the IP of devices connected to Mesh nodes appear as **_null_**.

![image](https://user-images.githubusercontent.com/40715497/212189596-7d1d1906-62f3-4db2-b941-0e385a8505c2.png)

### Your device model

RT-AX88U

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.1

### Integration version with the issue

0.17.4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.2

**Comment by Vaskivskyi** [comment]
Hello. Does it happen to many devices or only to some? Does it happen to the end devices or only to AiMesh nodes, which are also shown as connected devices?

**Comment by mihsu81** [comment]
It happens to all end devices not connected to the router, but connected to one of the AiMesh nodes.
The MAP-AC1300 AiMesh nodes don't appear in the list of connected devices of the router.
The RT-AC87U media bridge does appear in the list of connected devices and has an IP listed.

**Comment by mihsu81** [comment]
I've rebooted the router and AiMesh nodes today and noticed that only 12 devices appear without IP now.
All 12 connected are connected to AiMesh nodes, not to the router.
The device_tracker entities created for these 12 devices don't have an IP attribute. And the Connection time, Rx speed and Tx speed attributes are missing a value.
Anything to check on the router that would help clarify the cause?
![image](https://user-images.githubusercontent.com/40715497/212401647-e1f18c8f-a3d4-48b2-ad92-c9b77d1e55e0.png)
![image](https://user-images.githubusercontent.com/40715497/212401917-8e10f626-2e52-48c9-9b3c-3ba87eab70ec.png)

**Comment by Vaskivskyi** [comment]
Please, check whether the issue persists with the new version 0.18.0

**Comment by mihsu81** [comment]
The issue is still there in 0.18.0.
I've noticed 2 more related issues in 0.18.0:

1. Now I can see the AiMesh nodes as connected devices and for them **_node_** is **_null_**.
2. Devices wired to a media bridge (RT-AC87U) have **_connection_type: unknown_** and **_node: null_** 


![image](https://user-images.githubusercontent.com/40715497/213885343-fc76a6f3-bf1a-4a42-9db2-e1fcfd9fde1f.png)

![image](https://user-images.githubusercontent.com/40715497/213885492-074e75e2-551e-448f-bc57-b9b1736ae4f1.png)

**Comment by Vaskivskyi** [comment]
You can try checking the `0.23.0b1` beta release. Unfortunately, device tracking with an Asus router is quite a headache and I am still not sure how to make everything work well
