### ISSUE TITLE
[Bug] Firmware version cannot be parser. Please report this. The original FW string is: 9.0.0.4.386.41615-g7c2264e

### ISSUE THREAD

**Issue by mihsu81** [Vaskivskyi/ha-asusrouter#467]
### The problem

Getting the below 2 warnings in HA.
The first one is caused by x4 Asus Lyra Mini MAP-AC1300 running beta firmware 9.0.0.4.386.41615-g7c2264e.
```
This error originated from a custom integration.

Logger: asusrouter.util.parsers
Source: custom_components/asusrouter/bridge.py:149
Integration: AsusRouter (documentation, issues)
First occurred: 23:58:23 (4 occurrences)
Last logged: 23:58:24

Firmware version cannot be parser. Please report this. The original FW string is: 9.0.0.4.386.41615-g7c2264e
```
This one is caused maybe by the router and media bridge (based on the number of occurrences)?
```
This error originated from a custom integration.

Logger: asusrouter.util.parsers
Source: custom_components/asusrouter/bridge.py:246
Integration: AsusRouter (documentation, issues)
First occurred: January 12, 2023 at 23:58:27 (2 occurrences)
Last logged: January 12, 2023 at 23:58:28

Firmware version cannot be parser. Please report this. The original FW string is:
```

### Your device model

MAP-AC1300

### Firmware type

Stock

### Firmware version

9.0.0.4.386.41615-g7c2264e

### Integration version with the issue

0.17.4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.2

### Diagnostics information

[config_entry-asusrouter-e568a898ee4e147629d92dbdf233790d.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10406413/config_entry-asusrouter-e568a898ee4e147629d92dbdf233790d.json.txt)
[config_entry-asusrouter-edcade55ce9bad2892da0ef98b3f4970.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10406414/config_entry-asusrouter-edcade55ce9bad2892da0ef98b3f4970.json.txt)
[config_entry-asusrouter-eea7c56fddb0fb9fba8c722811ae8749.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10406415/config_entry-asusrouter-eea7c56fddb0fb9fba8c722811ae8749.json.txt)
[config_entry-asusrouter-424ed09a3f7616fd40ad3a60a6bdab05.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10406416/config_entry-asusrouter-424ed09a3f7616fd40ad3a60a6bdab05.json.txt)
[config_entry-asusrouter-abc26babac5f76cbcf9c7deb0f2508e3.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10406417/config_entry-asusrouter-abc26babac5f76cbcf9c7deb0f2508e3.json.txt)
[config_entry-asusrouter-e5c3ec43c5f57e04ed6b2099f38d4538.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10406418/config_entry-asusrouter-e5c3ec43c5f57e04ed6b2099f38d4538.json.txt)

**Comment by sezlony** [comment]
+1

same bug here on RT-AC1200G+

stock 3.0.0.4.382.52272 fw

**Comment by Vaskivskyi** [comment]
Hello,

I will look into the issue and let you know whether some more details are needed from your side

**Comment by mihsu81** [comment]
On the MAP-AC1300 the update sensor sees it as 3.0.0.4.None.None_None.

![image](https://user-images.githubusercontent.com/40715497/212258441-6a030b10-514d-4c03-987e-f4c22889ca75.png)

**Comment by Vaskivskyi** [comment]
The initial issue will be fixed in the next release (with the beta version `9.0.0.4.386.41615-g7c2264e`)

@sezlony, @mihsu81, please, provide full version strings for the other cases when the integration cannot process FW version properly. The full FW version you can find in the device Web UI (in the case of using AiMesh, the main router shows FW versions for all the nodes)

**Comment by sezlony** [comment]
do you mean this version string? **`3.0.0.4.382_52272-g73d3ea2`**

**Comment by Vaskivskyi** [comment]
Strange. This string should be completely fine. Do you see log errors or does the `update` entity shows something wrong? I would need a bit more info on your issue

**Comment by mihsu81** [comment]
The versions are:

RT-AX88U
3.0.0.4.388.1
RT-AC87U
3.0.0.4.384.13_10
MAP-AC1300
9.0.0.4.386_41615-g7c2264e

Could it be caused the **_** after 386? I see that the other firmware have a **.** after 388 and 384 respectively.

**Comment by Vaskivskyi** [comment]
@mihsu81, thanks! All of these FW versions should work fine in the next AsusRouter release

**Comment by mihsu81** [comment]
With v0.18.0 Installed version is fine, but Latest version appears as 3.0.0.4.None.None_None.

![Screenshot_2023-01-21-18-44-23-43_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/40715497/213877447-b278ab02-a2e8-43a0-8dfc-4664b5edb586.jpg)

**Comment by sezlony** [comment]
Thank you! 👍 🥇

monitoring of connected devices is now working, i don't care about version numbers... 😄

![kép](https://user-images.githubusercontent.com/101760883/213884567-b3b08e97-5e75-4aa2-99c2-8b4887339e75.png)

**Comment by Vaskivskyi** [comment]
Can you please both check what this API endpoint shows you when opening from a web browser?

`https://192.168.1.1/detect_firmware.asp`

Just login to your device Web UI and change the last part of the URL with `detect_firmware.asp`

Should be something similar to this

```
webs_state_update = '1';
webs_state_error = '0';
webs_state_info = '388_1_0';
webs_state_info_beta = '';
webs_state_REQinfo = '';
webs_state_flag = '0';
webs_state_upgrade = '';
webs_state_level = '0';
sig_state_flag = '0';
sig_state_update = '1';
sig_state_upgrade = '1';
sig_state_error = '0';
sig_ver = '2.330';
if(cfg_sync_support){
cfg_check = '9';
cfg_upgrade = '';
}
if(pipefw_support || urlfw_support){
hndwr_status = '99';
}
if(rbkfw_support){
_rollback_info = JSON.parse('');
rbk_count = Object.keys(_rollback_info).length;
}
```

**Comment by sezlony** [comment]
kinda similar
```
webs_state_update = '1';
webs_state_error = '1';
webs_state_info = '';
webs_state_info_beta = '';
webs_state_REQinfo = '__';
webs_state_flag = '0';
webs_state_upgrade = '';
sig_state_flag = '';
sig_state_update = '';
sig_state_upgrade = '';
sig_state_error = '';
sig_ver = '';
if(cfg_sync_support){ cfg_check = ''; cfg_upgrade = ''; } 
```

**Comment by mihsu81** [comment]
```
webs_state_update = '1';
webs_state_error = '0';
webs_state_info = '388_1_0';
webs_state_info_beta = '';
webs_state_REQinfo = '';
webs_state_flag = '0';
webs_state_upgrade = '';
webs_state_level = '0';
sig_state_flag = '0';
sig_state_update = '1';
sig_state_upgrade = '1';
sig_state_error = '0';
sig_ver = '2.330';
if(cfg_sync_support){ cfg_check = '9'; cfg_upgrade = ''; } if(pipefw_support || urlfw_support){ hndwr_status = '99'; } if(rbkfw_support){ _rollback_info = JSON.parse(''); rbk_count = Object.keys(_rollback_info).length; }
```

**Comment by Vaskivskyi** [comment]
@sezlony, your case will be fixed in 0.18.1

@mihsu81, both of those should already work well with the integration as it was. Do they show `None` in the `update` entity? Your latest screenshot is for the device with a 9.0.0.4 build (so Lyra Mini apparently) which does not show the latest available version. Can you please check data from the `detect_firmware.asp` for them if this is possible?

**Comment by Vaskivskyi** [comment]
Please, check 0.18.1

**Comment by mihsu81** [comment]
@Vaskivskyi v0.18.1 fixed the issue. Thanks a lot. 👍🏼 

![image](https://user-images.githubusercontent.com/40715497/213988789-a97c16d9-6060-43fc-8146-1bb92ac69cd9.png)
