### ISSUE TITLE
[Bug] VPN client status works but control doesnt

### ISSUE THREAD

**Issue by max246** [Vaskivskyi/ha-asusrouter#470]
### The problem

Using Asus  RT-AX58U with stock 3.0.0.4.388_22237-g9120e16 cant seems to trigger on and off VPN client

Will it be possible to support this functionality ?

### Your device model

RT-AX58U

### Firmware type

Stock

### Firmware version

3.0.0.4.388_22237-g9120e16

### Integration version with the issue

0.17.4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023

**Comment by Vaskivskyi** [comment]
Hello,

Unfortunately, VPN features are not yet supported on the new Stock 388 builds. Asus has rebuilt all the VPN parts of the firmware.

I am working on getting it back to work. Hopefully, it will be ready soon.

P.S. On Merlin 388 builds everything works, it is just a Stock limitation.

**Comment by max246** [comment]
Thank you for the information

**Comment by Vaskivskyi** [comment]
#685 is bringing support for OpenVPN Clients through VPN Fusion (stock 388 FW). It will be available with the release of integration `0.24.0+` (soon)

**Comment by Vaskivskyi** [comment]
Hello, please check the new beta release `0.24.0b0` for the new functionality. The stable version will be released later this week.
