### ISSUE TITLE
Can't install without SSL 

### ISSUE THREAD

**Issue by boheme61** [Vaskivskyi/ha-asusrouter#472]
### The problem

I just experienced same "error" as other have reasently, Can't re-install AsusRouter ... did you somehow force people to use SSL ?

It started with after an upgrade i suddenly found 2 "Router-Devices" 1 with all the entities and 1 without entities ( obviously i just disabled the 1 without entities) ... then i discovered that some of the entities was disabled(by device/integration), i couldn't enable them. ( seemed like only trackers worked , binary,wan, wan-IP, connected devices etc, didn't work)
So i decided to uninstall and delete ALL entities, remote etc.
Now i end up with above ! ... also i have RT AX86U ... i don't know whether it's caused by the fact that it now seems to be "Required" to use SSL ? ( also Why is this suddenly Recommended/required ? ) ... as my installation is supposed to be entirely Local, i don't find any reason to setup SSL, so as i haven't i can't confirm if that's the root-cause here

EDIT: 1 thing i did noticed, before i removed everything was that, The 1 Device (router) which now had all the entities was "marked" as an Aimesh-node ( which im sure i never have chosen initially" ) and the other Device(router), which i believe was the initial i had(before some asusrouter--version update) it had a "random. number after device-name

Unknown error of type '<class 'homeassistant.exceptions.ConfigEntryNotReady'>' during connection to 192.168.50.119: ("Cannot connect to host 192.168.50.119:80 ssl:False [Connect call failed ('192.168.50.119', 80)]", None)

### Your device model

RT-AX68U

### Firmware type

Stock

### Firmware version

3.0.0.4.388_21732-g0837a3a

### Integration version with the issue

latest , as i can't install again, after removing it

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

homeassistant-os VMware latest latest

**Comment by Vaskivskyi** [comment]
Hello,

No changes were made to the SSL / non-SSL settings in the recent releases. SSL is not forced and only the user-selected settings are used.

The only reason it is recommended in the documentation is that router FW can handle many more simultaneous connections over HTTPS rather than over HTTP - this is just an Asus feature.

Could you please follow the steps:

1. Remove any set-up (if any) AsusRouter integration if your HA
2. Reinstall AsusRouter from HACS
3. Try to set up the integration using your preferred settings
--- if 3 fails ---
5. Reboot your router
6. Try setting up AsusRouter again without SSL

let me know, which step of the above you can get to

The error from your log just says that integration cannot be connected to the device. It can be both integration and device-related

**Comment by boheme61** [comment]
yep, i removed every trace, rebooted again, and reinstalled again ... this time everything went smooth !!! :) ... i have no idea of when and where it went wrong. most likely some "trace" of the(a) previous installation.
Thx for your patience

While im here, i have thoughts about the "entities" which gets installed: 
Are all of the entities, entities that my specific router should support ? , as i found a bunch of switches this time "previously" i didn't enabled this feature during installation
But does this look feasible ? 2x3 guest network and 5 vpn clients ... i never thought this model had support for 5 vpn clients

Thx again for a great work

**Comment by Vaskivskyi** [comment]
Actually, all the Asus routers support up to 3 guest networks on each wireless interface and 5 OpenVPN clients + 2 OpenVPN servers.

Unfortunately, OpenVPN does not work well yet on the new 388 stock builds. Actually, I should hide those entities depending on the FW version before everything is working correctly for the newer FW

**Comment by boheme61** [comment]
OK, Thanx for the info :)
I usually goes through all integrations initially to enable/disable what i want/need, and in this case i don't use OpenVPN, nor guest-network(since awhile ago ... (no guests allowed to disturb my network :)
Maybe it's better if you just disable such entities, and then maybe on your documentation-site ( or in the ha-forum-site) write that you don't currently recommend using OpenVPN ), and then list which entities you decide to disable as default or maybe you already have and i missed that also :) ...  anyway i just saw yesterday the Howto/Automation section, cool
