### ISSUE TITLE
[Bug] Device tracking not working properly

### ISSUE THREAD

**Issue by 5a5cha** [Vaskivskyi/ha-asusrouter#485]
### The problem

Device tracking seems to be broken.

I have many home/not home tracking information in the history of my Access-Point.
Device is working as expected and a continuous ping from my Laptop to the AP shows no lost connection.
Tested on WIFI and wired. Connected to the AP direct and Router.

AP is one of many devices with this strange behaviour.
Screenshots AsusRouter vs AsusWRT below.

AsusRouter
![image](https://user-images.githubusercontent.com/21234719/213876250-8c4049c2-e4e6-4241-b3f4-b709270a65f3.png)

AsusWRT
![image](https://user-images.githubusercontent.com/21234719/213876261-83c51795-9738-40a1-9908-0182e1db7876.png)

### Your device model

GT-AX11000

### Firmware type

Merlin

### Firmware version

388.1

### Integration version with the issue

0.17.4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.6

### Additional information

Got two GT-AX11000 devices in my house.
One is configured in Router-Mode and one in AP-Mode (No AI-Mesh config).
Connected via 2.5G Cable.

**Comment by Vaskivskyi** [comment]
Hello. Please check with the new version 0.18.0 whether the issue persists

**Comment by 5a5cha** [comment]
Good morning.
installed 0.18.0 last night and looking good so far.
![image](https://user-images.githubusercontent.com/21234719/213906984-7da1e190-58c6-4ec1-bfc0-f9cc3882e3b3.png)


Set a reminder and report next week again.

**Comment by Vaskivskyi** [comment]
Good. Just keep in mind, that if you want to compare with AsusWRT, make sure that the `consider device at home` time interval is set to the same value in both.

A shorter `consider home` would mean it detects devices offline faster, but might have more short disconnects/reconnects

**Comment by 5a5cha** [comment]
Why should it detect reconnects on a cable connection?
> A shorter consider home would mean it detects devices offline faster, but might have more short disconnects/reconnects

Sadly it looks like the bugfix didn't work 100%.
After Update to 0.18.1 i deleted the integrations for both and did a complete new config. One Router and one Access-Point.
In the Screenshot you can see random disconnects.
![image](https://user-images.githubusercontent.com/21234719/214241542-9fb85f67-94cf-4a00-a97b-431c7a80422f.png)

**Comment by 5a5cha** [comment]
Ok, after playing around and digging a little deeper it seems the problem could be the combination of router and ap.
Since router and ap have own client-name lists the integration will generate two different entities.
Don't know if this is the reason or router and ap playint tricks on each other.

Will check a AIMesh-Router and AIMesh-Node config.

**Comment by Vaskivskyi** [comment]
A question regarding your router-AP config: so you have AP with the same network names to increase the radius of your WiFi network for end devices? Or is it AP with separate WiFi?

In the first case, AiMesh will really be the better option - in this mode, all the devices communicate correctly and the one responsible for monitoring all the connected devices - is the AiMesh router. So you will have 2 times less entities and all of them should work better

Regarding device_tracker disconnects on wired connection - does it happen to end devices or only to AP connected via wire to the main router?

**Comment by 5a5cha** [comment]
Hi @Vaskivskyi, your right.

Config is to increase the WIFI.
Yesterday i changed the config to AIMesh-Router and AIMesh-Node. Looks good for the number of devices.

But the issue seems not to be solved at all.
I have a raspberry pi for testing and after a shutdown and disconnect from power the device is still listed as online.
Strange to me, it is also listed in the GUI. But i really don't know if the GUI shows the online devices or the ever seen devices.

**Comment by Vaskivskyi** [comment]
Then this would be the main problem. The Web UI should be showing only online devices. And the source is exactly the same as the source for the integration data. The question is only, why RPi stays online for the router.

I will be able to check with RPi connected via wire in the evening (CET) and will let you know, whether it works for me with a similar config.

**Comment by 5a5cha** [comment]
Ok, i will install the AsusWRT integration this evening and check if this has the same behave.

**Comment by 5a5cha** [comment]
Tested AsusWRT with the pi.

In AsusWRT the pi is tracked as expected.
Comes online and after shutdown goes offline.

In AsusRouter the pi is online all the time.
Checked log regarding the other issue with CPU usage and there are errors in the log. Will post the result at the other bug.

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the delay. I can confirm the bug with the same 388.1 FW and RPi 3B connected in wired mode. At the same time, wireless connection / disconnection works fine

But this is not an integration issue, but rather a router - the wired connected RPi stays `online` in the Web UI and AsusRouter cannot receive any other information than Web UI shows

Comparison with AsusWRT HA integration is not particularly correct. AsusWRT runs commands directly on the router OS. AsusRouter communicates with the Asus API - this allows abstracting from the exact device peculiarities and being compatible with all the possible Asus routers

Currently, I cannot check whether this behaviour is only on 388.1 or is it a general problem

**Comment by 5a5cha** [comment]
No problem for being late :-)

Well, maybe the FW on the Router has two different ways to detect online devices.
On for the "normal" router config and one for the AiMesh-Router config.

In Mesh-Router config:
As far as i can see, there is a difference between the online devices when clicking on "Liste anzeigen" (first screenshot) and "Kabelverbindungen" (second screenshot) in the AiMesh part of the GUI.
![image](https://user-images.githubusercontent.com/21234719/215291391-d4509682-7f21-4271-aad9-cba6b8481c35.png)
![image](https://user-images.githubusercontent.com/21234719/215291445-a1cea15a-a7d8-4bb5-826b-5f0028ba5768.png)

Yes, the second screenshot really shows three online devices via cable, which is correct.

**Comment by Vaskivskyi** [comment]
I will check the other connected devices menu, if it can improve device tracking

**Comment by Vaskivskyi** [comment]
Let's continue this discussion in issue #570. The problem with device trackers is happening for different users and it will be much easier to collect all the useful info in a single issue.
