### ISSUE TITLE
[Bug] Tracked devices only update from Offline to Online (NotHome to Home), but not viceversa

### ISSUE THREAD

**Issue by rkkoszewski** [Vaskivskyi/ha-asusrouter#49]
Seems like the tracked devices only update from Offline to Online (NotHome to Home) but not viceversa and shows as Online (Home) even when the device is disconnected. The only way to fix it is to restart Home Assistant. Then it shows the device as Offline, but once it changes back to Online, it's stuck at Online forever.

**Comment by Vaskivskyi** [comment]
Hey, @rkkoszewski,

Thanks for your bug report! :+1:

I will look into this problem as soon as I get a bit of free time (most probably till the end of the week)

**Comment by Vaskivskyi** [comment]
I am sorry for the delay with this fix. There is a large release in work and it requires a bit more time. But, of course, it will include a fix for this bug as well as many new features

**Comment by Vaskivskyi** [comment]
Hey, @rkkoszewski,

Mind checking the new 0.3.0 version? Now device tracking should be fixed. Moreover, now you can control `consider home` time for the devices.

If you are experiencing any other issues with the integration, please, open a new issue, so it will be easier to track.

**Comment by rkkoszewski** [comment]
Awesome!! It works perfectly now! Thanks!
Closing bug.
