### ISSUE TITLE
[Feature] Add Media Bridge mode

### ISSUE THREAD

**Issue by mihsu81** [Vaskivskyi/ha-asusrouter#494]
### The problem

Add support for Media Bridge mode where it links wired devices to the router over WiFi.
It should only create device trackers for wired devices. 
At the moment I'm using a media bridge integrated as an AP and it creates duplicate device trackers for the wireless devices already connected to the router.
Thanks in advance.

### Specific device(s)?

No

### Firmware type

No

**Comment by Vaskivskyi** [comment]
Hello. So in general, the integration in Media Bridge mode should do everything the same (create all the same sensors), but create only wired connection device_trackers and not create wireless?

**Comment by mihsu81** [comment]
Yes, the same sensors and wired device_trackers.
In fact at the moment the integration doesn't create device_trackers for wired devices.

**Comment by Vaskivskyi** [comment]
Hey. The feature is available in the new 0.19.0 version

**Comment by mihsu81** [comment]
Thank you for the new feature.

**Comment by mihsu81** [comment]
It looks like there aren't any device_trackers created for the wired devices into the media bridge.
![image](https://user-images.githubusercontent.com/40715497/217581387-a81b4ee0-34ac-4c70-9636-9d9f24e289d6.png)

The device trackers are created under the Router integration but they either appear disconnected (Tuya Gateway) or connected with incomplete info (HOS02). By comparison, devices wired into an AiMesh (Tahoma) get all the details correctly.

![image](https://user-images.githubusercontent.com/40715497/217589131-501cee93-5cbe-43da-a0ef-535c1c0e1613.png)

![image](https://user-images.githubusercontent.com/40715497/217589223-30c87f1d-7a21-47f3-b1a1-0224a1de97a6.png)

![image](https://user-images.githubusercontent.com/40715497/217589300-de32ae33-22d6-4285-99fd-ae8b1243b852.png)

**Comment by Vaskivskyi** [comment]
Do your devices show up in the router Web UI and wired and not show in the integration when set up in the Media Bridge mode?

**Comment by mihsu81** [comment]
I've noticed 2 different situations with the 2 devices connected over ethernet to the media bridge. 

Devices connected to the media bridge with the IP 192.168.45.240.
![image](https://user-images.githubusercontent.com/40715497/221442463-9b8ca326-0826-4cc0-ab9e-52fd41703f7a.png)

Case 1.
HAOS02 with IP 192.168.45.202 and MAC 7C:C2:C6:33:34:34.

The media bridge seen on the router with the IP of HAOS02, but with its own MAC.
![image](https://user-images.githubusercontent.com/40715497/221442544-a3709e25-c86f-40ae-9115-a2e51aae192d.png)

HAOS02 seen with the inversed MAC addresses. 
![image](https://user-images.githubusercontent.com/40715497/221442585-9d5fa0e7-7169-4c77-b192-a44ee06918b5.png)

The correct MAC addresses of HAOS02.
![image](https://user-images.githubusercontent.com/40715497/221442671-4ce43be1-761d-4cbf-8c9e-08418f32b394.png)

This issue seems to be caused by the fact that the media bridge also shows some of the devices connected to the router and this seems to mess the device details.

In HA it appears unavailable and without any details and under the integration of the router, not the media bridge.

![image](https://user-images.githubusercontent.com/40715497/221443945-2f9dcf9e-216f-41cf-93a5-d429e9f9699c.png)


Case 2. 
BETHAYN-ASUS with IP 192.168.45.135 and MAC 50:46:5D:E4:55:60.

The device is shown with the correct details and only appears on the media bridge, not the router.
![image](https://user-images.githubusercontent.com/40715497/221443709-a8ea5899-0e9a-4ef8-ab6a-9c7cee0f0bd0.png)

![image](https://user-images.githubusercontent.com/40715497/221443779-36cb67a8-8a9e-4684-95b7-b359a8b63ead.png)

In HA it appears Home but is missing some of the details. Also it appears under the integration of the router, not of the media bridge.
![image](https://user-images.githubusercontent.com/40715497/221444099-29b5006f-0366-47f4-93b5-03f802a00fef.png)

**Comment by Vaskivskyi** [comment]
The problem you have is actually really strange. I have again tested the media bridge mode and for me everything works as expected on the integration side - it only tracks all the devices connected via a wired connection (as shown in the router Web UI).

I would kindly ask you to create a new issue (bug report). Just because I might lose the discussion since it is in a `feature request` issue which is already closed
