### ISSUE TITLE
[Bug] Aimesh wrong node status

### ISSUE THREAD

**Issue by Salvora** [Vaskivskyi/ha-asusrouter#503]
### The problem

I noticed that one of my nodes was reporting connection type as wireless backhaul. I have checked the said node but it should be ethernet backhaul. Please, see below.

![image](https://user-images.githubusercontent.com/6360098/215882050-24827050-5daf-4e65-bfac-ce652522ec74.png)
![image](https://user-images.githubusercontent.com/6360098/215882146-219fad8b-7c3d-43de-a288-a935f121a093.png)
![image](https://user-images.githubusercontent.com/6360098/215882321-09fa3439-321f-4345-ad14-0b44e71f6146.png)
 

### Your device model

RT-AC5300

### Firmware type

Merlin

### Firmware version

386.7_2

### Integration version with the issue

0.18.3

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.1.7

### Is there anything useful in the logs?

```txt
None
```

### Diagnostics information

[config_entry-asusrouter-0c305ec51a5b4297704092fc7234f35b.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10551005/config_entry-asusrouter-0c305ec51a5b4297704092fc7234f35b.json.txt)

### Additional information

I can provide more info if needed.

**Comment by Vaskivskyi** [comment]
Hey, @Salvora,

Thanks for your report and sorry that something does not work as expected. I will check what can be the reason and let you know if any more information is needed from your side

**Comment by Vaskivskyi** [comment]
Hello. Can you check, whether the issue persists with versions `0.23.0+`

**Comment by Vaskivskyi** [comment]
In case if the issue was not solved, please, reopen this issue
