### ISSUE TITLE
[Bug] Having my Roborock S5 Max appearing in the AsusRouter integration.

### ISSUE THREAD

**Issue by Fisarl** [Vaskivskyi/ha-asusrouter#536]
### The problem

For some reason, my vacuum cleaner (Roborock S5 Max) appears in the AsusRouter integration as another device. This looks strange since this is definitely not a router and I do not expect this device to be present in this integration.
![image](https://user-images.githubusercontent.com/116768097/218401078-432a66f0-5dce-42c3-b070-7b76e5888f24.png)
There are additional issues and I am unsure if I should create a new ticket. But just in case - I have duplicated devices with no entities and I am not able to remove them (see Main Router and Secondary Router devices which I have currently disabled).

### Your device model

RT-AX86U, ZenWiFi XD6

### Firmware type

Stock

### Firmware version

RT-AX86U: 3.0.0.4.388_22525-gd35b8fe, ZenWiFi XD6: 3.0.0.4.388_21380-g4fa255a

### Integration version with the issue

0.20.0 and all previous versions

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.2.3

### Diagnostics information

[config_entry-asusrouter-cf15d61152274c31ea41d6dad79963da.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10719916/config_entry-asusrouter-cf15d61152274c31ea41d6dad79963da.json.txt)

**Comment by Vaskivskyi** [comment]
Hey, @Fisarl,

That is normal behaviour for HA. This is not actually a robot vacuum device added by AsusRouter. Or, at least, it should not be.

AsusRouter only creates `device_tracker` entities. When the MAC address of the connected device is known to HA (such a device exists in another integration), the device tracker is automatically attached to a device and it starts showing in both integrations. Here is an example snapshot

<details>
<summary>Snapshot</summary>

![image](https://user-images.githubusercontent.com/6554415/218405133-e0f048ab-29e1-454d-8143-d0802af5b151.png)
</details>

as you can see, I have only 2 actual Asus devices and 10 others merged with device trackers.

On the other hand, it's a bit weird that your vacuum only shows AsusRouter and not the other integration name. Did you remove the Xiaomi integration for the vacuum? It might of course just be a bug in the HA frontend. You can check which entities the device provides.

<details>
<summary>Example</summary>

![image](https://user-images.githubusercontent.com/6554415/218406104-7391e631-b883-4d8b-a3b8-53de9088f6e4.png)
</details>

In the example, only a device tracker is from AsusRouter integration (showing a `Home` state) and 3 more are from the other integration.

---

As for the empty devices question. Did they appear after one of the integration updates or were they created from the beginning?

- In the first case, there might happen a bug during one of the migrations between versions. In case you are bothered by the thing showing up, you might try removing the integration and setting it up again. The correct way would be `Remove configured AsusRouter - Restart HA - Configure AsusRouter`.
- In the last case (if doubled devices are created from the initial configuration of the integration), I would kindly ask you to create a new issue, so we can collect all the needed data and troubleshoot it.

---

P.S. As far as I can see, you have a Ukrainian interface of HA. If so, what do you think about the Ukrainian translation of the AsusRouter configuration flow?

**Comment by Fisarl** [comment]
Dear @Vaskivskyi ,
> AsusRouter only creates `device_tracker` entities. When the MAC address of the connected device is known to HA (such a device exists in another integration), the device tracker is automatically attached to a device and it starts showing in both integrations.

This is new info for me, thanks. However, this is still strange. I do have Yeelight lamps, my smartphone (Mobile app integration in HA) connected via WiFi to my router and integrated into HA. None of these are present under the AsusRouter integration. 
Is there any way not to track such devices in the AsusRouter integration? It is completely fine for me to have my Roborock only under the Xiaomi integration and not both Xiaomi and AsusRouter.

> Did you remove the Xiaomi integration for the vacuum?

Yes. This morning it stopped working and I am going to reinstall this integration.
> Did they appear after one of the integration updates or were they created from the beginning?

Unfortunately. I am not sure here. It was definitely present in the past few versions of your wonderful integration. But I did not have time to report this issue so I have decided just to disable it. Would you suggest to reinstall your integration?

> P.S. As far as I can see, you have a Ukrainian interface of HA. If so, what do you think about the Ukrainian translation of the AsusRouter configuration flow?

Everything looks good. However, my initial setup was when I have English interface of HA. But still thank you for adding my native language :)

**Comment by Vaskivskyi** [comment]
@Fisarl,

There is no possibility to ignore only some of the connected devices. At least not yet. But actually, it might be a good new feature. Then, let's say when ignored by MAC, the device trackers will not be created at all - so it won't be merged with other integrations. I will add it to my `check whether possible` list.

This merging actually works not with all the integrations. Definitely, HA Companion (mobile phone app) does not support such a merge.

If you don't mind reinstalling AsusRouter, I would suggest it. Might help with double devices. And if not, we will be able to troubleshoot a bug.

**Comment by Fisarl** [comment]
@Vaskivskyi,

Thank you for the detailed and clear explanation. Having an option to not create device trackers by ignoring MAC (or asking the user if it is required to track the device) would be great. I believe we can close this topic. I will try to reinstall AsusRouter when I have more time. If the "double devices" issue will still persist I will submit another bug report.

**Comment by Vaskivskyi** [comment]
Ok, of course 👍🏻
