### ISSUE TITLE
Port forward setting expects blank in port not "None"[Bug] 

### ISSUE THREAD

**Issue by Tekno-man** [Vaskivskyi/ha-asusrouter#538]
### The problem

When creating port forwarding rules the option for internal port is optional. If this is left blank in the service call, the Asus router receives "None" in for this field. The port forward table does not accept this and while the port forwarding appears in the "virtual server/port forwarding" setting page, it is not in the port forwarding system log. 

If you cycle port forwarding off and on generate a HA service call while one of the port forwarding rules has "None" in the port column an error is generated in the system log and no port forwarding table is generated. 
![image](https://user-images.githubusercontent.com/53583738/218721470-35f2fcb4-a56a-4df9-8500-f100ca93d79e.png)

The solution i have found is to used port: ""  inputting a blank field like what is down in the web interface. The web interface expects a port number only, no text or space is allowed.
![image](https://user-images.githubusercontent.com/53583738/218722317-a6874598-8432-46de-97a0-a27e91a1ac79.png)

### Your device model

RT-AC86

### Firmware type

Stock

### Firmware version

3.0.0.4.386_49703

### Integration version with the issue

0.20

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.2.2

**Comment by Tekno-man** [comment]
I have just been trying a few options and I think the problem is actually with the asus firmware. When a blank field is left in the port field, and a service call is made to add a new port forward rule a reset of the firewall rules must be made and this turns any blank fields into "None" which up loading up the firewall rules is not allowed and generates the error I showed above. It works fine if you don't have any fields with blank ports or if the existing table has no blank port and you are simply adding a new rule that has a blank port. The issue only comes up if you try to add multiple rules with blank ports. Hopefully all this makes sense but let me know if you need any more information.

**Comment by Tekno-man** [comment]
Here is some rules before a service call and after a service call. I am not sure why after a service call the blank values are changing to "None"

before
![image](https://user-images.githubusercontent.com/53583738/218729357-3a129bc8-268e-4413-b24d-de9921ab2bd0.png)

After
![image](https://user-images.githubusercontent.com/53583738/218729858-dd7f4cbc-22d9-4036-b35f-6b7b8eb104fa.png)

**Comment by Vaskivskyi** [comment]
Hey, @Tekno-man,

Thanks for your report and provided information!

I will try to fix everything from the integration side as soon as possible

**Comment by Vaskivskyi** [comment]
Hey. The bug will be fixed in the next release - either today or tomorrow

**Comment by Tekno-man** [comment]
Wow so fast. Thanks!

**Comment by Vaskivskyi** [comment]
Sorry for the delay. Please check the new version 0.21.0

**Comment by Tekno-man** [comment]
Just tried it out, it works really well now. Can add multiple port forward
rules with blank ports. They also add very quickly.

**Comment by Vaskivskyi** [comment]
Great!

**Comment by Tekno-man** [comment]
I just updated and can see there has been a lot of changes but I can't see anywhere how to call the new service? I read through your new documentation and they service is still listed but I can't find it in ha anymore. Once I get it working again happy to contribute the github for people like me to make it a bit more obvious.

**Comment by Vaskivskyi** [comment]
Hello, @Tekno-man, sorry for the delay. The services were removed in `0.23.0` due to a breaking change in the backend library. They will be added back before the New Year. Please, follow #736 so that you'll get notified when the feature is ready

P.S. There is a bit of a delay in the docs update. Unfortunately, I don't have enough time and can forget some things. I'll try to keep it more up-to-date
