### ISSUE TITLE
[Bug] Device tracking not updating

### ISSUE THREAD

**Issue by alhemicar86** [Vaskivskyi/ha-asusrouter#550]
### The problem

Since few versions ago this started happening. Tracking was working normal, and after an update I noticed that devices that reported presence based on this integration stopped updating. Narrowed down the problem down to scheduled router reboots. It seems that integration doesn't fully restore the communication with the router after the router reboot. Reloading integration returns the tracking to a fully functional state until the next router reboot.

### Your device model

TUF-AX5400

### Firmware type

Stock

### Firmware version

3.0.0.4.388_22525-gd35b8fe

### Integration version with the issue

V0.21.0 and few earlier versions

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Home Assistant OS install 2023.2.5

### Is there anything useful in the logs?

```txt
2023-02-24 10:01:04.641 ERROR (MainThread) [homeassistant.components.switch] Platform asusrouter does not generate unique IDs. ID asusrouter_50_guest_2_4_ghz_1 already exists - ignoring switch.tuf_ax5400_guest_2_4_ghz_1
2023-02-24 10:01:04.644 ERROR (MainThread) [homeassistant.components.switch] Platform asusrouter does not generate unique IDs. ID asusrouter_50_parental_control already exists - ignoring switch.tuf_ax5400_parental_control
2023-02-24 10:01:04.645 ERROR (MainThread) [homeassistant.components.switch] Platform asusrouter does not generate unique IDs. ID asusrouter_50_port_forwarding already exists - ignoring switch.tuf_ax5400_port_forwarding
2023-02-24 10:01:04.645 ERROR (MainThread) [homeassistant.components.switch] Platform asusrouter does not generate unique IDs. ID asusrouter_50_open_vpn_client_1 already exists - ignoring switch.tuf_ax5400_openvpn_client_1
2023-02-24 10:01:04.646 ERROR (MainThread) [homeassistant.components.switch] Platform asusrouter does not generate unique IDs. ID asusrouter_50_wireless_2_4_ghz already exists - ignoring switch.tuf_ax5400_wireless_2_4_ghz
```

**Comment by alhemicar86** [comment]
An update, after updating today to 0.21.1 it entirely stops updating after initial update when system reboots/integration reloads.

**Comment by Vaskivskyi** [comment]
Hello, @alhemicar86,

Sorry to hear, you are experiencing problems with the integration.

Are there any errors in the log from AsusRouter except for the not generating unique_id (which is a separate issue #528?

Do the device_trackers stuck in some state (always stuck online / offline), just stuck in any state they were the last or become unavailable and stuck so?

**Comment by alhemicar86** [comment]
Found no errors in the logs. They are simply not updating. Only logged errors are the one related to unique_id. Device trackers get stuck in the last state that was accurate during the inegration initial configuration and they are updated after the integration is reloaded (and stuck in new states). The states are Home, Away and Work, and they update once after each integration reload.

**Comment by Vaskivskyi** [comment]
Ok, I see. Are there any similar problems with other entities? Sensors and binary sensors? Do they work properly or also stuck?

Also, do you use an SSL connection to your device?

**Comment by alhemicar86** [comment]
They seem to update properly, looked at Graphs, they seem to pool points at regular intervals. I did use SSL connection, I updated configuration now to disable it, now that you mentioned it, I think I had it disabled in the past. Will let you know if that changes anything.

**Comment by Vaskivskyi** [comment]
Actually, it usually works better with SSL.

The thing is, that AsusWRT (the FW) does not disconnect SSL sessions as regularly as non-SSL. And since most of the bugs are happening when API disconnects and tries to reconnect again, most users had better luck with SSL

**Comment by alhemicar86** [comment]
This is a bit weird behavior, several minutes ago I returned it to SSL session, and when someone came home it did update their status. It will probably stop reporting again it in a few hours or minutes when the session drops.

**Comment by alhemicar86** [comment]
Still running good. Not sure why, aside from changing SSL session to non-SSL and back. Will see if it survives through the nightly reboot.

**Comment by alhemicar86** [comment]
It finally stopped tracking. There wasn't any reboot on the router side.

**Comment by Vaskivskyi** [comment]
And nothing in the log around the time it stopped working?

**Comment by alhemicar86** [comment]
Nothing related to it, but something caused one of esp nodes to reconnect with few warnings

**Comment by alhemicar86** [comment]
As I wrote that this appeared in the log... 2023-02-25 09:13:56.867 ERROR (MainThread) [custom_components.asusrouter.router] Error connecting to '192.168.50.1' for device update: None

**Comment by alhemicar86** [comment]
It is getting weirder, out of 4 trackers two are updated, two are not, just checked.

**Comment by Vaskivskyi** [comment]
Does the connected devices sensor value correspond to the number of devices in the router Web UI?

![image](https://user-images.githubusercontent.com/6554415/221351632-5ba70cbc-1ea0-4050-8a0f-dec266e737c9.png)

**Comment by alhemicar86** [comment]
No, it is showing 21, and router lists 17 clients

**Comment by nickaggie** [comment]
+1 I'm experiencing the exact same issue as described here

**Comment by Vaskivskyi** [comment]
@nickaggie, please provide info about your device (model and FW version)

**Comment by Vaskivskyi** [comment]
Let's continue this discussion in issue #570. The problem with device trackers is happening for different users and it will be much easier to collect all the useful info in a single issue.
