### ISSUE TITLE
[Bug] Total traffic resets at 4Gb

### ISSUE THREAD

**Issue by BeHappy2021** [Vaskivskyi/ha-asusrouter#557]
### The problem

Exact same problem as [the core integration](https://github.com/home-assistant/core/issues/31404). This issue started with the update to 0.20.0. The download amount resets every time it gets to 4Gb.
![download_reset](https://user-images.githubusercontent.com/83814258/221413961-0f3e82b5-eaaa-4aaf-a86f-a69708a7a3dc.jpg)

This applies to all of the upload and download sensors.

### Your device model

DSL-AC68U

### Firmware type

Stock

### Firmware version

3.0.0.4.386.50117_geaaff54

### Integration version with the issue

0.20.0 and later

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.2.5

### Is there anything useful in the logs?

```txt
Nothing useful found in the logs
```

### Additional information

The [workaround](https://github.com/home-assistant/core/issues/31404#issuecomment-1030669795) for the core integration also works for this issue.

**Comment by Vaskivskyi** [comment]
Hello, @BeHappy2021,

The issue with 4 GB is due to the limit of the FW on older models for traffic monitoring. Actually, the best way to compensate for this in HA - is to create a utility_meter, which would be calculating traffic for a period of time regardless of overflows on the device side.

Did it work any differently before you updated the integration to 0.20.0? This would be quite unexpected, but in such a case please try to recall which version worked differently.

P.S. There might be a way to solve the problem from the backend library point of view (create an additional layer to calculate the traffic regardless of overflow), but it might have strange behaviour on HA reboots (integration reloads) when the library will be reconnecting

**Comment by BeHappy2021** [comment]
Hi @Vaskivskyi,

Thanks for the quick reply. It did work properly before 0.20.0 which is one of the reasons I switched from the core integration to this one. I've been using the integration for quite a few months now (I think I was the initial person to say it worked on the DSL-AC68U) and it has worked fine up until the major update to 0.20.0 and the versions after it. I was hoping it was a quick glitch but it seems to be here to stay. It would definitely have worked in versions 0.18.x and 0.17.x on the previous versions of HA-core.

I have created the utility meters as before so my graphs all look fine now. Before I was able to directly use the sensors (e.g.  sensor.dsl_ac68u_wlan0_download).

**Comment by Vaskivskyi** [comment]
Weird. I will check it

**Comment by Vaskivskyi** [comment]
You might try to check whether it's any different now with the new beta release `0.23.0b1`. There is no more constant limitation in the network sensors, so it might have changed something. But I cannot guarantee

**Comment by BeHappy2021** [comment]
I've just updated to 0.23.1 today so I'll check tomorrow to see if it is any different.

**Comment by BeHappy2021** [comment]
I've had the new version running for a couple of days now (when I went to update the beta versions were older). Same thing with all the sensors resetting at 4Gb.

**Comment by Vaskivskyi** [comment]
I am afraid, in this case, it's not due to AsusRouter. The integration just takes whatever values are available from the device directly without any processing

The only option then would be to create utility meters to track the total values you would like to track

**Comment by BeHappy2021** [comment]
No problem. I think it must have been a fluke or weird firmware version that had it working when it did. It never did with the core integration so I was surprised it did with this one. I've got utility meters set up so all good. 

That's for looking into it.
