### ISSUE TITLE
[Device support] Integration never switches a device to "Not Home"

### ISSUE THREAD

**Issue by pejannl** [Vaskivskyi/ha-asusrouter#562]
### Anything you want to mention?

I am running this integration since last Saturday. Today I noticed that the device continuously reports devices as "Home", even when they are gone. It never switches the status back to "Not Home" when a user goes away.

### Your device model

RT-AC88U

### Firmware type

Stock

### Firmware version

3.0.0.4.386_48260

### Does everything work well?

No

**Comment by pejannl** [comment]
This is the status of my phone as reported by my Deco integration
<img width="545" alt="Scherm­afbeelding 2023-02-27 om 21 14 17" src="https://user-images.githubusercontent.com/73560870/221676556-27d0c856-7fe7-44bb-a851-ac3db9dd2f1a.png">

**Comment by pejannl** [comment]
It looks as if the integration loses its settings or configuration or connection or something... (??)

I restarted Home Assistant and then I get 
<img width="262" alt="Scherm­afbeelding 2023-02-27 om 21 50 22" src="https://user-images.githubusercontent.com/73560870/221682603-a14f9948-cf87-41c1-bdfe-8cde5335c025.png">

and the log reports
<img width="390" alt="Scherm­afbeelding 2023-02-27 om 21 51 10" src="https://user-images.githubusercontent.com/73560870/221682760-2a7502ff-db84-49eb-a502-a36c6dcc8d00.png">

**Comment by Vaskivskyi** [comment]
Let's continue this discussion in issue #570. The problem with device trackers is happening for different users and it will be much easier to collect all the useful info in a single issue.
