### ISSUE TITLE
[Bug] no events triggered

### ISSUE THREAD

**Issue by Morriz** [Vaskivskyi/ha-asusrouter#573]
### The problem

Hi, I enabled all events but get none. I tried listening to `*`  but all I get are `stage_changed` events.

### Your device model

RT-AC68U

### Firmware type

Stock

### Firmware version

3.0.0.4.386.51255_g486ded6

### Integration version with the issue

0.21.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.3.1

### Is there anything useful in the logs?

```txt
nothing relevant in the logs with logging at debug level
```

### Diagnostics information

[config_entry-asusrouter-6f1a6f387af8a79c370fc0e353f1aed4.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10910827/config_entry-asusrouter-6f1a6f387af8a79c370fc0e353f1aed4.json.txt)

**Comment by Morriz** [comment]
got it to work by enabling sensors that were disabled by default (but why?). I suspect it was the `sensor.{device}_latest_connected` one

**Comment by Vaskivskyi** [comment]
Hello, @Morriz,

Sorry to hear, you are experiencing problems with the integration. And this is quite strange, it was fixed by enabling sensors

Please, allow me some time to check it out

**Comment by Vaskivskyi** [comment]
Hey,

The same as for the other issue #576 you opened, I cannot reproduce the problem. All the events are entirely independent of any entity and do not change behaviour.

The only case when events are not triggered - is if they are disabled in the integration settings. Please check the configurations.

If the issue still occurs to you on the latest AsusRouter version (0.22.0), please provide steps to reproduce it. If events are working in some conditions, but not others, please provide the conditions for it

**Comment by Morriz** [comment]
lets close it and if needed somebody else will find this ;)
