### ISSUE TITLE
[Bug] Wrong device name for ZenWiFiAX XT8

### ISSUE THREAD

**Issue by EBassie** [Vaskivskyi/ha-asusrouter#578]
### The problem

Since HA 2023.3 and last 2 versions of AsusRouter my ZenWiFiAX XT8 (router + node) is being added as a RT-AX95Q and it seems my mesh node is being added as a ZenWiFiAX. They used to have the same name in earlier versions. But now they are completely different.

I also lost the some entities like my Guest WLAN switches.

Tried to reinstall 0.22.0 but problem stays the same. 
Older versions don't seem to work with HA 2023.3 any more, so I cannot test those.

Also after rebooting HA, it keeps finding new integrations for the ZenWiFiAX router even though both the router and node are already installed.

### Your device model

ZenWiFi AX (XT8)

### Firmware type

Stock

### Firmware version

3.0.0.4.388_22525

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Frontend 20230306.0

**Comment by Vaskivskyi** [comment]
Hello, @EBassie,

Can you please append diagnostics for both devices? Actually, RT-AX95Q is one of the names for Zen WiFi. And some devices are reporting it exactly this way. But would be strange, if it changed with the integration update since integration is not deciding anything - just asks the device for a name explicitly. Did you maybe also update firmware only on one of the devices?

**Comment by EBassie** [comment]
Hi Vaskivskyi,

thanks for you reply. I don't really care about the devices being named different than before, but the troublesome thing is that I have lost a bunch of sensors, like the WiFi Toggles.

When I download the diagnostics for both devices, the file is identical for both:
[config_entry-asusrouter.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10969203/config_entry-asusrouter.txt)

But I find it weird that the names are not identical:
![image](https://user-images.githubusercontent.com/2745889/225019269-1ca87796-9693-4e63-8821-5d331a5c0e44.png)

Both devices are on the same firmware: 3.0.0.4.388_22525

Also the diagnostics show installed version of AsusRouter is 0.21.1, while HACS shows 0.22.0

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the late reply. If you are up to it, please, check the latest beta release `0.23.0b1` of the integration and let me know whether you got access to the sensors missing before or you still have the same / other issues

**Comment by Vaskivskyi** [comment]
With `0.27.0` the model name should now correspond to the `UI Model Name` as defined by Asus. Also, it should now be the same for the main device added to HA and AiMesh node devices created automatically for each node.
