### ISSUE TITLE
[Feature] Ability to ignore devices from connection/disconnection events

### ISSUE THREAD

**Issue by joeShuff** [Vaskivskyi/ha-asusrouter#583]
### The problem

I have some devices that I dont care if they connect/disconnect and they do it frequently. It would be good if I can specify a list of mac addresses to ignore from events.

### Specific device(s)?

No

### Firmware type

No

**Comment by Vaskivskyi** [comment]
Hello, @joeShuff,

Thanks for your idea! Actually, I was already considering similar for just the device trackers (not to create them for ignore list e.g.). But this behaviour can also extend to the events.

So, already in consideration and will probably be implemented soon

**Comment by Vaskivskyi** [comment]
It took some time, but with #761 even a bit better feature is included - the possibility to exclude devices from tracking and events or the possibility to include only devices you'd like to monitor.

In the first case (exclude), any device which is on the list of selected will be ignored by HA - no device_tracker will be created for it and no event fired. For all other devices, everything will work as before.
In the second case (include), only devices on the list will be monitored by the integration. Keep in mind, in this case, the events of new devices joining will NOT be fired at all. So, choose wisely.

The new version with this feature will be released soon.

**Comment by Vaskivskyi** [comment]
Released in `0.28.0`
