### ISSUE TITLE
[Bug] Wan totals resetting constantly?

### ISSUE THREAD

**Issue by pergolafabio** [Vaskivskyi/ha-asusrouter#585]
### The problem

Hi, not sure if it's normal or not, but I have enabled the WAN sensors... They are increasing, and during the day they always go back to 0 and increase again...

Is this normal behavior? Would be interesting to see how many stuff I downloaded/uploaded during 1 day, and then reset....

### Your device model

RT-ac88u

### Firmware type

Merlin

### Firmware version

386.5.0

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.4

**Comment by pergolafabio** [comment]
![Uploading Screenshot_20230406-204543.jpg…]()

**Comment by pergolafabio** [comment]
Here a screen, I must have downloaded much more today ;-)

![Screenshot_20230406-204543](https://user-images.githubusercontent.com/43251136/230468995-7549c371-0601-47f0-8e6d-f871e4d49954.jpg)

**Comment by Vaskivskyi** [comment]
Hello. Sorry that I have missed your issue.

There are 3 possible reasons for the traffic sensors to reset:

- Your device has a low total cap for traffic measurement (this was more important with the older devices, limited at 4 GB only)
- The device has restarted (which erases the current measurement)
- Something is wrong with the integration

In the first 2 cases, you should be able to easily check it. If it resets at the same value - it will be visible in the sensor history. If restarted - in the reboot sensor.

In case of the 3 option and if you still wish to troubleshoot the issue, please let me know

**Comment by pergolafabio** [comment]
Np!

That makes sense, I see indeed 4 GB max..
I have the rt-ac88u, it's indeed older, but not that old :-)

Thnx, so can be closed then?

**Comment by Vaskivskyi** [comment]
Yeah. If it all goes to 4 GB - that's the device limitation.

For such cases, the best option is to create a `utility_meter` in HA, which would be watching a sensor you need and just accumulating the traffic

**Comment by pergolafabio** [comment]
Perfect, will do that
