### ISSUE TITLE
[Bug] Opvpn client control fails to connect

### ISSUE THREAD

**Issue by MitchellThompkins** [Vaskivskyi/ha-asusrouter#586]
### The problem

I'm new to home assistant so it may simply be that I've configured something incorrectly, but I'm not able to control my openvpn client via the home assistant integration. I've configured one of my vpn clients with the settings provided by my VPN service provider. I've provided my username, password, and .ovpn file to the router.

![Screenshot from 2023-04-11 11-19-41](https://user-images.githubusercontent.com/6433864/231254596-03b7d1d4-25b3-4827-b163-d9e2c6791fed.png)

When I click "activate" from the router interface this works, my router connects and everything is happy.

![image](https://user-images.githubusercontent.com/6433864/231254407-859c95de-7720-417a-abb6-be8b69aebbb1.png)

However, when I try to start it from HomeAssistant it fails to start and my router system log provides message below. This looks to me like it's not using the correct credentials provided by the router interface.

```
Apr 11 11:25:02 vpnclient1[28393]: OpenVPN 2.4.11 arm-buildroot-linux-gnueabi [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan  6 2022
Apr 11 11:25:02 vpnclient1[28393]: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.03
Apr 11 11:25:02 vpnclient1[28393]: ERROR: username from Auth authfile 'up' is empty
Apr 11 11:25:02 vpnclient1[28393]: Exiting due to fatal error
```

However, the switch actually does remain on, as if the VPN was connected (this may be the expected behavior but I'm not sure).

![image](https://user-images.githubusercontent.com/6433864/231256353-7bdde5f2-fac7-4904-b5db-c059d78c1714.png)

Lastly, I noticed in the integration that I only have 2 attributes, error code and status, but in [the documentation](https://asusrouter.vaskivskyi.com/features/openvpn.html#binary-sensor-switch) it looks like there should be more attributes.

![Screenshot from 2023-04-09 20-38-57](https://user-images.githubusercontent.com/6433864/231256795-5c72bdd8-10ab-4b38-8c8a-037c2018a586.png)

Thanks for this feature, it's really cool!

### Your device model

RT-AX86S

### Firmware type

Stock

### Firmware version

3.0.0.4.386_46061

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Home Assistant 2023.4.1 Frontend 20230406.1 - latest

### Is there anything useful in the logs?

```txt
It spits out a lot of data, but this is the only thing related to the VPN that I can find.


homeassistant  | 2023-04-11 11:25:32.234 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `devicemap` is enabled                                            
homeassistant  | 2023-04-11 11:25:32.235 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `vpn` is disabled                                                 
homeassistant  | 2023-04-11 11:25:32.235 DEBUG (MainThread) [asusrouter.asusrouter] Value `vpn` is not in cache yet by monitor `devicemap` or the caching time
 has already expired                                                           
homeassistant  | 2023-04-11 11:25:32.236 DEBUG (MainThread) [asusrouter.asusrouter] Monitor `devicemap` is enabled                                            
homeassistant  | 2023-04-11 11:25:32.319 DEBUG (MainThread) [custom_components.asusrouter.router] Finished fetching vpn data in 0.085 seconds (success: True)
```
```


### Diagnostics information

_No response_

### Additional information

I wasn't exactly sure what level of diagnostic information to provide above. If you need more please let me know and I can try to provide it.

**Comment by Vaskivskyi** [comment]
Also, the whole list of the entity attributes is only available on the successful connection. In your case, the attributes correspond to the disconnected status. I would expect the integration to at least report some error code and I will check this out.

**Comment by MitchellThompkins** [comment]
@Vaskivskyi  thanks! Let me know if there are any tests I can do on my end to get you some more data.

**Comment by Vaskivskyi** [comment]
In case you are still experiencing this issue, please, reopen it or open a new one for any different problem with the integration.
