### ISSUE TITLE
Hungarian translation [Feature] 

### ISSUE THREAD

**Issue by zsigus** [Vaskivskyi/ha-asusrouter#588]
### The problem

Hi

[hu.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/11304963/hu.txt)

Thank you for your work!

I am attaching the Hungarian translation.
.txt -> .json

### Specific device(s)?

No

### Firmware type

No

**Comment by Vaskivskyi** [comment]
Hello, @zsigus,

Thanks for your help. The proposed changes will be added to AsusRouter in the next release

**Comment by zsigus** [comment]
Thank you! :)

**Comment by Vaskivskyi** [comment]
The translation is added in the latest [0.23.0b0](https://github.com/Vaskivskyi/ha-asusrouter/releases/tag/0.23.0b0) release
