### ISSUE TITLE
Only the main router is shown [Feature] 

### ISSUE THREAD

**Issue by jjprz** [Vaskivskyi/ha-asusrouter#589]
### The problem

I can only reboot and switch the main router led. Would it be possible to do this on the other routers in the mesh?

### Specific device(s)?

None

### Firmware type

None

**Comment by Vaskivskyi** [comment]
Hello, @jjprz,

Yes, this in principle is possible.

The first way would be to add your AiMesh nodes as separate devices to the integration (using AiMesh node mode) - then you will get control over reboot and LED features.

Or would you like to have control of all the LEDs/reboots on all the nodes at the same time from the main device? That would be more complicated, but potentially such a feature is possible, it will just require some time for development.

**Comment by jjprz** [comment]
Wonderful!
Thank you so much
This integration is fantastic, hopefully it will become the official integration.
