### ISSUE TITLE
[Bug] AXE-11000 / 6 GHz WLAN label

### ISSUE THREAD

**Issue by justmatze1992** [Vaskivskyi/ha-asusrouter#591]
### Anything you want to mention?

hey

there is a small bug the 6ghz module, it is displayed as a second 5 ghz module.

![Bildschirmfoto 2023-05-07 um 09 58 47](https://user-images.githubusercontent.com/50325883/236665308-c79368e9-205a-493f-af83-37fa001f027a.png)

### Your device model

GT-AXE11000

### Firmware type

Stock

### Firmware version

3.0.0.4.388_22525-gd35b8fe

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello. I am really sorry for such a late reply.

Can you please confirm, that the issue is still there and that you have a possibility to test some code that will help fix the issue?

**Comment by JohnyR** [comment]
Hi @Vaskivskyi, I have an ET8 where the 6GHz is also showing up as 5GHz-2. I can help test if needed.

**Comment by Vaskivskyi** [comment]
@JohnyR,

If you can use the latest AsusRouter backend library (`1.1.0b1` - a beta release, included with the latest integration beta release as well), you can use it to easily get the raw temperature data which I need.

- to install the library `pip install asusrouter==1.1.0b1`
- run it as the following:

```
python -m asusrouter -o path/to/save --host 192.168.1.1 -u admin -p admin -P 80 --dump --zip
```

- this will queue all the known endpoints from your device and create a zip with raw data in it + a log file. I need the content of the file which looks like `{date}-Endpoint.TEMPERATURE.content`


<details>
<summary>Full list of asusrouter arguments</summary>

```
  -h, --help            show this help message and exit
  -o OUTPUT, --output OUTPUT
                        The output folder for the log.
  --dump                Perform a full dump.
  --host HOST           The hostname / ip address of the router.
  -u USERNAME, --username USERNAME
                        The username for the router. Default: `admin`.
  -p PASSWORD, --password PASSWORD
                        The password for the router. Default: `admin`.
  -s, --ssl             Use SSL for the connection.
  -P PORT, --port PORT  The port to connect to. Only when using non-default settings. Default is 80 for HTTP and 443 for HTTPS.
  --debug               Enable debug logging.
  --zip                 Zip the output.
```
</details>

---

This is a new tool to give users a possibility to dump device data and share it for better debugging of AsusRouter as well as implementing new features. Keep in mind, that the `.content` files are a raw data from the device - some of them will include MAC / IP addresses as well as names of your devices.

**So, in case you want to share anything except the temperature endpoint, do it only privately**

**Comment by JohnyR** [comment]
@Vaskivskyi, running it as we speak. How long is it supposed to take?

**Comment by Vaskivskyi** [comment]
Ah. I now understood, that I actually answered the wrong question... Sorry for that. The data we need is in a different part and is not available right now as easily... I will adjust the things and let you know what to try

P.S. The test should take 10-30 s only in principle. Also, it should run with the same settings as you have for the integration

**Comment by JohnyR** [comment]
Hahaha, ah, makes sense. I was a little confused why you wanted temperature data. Sure, let me know.

**Comment by Vaskivskyi** [comment]
@JohnyR,

with `0.24.0` or just by installing `pip install asusrouter==1.1.0` you'll now be able to get a larger set of data from the device when running it the same way:

```
python -m asusrouter -o path/to/save --host 192.168.1.1 -u admin -p admin -P 80 --dump --zip
```

You'll need file `{date}-Endpoint.HOOK.content`. There will be several of them, one of the interest is the one with something like this:

```
{
"cpu_usage":{"cpu1_total":"52557468","cpu1_usage":"4733197","cpu2_total":"52587131","cpu2_usage":"1731814","cpu3_total":"52621020","cpu3_usage":"1821047","cpu4_total":"52620879","cpu4_usage":"1720689"},
"memory_usage":{"mem_total":"1048576","mem_free":"235464","mem_used":"813112"},
"netdev":{ "BRIDGE_rx":"0x30a0b6bba","BRIDGE_tx":"0x134ce06712","INTERNET_rx":"0xe5d193f41","INTERNET_tx":"0x2000941dd","INTERNET_rx":"0xeb9a134fe","INTERNET_tx":"0x227d6b665","WIRED_rx":"0x39ddba16c","WIRED_tx":"0x80c855eba","WIRELESS0_rx":"0x1d09911e","WIRELESS0_tx":"0x610f01c4","WIRELESS1_rx":"0x2f570951","WIRELESS1_tx":"0x32ed23b8c","LACP1_rx":"0x0","LACP1_tx":"0x5e9c7a8c","LACP2_rx":"0xf5b08c18","LACP2_tx":"0x4408840"}
}
```

We need everything in the `netdev` key. This is the list of network interfaces and traffic on them. We need to find out which ones you have, so I can fix the labels

**Comment by JohnyR** [comment]
@Vaskivskyi sorry for the delay. Hope this helps:

```
{
    "cpu_usage": {
        "cpu1_total": "44213630",
        "cpu1_usage": "3134258",
        "cpu2_total": "44213628",
        "cpu2_usage": "3540060",
        "cpu3_total": "44213626",
        "cpu3_usage": "2490619",
        "cpu4_total": "44213629",
        "cpu4_usage": "235106"
    },
    "memory_usage": {
        "mem_total": "524288",
        "mem_free": "193796",
        "mem_used": "330492"
    },
    "netdev": {
        "BRIDGE_rx": "0x7710a094",
        "BRIDGE_tx": "0x344459921",
        "WIRED_rx": "0x8b9ed3f28",
        "WIRED_tx": "0x582c3a4dc3",
        "WIRELESS0_rx": "0x38f6edb11",
        "WIRELESS0_tx": "0x12aafc194",
        "WIRELESS1_rx": "0x53090e92ed",
        "WIRELESS1_tx": "0x7f0498e7f",
        "WIRELESS2_rx": "0x84c1feb2",
        "WIRELESS2_tx": "0xab594b7a"
    }
}
```

**Comment by Vaskivskyi** [comment]
Thanks!

**Comment by Vaskivskyi** [comment]
@JohnyR, is your device shown in the HA UI as `ZenWiFi ET8` or somehow else?

Here, just below the `Device info` label

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/320ed450-14d1-490d-9a73-2765aa7c28c2)

**Comment by JohnyR** [comment]
@Vaskivskyi, main node:
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/967548/41823770-c17d-487f-8548-cb971a269329)

secondary node connected to main node:
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/967548/01553819-5325-4bcd-bb2d-67a81f47feae)

**Comment by JohnyR** [comment]
Thanks @Vaskivskyi!

**Comment by JohnyR** [comment]
@Vaskivskyi just had a chance to check, seems like the interface is still named 5 GHz-2 in the config flow:
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/967548/1ece24bb-830b-41f4-a7b7-b2624344ccd6)

**Comment by Vaskivskyi** [comment]
@JohnyR,

can you please share the identity of your device? I just used the code available for my model to see what values are passed on the `6 GHz` being available but might be that different branches of the FW are not compatible.

You'd need a first request sent to `Endpoint.HOOK` (the second request in general, just after the login) which would look like this:

```
{
"serial_no":"REDACTED",
"label_mac":"REDACTED",
"lan_hwaddr":"REDACTED",
"wan_hwaddr":"REDACTED",
"productid":"RT-AX88U",
"firmver":"3.0.0.4",
"buildno":"388.4",
"extendno":"0",
"rc_support":"mssid 2.4G 5G usbX2 update switchctrl manual_stb 11AX pwrctrl WIFI_LOGO nandflash movistarTriple wifi2017 app ofdma wpa3 reboot_schedule ipv6 ipv6pt PARENTAL2 dnsfilter am_addons cake ntpd dnspriv dualwan pptpd openvpnd utf8_ssid printer modem webdav rrsut cloudsync media appnet timemachine hdspindown diskutility nfsd dnssec usb_bk email bwdpi wrs_wbl ookla tor HTTPS letsencrypt ssh vpnc repeater psta wl6 wifi_tog_btn user_low_rssi wifiradar tcode usericon stainfo realip lacp wanbonding wtfast ifttt alexa ipsec_srv mumimo netool cfg_sync no_finiwl betaupg amas bcmwifi bcmhnd mbo conndiag eula proxysta iperf3 gn_wbl amazon_wss account_binding gameMode wireguard ftp_ssl acl96 dhdlog dis11b smart_connect",
"ss_support":"asuswebstorage webdav dropbox ftp samba usb ",
"led_val":"0"
}
```

and you can get it in the same way as before https://github.com/Vaskivskyi/ha-asusrouter/issues/591#issuecomment-1817996762

**Comment by JohnyR** [comment]
@Vaskivskyi, sure:

```
{
    "serial_no": "-",
    "label_mac": "-",
    "lan_hwaddr": "-",
    "wan_hwaddr": "",
    "productid": "RT-AXE95Q",
    "firmver": "3.0.0.4",
    "buildno": "388",
    "extendno": "23759-gfd1c030",
    "rc_support": "mssid 2.4G 5G update usbX1 switchctrl manual_stb 11AX pwrctrl WIFI_LOGO nandflash movistarTriple wifi2017 app ofdma wpa3 reboot_schedule ipv6 ipv6pt PARENTAL2 dnsfilter dnspriv dualwan pptpd openvpnd utf8_ssid printer modem webdav rrsut cloudsync media appnet timemachine hdspindown diskutility dnssec usb_bk frs_feedback dblog email 5G-2 bwdpi wrs_wbl ookla HTTPS letsencrypt ssh vpnc vpn_fusion repeater psta wl6 user_low_rssi tcode usericon cfg_wps_btn stainfo cloudcheck realip ifttt alexa ipsec_srv mumimo netool cfg_sync no_finiwl fupgrade afwupg betaupg amas amas_bdl bcmwifi bcmhnd mbo conndiag eula proxysta iperf3 wifi6e account_binding wireguard ftp_ssl acl96 hnd_ax_675x dhdlog dis11b smart_connect",
    "ss_support": "asuswebstorage webdav dropbox ftp samba usb ",
    "led_val": "1"
}
```

**Comment by Vaskivskyi** [comment]
Hm. That would explain why it didn't work with the last update. Your device has `5G-2` in the supported services and not the key for the WiFi 6E support. That's weird. I will then just do a check for the device model. Unfortunately, that would mean that the fix will only work for this type of device, not for other 3-bands with 2.4, 5 and 6 GHz support

**Comment by Vaskivskyi** [comment]
@JohnyR, `0.25.0` should fix it for your device model, hopefully. Give it a try
