### ISSUE TITLE
Faulty device status 

### ISSUE THREAD

**Issue by aventouris** [Vaskivskyi/ha-asusrouter#593]
### The problem

Hi.

When the phone devices are connected to the WiFi appear normally connected all the time. If a device goes away it appears constantly to connect for a second and disconnect from the WiFi
![HA-phone_status](https://github.com/Vaskivskyi/ha-asusrouter/assets/5867614/35f04a38-14be-4d07-8bb4-9c213cf47a7b)

### Your device model

RT-AX95Q

### Firmware type

Stock

### Firmware version

3.0.0.4.388.23285_g5068da5

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Home Assistant 2023.5.3

**Comment by TeddyLafrite** [comment]
Hi
Same here
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/94308304/6a9c31a9-b09a-442c-93f6-6e75c4889cab)

home/at-home every 5mn all night long, phones were in flight mode

**Comment by aventouris** [comment]
Hello again.

In my HA installation there are several WiFI Temperature & Humidity Tuja sensors, that fires every 5 mins to update Tuja cloud with the current state. During this period active WiFi the number of the connected devices increasing for a secs and decreases periodically.

Is this something to do with the wrong update of the status of the offline connected devices ?
![HA-phone_status_2](https://github.com/Vaskivskyi/ha-asusrouter/assets/5867614/6c30a8be-7d86-48ca-aaf9-6073c97c7b22)

**Comment by Vaskivskyi** [comment]
Hello, @aventouris,

Thanks for your report. I'll take a closer look at it. Unfortunately, device tracking features are not perfect, but I am trying to improve them with time.

I'll let you know if some additional info is needed from your side

**Comment by aventouris** [comment]
Hi Vaskivski.

After updating to the latest (3.0.0.4.388.23285_g5068da5) version, the problem vanished ;-)
<img width="1355" alt="Screenshot 2023-06-05 at 11 05 45 AM" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/5867614/aa26c4cc-66ef-471d-a0cc-b0b476a1269c">
