### ISSUE TITLE
[Feature] Support Control of Wireguard VPN Clients

### ISSUE THREAD

**Issue by drewdah** [Vaskivskyi/ha-asusrouter#594]
### The problem

Wireguard VPN (server and clients) are enabled In ASUS router versions `3.0.0.4.388.20000` and higher on a large number of their support devices and it is a typically faster alternative to OpenVPN. https://www.asus.com/support/FAQ/1048282/

It would be really amazing to be able to enable/disable my Wireguard VPN clients on my router using HA, similar to the existing OpenVPN control.

![Screenshot 2023-05-25 094538](https://github.com/Vaskivskyi/ha-asusrouter/assets/273682/34f24996-b05d-4b20-ba43-aa5253bb1e60)

### Specific device(s)?

Yes

### Firmware type

No

**Comment by Vaskivskyi** [comment]
Hello, @drewdah,

This feature is already in development and will be added soon.

P.S. Unfortunately, for the last several months I didn't have time to work on AsusRouter, so some time might be needed to first deal with the most important bugs and problems before releasing new features.

**Comment by drewdah** [comment]
@Vaskivskyi Thank you very much, that's great to hear. Genuinely appreciate your work

**Comment by Vaskivskyi** [comment]
Support is ready. It will be released with version `0.24.X` soon (https://github.com/Vaskivskyi/asusrouter/pull/356)

**Comment by Vaskivskyi** [comment]
Hello, please check the new beta release `0.24.0b0` for the new functionality. The stable version will be released later this week.
