### ISSUE TITLE
[Bug] Device_trackers not created for wired devices added into a router set as media bridge

### ISSUE THREAD

**Issue by mihsu81** [Vaskivskyi/ha-asusrouter#596]
### The problem

The device trackers which should have been created under the Media Bridge, are created under the Router integration but they either appear away (BETHAYN-ASUS) or home with unknown connection type (TUYA-GATEWAY), or don't get created at all (HAOS02) even though they're present on the media bridge. By comparison, devices wired into an AiMesh Node (Tahoma) get all the details correctly.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/40715497/023e91f3-343b-41d3-8f73-d92c43fa1532)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/40715497/f83aca36-005a-4e73-ac57-b070d5ca30be)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/40715497/063a7aee-eb7b-4938-9ad6-6f080f95aef1)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/40715497/f7a4cb18-dab9-43d7-b64e-8e92ddae24ff)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/40715497/fdcf3f2b-57b9-4388-bc07-5a1c1ae0d608)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/40715497/1b65bae9-0624-42be-9c02-754f4dba1196)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/40715497/7e764706-6e89-44c6-ba3f-aeed42747bc2)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/40715497/f9b75844-48db-4ca6-a454-5759447b4134)

The model is RT-AC87U with firmware 384.13_10.

### Your device model

RT-AC87U

### Firmware type

Stock

### Firmware version

3.0.0.4.384.13_10

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.6.1

### Diagnostics information

[config_entry-asusrouter-118d2a5bac80d3b71e3e596e35fc3a02.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/11733685/config_entry-asusrouter-118d2a5bac80d3b71e3e596e35fc3a02.json.txt)

**Comment by Vaskivskyi** [comment]
Please, check whether you are still experiencing this issue with the latest beta release `0.23.0b1`. You need the HACS option `Show beta releases` to be set in the settings for AsusRouter repository to be able to install a beta version

**Comment by Vaskivskyi** [comment]
In case you are still experiencing this issue, please, reopen it or open a new one for any different problem with the integration.
