### ISSUE TITLE
[Bug] Turning off and on the wifi network and guest network is not available

### ISSUE THREAD

**Issue by Roei639** [Vaskivskyi/ha-asusrouter#600]
### The problem

The wifi and guest network control buttons are not available.
I tried to reconfigure the integration and the problem still persists.

### Your device model

RT-AX56U

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.2_2

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.6.2

**Comment by Vaskivskyi** [comment]
Hello. Was it never available or just stopped working? Did you change device FW before it happened? Any errors in the HA log?

**Comment by Roei639** [comment]
It worked before and stopped, I uninstalled the integration and reinstalled and still not working.  There are no errors in the log

**Comment by Roei639** [comment]
It may have happened because of a router version update

**Comment by Roei639** [comment]
Waiting for a reply
thanks

**Comment by Roei639** [comment]
?

**Comment by Vaskivskyi** [comment]
Hello and sorry for the late reply

After all the tests with the same FW version, it does not seem to be related to the FW update. The integration supports 388.2_2

Can you turn on/off the guest WLAN in the device admin panel? If you reboot your router and then reload the integration, are the switches still not available?

Also, can you please upload diagnostics of the integration (use the Download diagnostics button)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/43655852-170d-49ed-8576-1ab42348db03)

**Comment by Roei639** [comment]
Yes, I can turn off the guest network in the router settings.
I restarted the router and the integration and it did not solve the problem.
I have attached diagnostics
Tank's

**Comment by Vaskivskyi** [comment]
Sorry, should have explained better. The `Download diagnostics` button should allow you to save diagnostics as a txt file. Please, upload it here as a file or send the file to me at Yevhenii@Vaskivskyi.com

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/b59b639b-98e7-40f3-a001-594dbafcc962)

**Comment by Roei639** [comment]
txt file is attached
I also sent you an email

[config_entry-asusrouter-e3d16920a2d6d99f7836bbbbd4c625cf.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/12330033/config_entry-asusrouter-e3d16920a2d6d99f7836bbbbd4c625cf.json.txt)

**Comment by Roei639** [comment]
> Sorry, should have explained better. The `Download diagnostics` button should allow you to save diagnostics as a txt file. Please, upload it here as a file or send the file to me at [Yevhenii@Vaskivskyi.com](mailto:Yevhenii@Vaskivskyi.com)
> 
> ![image](https://user-images.githubusercontent.com/6554415/260314804-b59b639b-98e7-40f3-a001-594dbafcc962.png)

Waiting for a reply
thanks

**Comment by Roei639** [comment]
@Vaskivskyi   ??

**Comment by Vaskivskyi** [comment]
Hello. I'm currently still working on the issue. Sorry for taking so long

**Comment by Vaskivskyi** [comment]
Hello, can you check the new versions `0.23.0+`?

**Comment by Roei639** [comment]
Yes, working.  
Thank you

**Comment by Vaskivskyi** [comment]
Great! 👍🏻
