### ISSUE TITLE
[Feature] Binary Sensor to show the status for both primary & secondary WAN for Dual WAN Setup

### ISSUE THREAD

**Issue by chandar-github** [Vaskivskyi/ha-asusrouter#603]
### The problem

Expecting a binary Sensor to show the WAN online/offline Status for both Primary & Secondary WAN for Dual WAN setup
Expected Device: ASUS RT-68U.
firmware: AsusWRT-Merlin

### Specific device(s)?

Yes

### Firmware type

Yes

**Comment by sesardelaisla** [comment]
I also support this request. However, in my case it is for model RT-AC87U (Merlin). Thanks!

**Comment by Vaskivskyi** [comment]
Hello, please check the new beta release `0.24.0b0` for the new functionality. The stable version will be released later this week.
