### ISSUE TITLE
RT-AX88U sometimes 2.4 GHz radio temperature detected at 76°C

### ISSUE THREAD

**Issue by GitHubGio70** [Vaskivskyi/ha-asusrouter#606]
### The problem

the temperature of the 2.4 Ghz radio sometimes, after a few hours or a few minutes, several times a day (10 times or more), in a completely random way, indicates for a scan time, memorized by HA, the fixed temperature value at 76°C, then in the next cycle it returns to the real value (generally around 40°C). I've tried changing the scan rate, but so far to no avail. All other sensors are correctly detected.

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/67016464/96cdf23b-b923-4ab6-a2e5-7d4dced361d8)

### Your device model

RT-AX88U

### Firmware type

Merlin

### Firmware version

388.2_2

### Integration version with the issue

    "asusrouter": { "version": "0.21.1",  "requirements": [ asusrouter==0.20.3"

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.7.1

**Comment by GitHubGio70** [comment]
Now the temperature of the 2.4 Ghz radio sometimes gives 64°C or 76°C randomly

![39 - 76](https://github.com/Vaskivskyi/ha-asusrouter/assets/67016464/b6530223-abb0-4e5a-b212-f4272a55b2e4)

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the late reply.

Can you please check, that your Merlin web UI does not have such issues?

I have tested an RT-AX88U with the same FW version but didn't notice any large jumps in the temperature values as in your case. Data parsing from the device seems to work well. So it would be nice to make sure, this is not a problem of reporting by the device itself

**Comment by GitHubGio70** [comment]
HI Vaskivskyi,

 

sorry for the delay in responding, but I took some time to better verify the anomaly which started on April 14th and disappeared (maybe definitely??) on its own on August 8th, without me doing any targeted intervention, nor firmware upgrades or configuration changes on the router or in home assistant. Below the trend. I have no explanations about it.

 



 

Thanks for the support!

Regards

Giorgio

 

Da: Yevhenii Vaskivskyi ***@***.***> 
Inviato: domenica 13 agosto 2023 18:37
A: Vaskivskyi/ha-asusrouter ***@***.***>
Cc: GitHubGio70 ***@***.***>; Author ***@***.***>
Oggetto: Re: [Vaskivskyi/ha-asusrouter] RT-AX88U sometimes 2.4 GHz radio temperature detected at 76°C (Issue #606)

 

Hello. Sorry for the late reply.

Can you please check, that your Merlin web UI does not have such issues?

I have tested an RT-AX88U with the same FW version but didn't notice any large jumps in the temperature values as in your case. Data parsing from the device seems to work well. So it would be nice to make sure, this is not a problem of reporting by the device itself

**Comment by Vaskivskyi** [comment]
It's great that the issue has been solved by itself. Since I didn't find any issue in the way temperature is parsed and also no one else reported a similar issue, I will close this one. Hope, AsusRouter will be working well for you
