### ISSUE TITLE
[Device support] 

### ISSUE THREAD

**Issue by surfdef** [Vaskivskyi/ha-asusrouter#610]
### Anything you want to mention?

The integration is complete except for a few more detailed entities but it works well and with another router in Mesh, RT-AX56U.
This last Router mesh used firmware Merlin 3.0.0.4.388

### Your device model

RT-AX86U PRO

### Firmware type

Stock

### Firmware version

3.0.0.4.388.23565

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Thanks for your report :+1:

Some more features are coming to AsusRouter soon. But if you have some exact suggestions on the new / improved features, please open a feature request
