### ISSUE TITLE
[Bug] Error setting up integration

### ISSUE THREAD

**Issue by alexstaal** [Vaskivskyi/ha-asusrouter#611]
### The problem

Cannot setup the integration due to an error

### Your device model

RT-AX58U

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.2_0

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

core-2023.8.4

### Is there anything useful in the logs?

```txt
Unknown error of type '<class 'UnicodeDecodeError'>' during connection to `192.168.50.1`: 'utf-8' codec can't decode byte 0xf4 in position 2121: invalid continuation byte
Unknown error of type '<class 'aiohttp.client_exceptions.ClientResponseError'>' during connection to `192.168.50.1`: 400, message="Expected HTTP/:\n\n b'SSH-2.0-dropbear\\r'\n ^", url=URL('http://192.168.50.1:22/login.cgi')
Unknown error of type '<class 'asusrouter.error.AsusRouterSSLError'>' during connection to `192.168.50.1`: None
```

**Comment by Vaskivskyi** [comment]
Hello. It looks like you are trying to connect on the `22` port (SSH).

AsusRouter is using an HTTP(S) connection to the device (the way web UI or the mobile app from Asus works). You need to select the correct port (or don't specify any by setting it to `0` in the integration settings). The default ports are 80 for HTTP and 8443 for HTTPS (SSL) connection.

**Comment by alexstaal** [comment]
Apologies, changed it to default. Now getting the following error:
`Unknown error of type '<class 'UnicodeDecodeError'>' during connection to `192.168.50.1`: 'utf-8' codec can't decode byte 0xf4 in position 2121: invalid continuation byte`

**Comment by Vaskivskyi** [comment]
Please, check whether you are still experiencing this issue with the latest beta release `0.23.0b1`. You need the HACS option `Show beta releases` to be set in the settings for AsusRouter repository to be able to install a beta version

**Comment by alexstaal** [comment]
Updated to the latest beta release. Unfortunately no change, i'm still getting the same issue

`Unknown error of type '<class 'UnicodeDecodeError'>' during connection to `192.168.50.1`: 'utf-8' codec can't decode byte 0xf4 in position 2110: invalid continuation byte`

By the way, in the meantime, i also updated to home assistant version 2023.10.5

**Comment by Vaskivskyi** [comment]
Hey, with `0.23.0b3` you should be able to set up the integration since it won't be blocked anymore by the decoding error (but some data will be missing from the integration). The HA log will show you a detailed error as well as the data which causes the issue. You can send it here or via email in a single file to Yevhenii@Vaskivskyi.com - then we can try to solve the issue itself, so you'll have access to all the data. When sending, please, make sure you are not adding any formatting to the log output

**Comment by Vaskivskyi** [comment]
One more chance on `0.23.0b4`

**Comment by alexstaal** [comment]
Setting up the integration works now! 

Getting 2 issues:

First:
`Unable to decode json content with exception `Invalid control character at: line 2 column 970 (char 2105)`. Please, copy this end fill in a bug report: {"get_onboardinglist":[{}],"get_cfg_clientlist":[[{"alias":"Home","model_name":"RT-AX58U","ui_model_name":"RT-AX58U","icon_model_name":"","product_id":"RT-AX58U","frs_model_name":"","fwver":"3.0.0.4.388.2_0","newfwver":"3.0.0.4.388_4_0","ip":"192.168.50.1","mac":"A8:5E:45:E8:6A:F0","online":"1","ap2g":"A8:5E:45:E8:6A:F0","ap5g":"A8:5E:45:E8:6A:F4","ap5g1":"","apdwb":"","ap6g":"","wired_mac":["F0:2F:74:6D:46:10"],"pap2g":"","rssi2g":"","pap5g":"","rssi5g":"","pap6g":"","rssi6g":"","level":"0","re_path":"0","config":{},"sta2g":"","sta5g":"","sta6g":"","capability":{"3":3,"2":1,"16":1,"17":1,"19":1,"20":1,"1":31,"4":12159,"22":3,"23":1},"ap2g_ssid":"Can't touch this WiFi!","ap5g_ssid":"Can't touch this WiFi!_5G","ap5g1_ssid":"","ap6g_ssid":"","pap2g_ssid":"","pap5g_ssid":"","pap6g_ssid":"","wired_port":{},"plc_status":{},"band_num":"2","tcode":"EU/01","misc_info":{"2":"1"},"ap2g_fh":"A8:5E:45:E8:6A:F0","ap5g_fh":"A8:5E:45:E8:6A:F4","ap5g1_fh":"","ap6g_fh":"","ap2g_ssid_fh":"Can't touch this WiFi!","ap5g_ssid_fh":"Can't touch this WiFi!_5G","ap5g1_ssid_fh":"","ap6g_ssid_fh":"","band_info":{"0":{"unit":0},"1":{"unit":1}}}, {"alias":"Office","model_name":"ZenWiFi_XD4","ui_model_name":"ZenWiFi AX Mini","icon_model_name":"ZenWiFi_XD4_black","product_id":"","frs_model_name":"","fwver":"3.0.0.4.386_39507-g13a3d7d","newfwver":"","ip":"192.168.50.64","mac":"F0:2F:74:6D:46:10","online":"1","ap2g":"","ap5g":"","ap5g1":"","apdwb":"","ap6g":"","wired_mac":[],"pap2g":"","rssi2g":"","pap5g":"","rssi5g":"","pap6g":"","rssi6g":"","level":"0","re_path":"1","config":{"misc":{"cfg_alias":"Office"},"backhalctrl":{"amas_ethernet":"3"},"ctrl_led":{"led_val":"1"},"prefer_ap":{"amas_wlc_target_bssid":"<A8:5E:45:E8:6A:F0","amas_wlc0_target_bssid":"<A8:5E:45:E8:6A:F0","amas_wlc1_target_bssid":"<A8:5E:45:E8:6A:F4"}},"sta2g":"F0:2F:74:6D:46:11","sta5g":"F0:2F:74:6D:46:14","sta6g":"","capability":{"3":1,"2":1,"16":1,"17":1,"19":1,"20":1,"1":4,"4":30,"6":1,"7":1,"9":123,"10":123,"12":5499,"13":5499,"15":1,"21":"WAN:41","23":1},"ap2g_ssid":"","ap5g_ssid":"","ap5g1_ssid":"","ap6g_ssid":"","pap2g_ssid":"L hL_","pap5g_ssid":"L hL1_","pap6g_ssid":"","wired_port":{"wan_port_count":0,"wan_port":{}},"plc_status":{},"band_num":"2","tcode":"EU/01","misc_info":{},"ap2g_fh":"","ap5g_fh":"","ap5g1_fh":"","ap6g_fh":"","ap2g_ssid_fh":"","ap5g_ssid_fh":"","ap5g1_ssid_fh":"","ap6g_ssid_fh":"","band_info":{"0":{"unit":0},"1":{"unit":1}}}, {"alias":"Living Room","model_name":"ZenWiFi_XD4","ui_model_name":"ZenWiFi AX Mini","icon_model_name":"ZenWiFi_XD4_black","product_id":"","frs_model_name":"","fwver":"3.0.0.4.386_39507-g13a3d7d","newfwver":"","ip":"192.168.50.241","mac":"F0:2F:74:6D:46:00","online":"0","ap2g":"","ap5g":"","ap5g1":"","apdwb":"","ap6g":"","wired_mac":[],"pap2g":"","rssi2g":"","pap5g":"","rssi5g":"","pap6g":"","rssi6g":"","level":"0","re_path":"1","config":{"misc":{"cfg_alias":"Living Room"},"backhalctrl":{"amas_ethernet":"3"},"ctrl_led":{"led_val":"1"},"prefer_ap":{"amas_wlc_target_bssid":"<A8:5E:45:E8:6A:F0","amas_wlc0_target_bssid":"<A8:5E:45:E8:6A:F0","amas_wlc1_target_bssid":"<A8:5E:45:E8:6A:F4"}},"sta2g":"F0:2F:74:6D:46:01","sta5g":"F0:2F:74:6D:46:04","sta6g":"","capability":{"3":1,"2":1,"16":1,"17":1,"19":1,"20":1,"1":4,"4":30,"6":1,"7":1,"9":123,"10":123,"12":5499,"13":5499,"15":1,"21":"WAN:41","23":1},"ap2g_ssid":"","ap5g_ssid":"","ap5g1_ssid":"","ap6g_ssid":"","pap2g_ssid":"\\\" x\\_","pap5g_ssid":"\\\" x\\1_","pap6g_ssid":"","wired_port":{},"plc_status":{},"band_num":"2","tcode":"EU/01","misc_info":{},"ap2g_fh":"","ap5g_fh":"","ap5g1_fh":"","ap6g_fh":"","ap2g_ssid_fh":"","ap5g_ssid_fh":"","ap5g1_ssid_fh":"","ap6g_ssid_fh":"","band_info":{"0":{"unit":0},"1":{"unit":1}}}]],"get_onboardingstatus":[{"cfg_obstatus":"1","cfg_obresult":"","cfg_newre":"","cfg_wifi_quality":"-65","cfg_obstart":"","cfg_obcurrent":"1698835101","cfg_obtimeout":"","cfg_obmodel":"","cfg_ui_obmodel":"","cfg_obrssi":"-40","cfg_obcount":"2","cfg_obreboottime":"","cfg_obstage":"0","cfg_obfailresult":"0","cfg_re_maxnum":"9","cfg_recount":"2","cfg_ready":"1"}],"get_wclientlist":[{"F0:2F:74:6D:46:00":{"2G":[]},"A8:5E:45:E8:6A:F0":{"2G":["48:0B:B2:5A:B3:EF","1C:53:F9:CE:06:E5"],"5G":["1C:53:F9:21:8E:61"]},"F0:2F:74:6D:46:10":{"2G":["54:60:09:39:0C:92","7C:D9:5C:0C:3D:55","44:CB:8B:5F:97:40"],"5G":["7C:D9:5C:66:36:D5","14:C1:4E:72:F8:9F"]}}],"get_wiredclientlist":[{ "A8:5E:45:E8:6A:F0": [ "74:C6:3B:9F:14:AF", "DC:A6:32:DB:85:99", "EC:71:DB:B3:0D:8F", "EC:B5:FA:20:AC:63", "F8:F1:E6:63:84:39" ] }],"get_allclientlist":[{"F0:2F:74:6D:46:00":{"2G":{"7C:D9:5C:0C:3D:55":{"ip":"192.168.50.119","rssi":"-61"},"44:CB:8B:5F:97:40":{"ip":"192.168.50.83","rssi":"-45"},"DC:68:EB:10:ED:8A":{"ip":"192.168.50.19","rssi":"-53"},"E0:5A:1B:AC:4A:B4":{"ip":"192.168.50.163","rssi":"-58"}}},"A8:5E:45:E8:6A:F0":{"2G":{"48:0B:B2:5A:B3:EF":{"ip":"192.168.50.236","rssi":"-75"},"1C:53:F9:CE:06:E5":{"ip":"192.168.50.124","rssi":"-32"}},"5G":{"1C:53:F9:21:8E:61":{"ip":"192.168.50.147","rssi":"-63"}},"wired_mac":{"14:C1:4E:72:F8:9F":{"ip":"192.168.50.208"},"44:CB:8B:5F:97:40":{"ip":"192.168.50.74"},"54:60:09:39:0C:92":{"ip":"192.168.50.251"},"74:C6:3B:9F:14:AF":{"ip":"192.168.50.11"},"7C:D9:5C:0C:3D:55":{"ip":"192.168.50.16"},"7C:D9:5C:66:36:D5":{"ip":"192.168.50.71"},"DC:A6:32:DB:85:99":{"ip":"192.168.50.99"},"EC:71:DB:B3:0D:8F":{"ip":"192.168.50.114"},"EC:B5:FA:20:AC:63":{"ip":"192.168.50.225"},"F0:2F:74:6D:46:00":{"ip":"192.168.50.241"},"F0:2F:74:6D:46:10":{"ip":"192.168.50.64"}}},"F0:2F:74:6D:46:10":{"2G":{"54:60:09:39:0C:92":{"ip":"192.168.50.251","rssi":"-48"},"7C:D9:5C:0C:3D:55":{"ip":"192.168.50.16","rssi":"-54"},"44:CB:8B:5F:97:40":{"ip":"192.168.50.74","rssi":"-43"}},"5G":{"7C:D9:5C:66:36:D5":{"ip":"192.168.50.69","rssi":"-71"},"14:C1:4E:72:F8:9F":{"ip":"192.168.50.208","rssi":"-56"}}}}],"cfg_note":"3","cfg_obre":""}`

Second:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 342, in setup
    await self.update_nodes()
  File "/config/custom_components/asusrouter/router.py", line 538, in update_nodes
    aimesh = await self.bridge.async_get_aimesh_nodes()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 272, in async_get_aimesh_nodes
    return await self._get_data(AsusData.AIMESH)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 261, in _get_data
    raw = await self.api.async_get_data(datatype, force=force)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 459, in async_get_data
    process(
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/__init__.py", line 113, in process
    return submodule.process(data)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/onboarding.py", line 58, in process
    client_list = data["get_allclientlist"][0]
                  ~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'get_allclientlist'`

**Comment by alexstaal** [comment]
After reading the other issue, changing the operation mode to aimesh seems to have resolved the issue!

**Comment by Vaskivskyi** [comment]
You mean `AiMesh node`? That does not actually solve the issue, rather avoids it. In this mode, some functionality is disabled.

In your case, the issue itself is in these parameters of your Living room node:

```JSON
"pap2g_ssid": "\\�\" x\\_",
"pap5g_ssid": "\\�\" x\\1_",
```

These 2 values should be SSIDs for the parent node. Unfortunately, I don't have access to AiMesh to tell you more
