### ISSUE TITLE
[Device support]  TUF-AX3000 V2

### ISSUE THREAD

**Issue by szwarx** [Vaskivskyi/ha-asusrouter#614]
### Anything you want to mention?

Hello
Please add support TUF-AX3000 V2

### Your device model

 TUF-AX3000 V2

### Firmware type

Stock

### Firmware version

3.0.0.4.388_23785

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello,

Thanks for your report. The device will be added
