### ISSUE TITLE
[Feature] Support data_size, data_rate device classes and native_unit_of_measurement properties for sensors.

### ISSUE THREAD

**Issue by jazzyisj** [Vaskivskyi/ha-asusrouter#615]
### The problem

Data speed and data size sensors (upload/download) have not been assigned device clases or the native_unit_of_measurement property meaning the user cannot select their preferred unit of measurement in the UI.

https://developers.home-assistant.io/docs/core/entity/sensor/#properties
https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes

### Specific device(s)?

None

### Firmware type

None

**Comment by Vaskivskyi** [comment]
This feature will be available in the next release. Thanks for your feedback! :+1:
