### ISSUE TITLE
Device Tracker RSSI Stuck [Bug] 

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#619]
### The problem

I have problem after few hours device tracker attribut rssi stucked, only help me reload integration.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/42905545/70baee8b-a200-48a2-8d41-e09fe25780c0)

### Your device model

*************

### Firmware type

Stock

### Firmware version

*****************

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.9.2

**Comment by Vaskivskyi** [comment]
Hello.

Device tracker functionality is being actively worked on

**Comment by jata1** [comment]
@Vaskivskyi - just wanted to say thanks for all the great work you are doing on this project. I have the custom integration and I am running latest beta. I have a similar issue in that all my tracked devices report they are home even when they are not connected to the wifi. If I check the attributes for these devices I see that the 'connected' attribute continues to update even when the device is not connected and other attributes such as rssi are also populated. Can you just confirm that this is a related issue or should I create a new issue?

**Comment by Vaskivskyi** [comment]
Hey, @jata1,

It's better to add to issue #570 - this one is general for the device tracking problems. Please, post there your device model and FW version. Also, if you know a way to reproduce the issue with trackers without the need to just wait for some time that they stuck by themself - that would also help :+1:

**Comment by milandzuris** [comment]
> @milandzuris, can you please check whether the issue persists with the new versions `0.23.0+`?

for now looks it work im give some time to verify
