### ISSUE TITLE
GT-AX6000 [Device support] 

### ISSUE THREAD

**Issue by EstSoft87** [Vaskivskyi/ha-asusrouter#620]
### Anything you want to mention?

Fully supported, but  there is an issue with the firmware check update!

I'm getting every time this notify:

GT-AX6000 Firmware update
Newest version is 3.0.0.4.388.23285_g5068da5
Installed version is 3.0.0.6.102.21514_g9affda2_136-g5d23c

Latest one is the 3.0.0.6 with VLAN Integration.

### Your device model

GT-AX6000

### Firmware type

Stock

### Firmware version

3.0.0.6.102.21514_g9affda2_136-g5d23c

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello,

Thanks for your report. The firmware issue will be fixed in the next release (#605)

**Comment by Vaskivskyi** [comment]
The issue should be fixed in the latest [0.23.0b0](https://github.com/Vaskivskyi/ha-asusrouter/releases/tag/0.23.0b0) release
