### ISSUE TITLE
[Feature] Block status of devices

### ISSUE THREAD

**Issue by poudenes** [Vaskivskyi/ha-asusrouter#622]
### The problem

Would be nice to see also the block status of devices. Some devices I have blocked for internet access.
I have a card that repeat some information of all my devices and would be nice to see also this status

### Specific device(s)?

None

### Firmware type

None

**Comment by Vaskivskyi** [comment]
Hello. Thanks for your feedback!

Do you mean something similar to the parental control rules listed in the `parental_control` switch/binary sensor? Please, check the attribute `list` of one of those entities. It provides `mac`, `name` of the device and the `type` of blocking (`block`, `time`, `disabled`)

**Comment by Vaskivskyi** [comment]
With `0.27.0` you now have switch entities for each parental control rule. They can also be used for monitoring the state
