### ISSUE TITLE
2023.10.0b3 [Bug] 

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#623]
### The problem

Stop Working Integration

### Your device model

*

### Firmware type

Stock

### Firmware version

*

### Integration version with the issue

*

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.10.0b3

**Comment by Vaskivskyi** [comment]
Hello. Can you please provide a bit more info on the issue?

I have tested the mentioned version of HA, but did not notice any new issue with the current version of the integration
