### ISSUE TITLE
[Feature] Inlang implementation

### ISSUE THREAD

**Issue by Vaskivskyi** [Vaskivskyi/ha-asusrouter#633]
### The problem

I would like to implement Inlang support as was suggested in #590.

Since, apparently, the way it works has changed a lot since the original PR was suggested, I'd like to get help from the author @felixhaeberle if possible to finish the implementation.

Thanks in advance!

### Specific device(s)?

None

### Firmware type

None

**Comment by felixhaeberle** [comment]
@Vaskivskyi sure! will provide a follow-up PR tomorrow.
