### ISSUE TITLE
[Bug] Mark beta releases as "pre-release" in GitHub

### ISSUE THREAD

**Issue by ScottG489** [Vaskivskyi/ha-asusrouter#645]
### The problem

I believe when you make a GitHub release and check "Set as a pre-release" it will mark it as a beta release in HACS. This is important because it will then only show up for users who have opted to download beta releases.

It's been a while since I've published a beta in HACS, so correct me if I'm wrong on this, but this is how I recall it working.

### Your device model

N/A

### Firmware type

Stock

### Firmware version

N/A

### Integration version with the issue

N/A

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.10.5

**Comment by Vaskivskyi** [comment]
Hello. Thanks for the information :+1: I have marked both betas as pre-release and checked it. It seems to work as you described
