### ISSUE TITLE
[Bug] "Failed to set up" with HA 2023.10.05

### ISSUE THREAD

**Issue by sjbarkey** [Vaskivskyi/ha-asusrouter#659]
### The problem

After updating to 0.23.0, the AsusRouter integration shows "Failed to set up" and the entities for the router, provided by the integration, are all listed as "unavailable".

### Your device model

RT-AC87u

### Firmware type

Merlin

### Firmware version

384.13_10

### Integration version with the issue

0.23.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Supervisor 2023.10.01 and OS 11.1

### Is there anything useful in the logs?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 1:19:22 PM (1 occurrences)
Last logged: 1:19:22 PM

Error setting up entry 192.168.0.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 345, in setup
    await self.update_clients()
  File "/config/custom_components/asusrouter/router.py", line 485, in update_clients
    self.update_latest_connected()
  File "/config/custom_components/asusrouter/router.py", line 530, in update_latest_connected
    self._latest_connected = new_list[-1].get(CONNECTED)
                             ~~~~~~~~^^^^
IndexError: list index out of range
```

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the issue you are experiencing. It will be fixed in PR #660 now and the fix will become available with the next release tomorrow (up to 24 hours from now)
