### ISSUE TITLE
[Bug] Multiple up/down states swapped

### ISSUE THREAD

**Issue by Rembock** [Vaskivskyi/ha-asusrouter#676]
### The problem

Multiple up/down states seem to be swapped around.
![Screenshot 2023-11-05 042429](https://github.com/Vaskivskyi/ha-asusrouter/assets/18113225/f52cf268-ff62-4d16-9aee-54caa7d8878b)

### Your device model

RT-AC58U

### Firmware type

Stock

### Firmware version

3.0.0.4.382_52134

### Integration version with the issue

0.23.4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.10.5

**Comment by Vaskivskyi** [comment]
Please, consider, that `down` / `up` is relative to the router and not to the clients.

If you are downloading a movie from your phone, this will be `WAN Download` + e.g. `5 GHz Upload` for your router.

If you still think, the values are wrong, let's continue troubleshooting.

**Comment by Rembock** [comment]
No need, I'll turn the values around. Thanks for the explanation, was searching for a reason why the values are reversed.

**Comment by Vaskivskyi** [comment]
👍🏻
