### ISSUE TITLE
[Bug] CPU data for one router is switching between two routers.

### ISSUE THREAD

**Issue by Cosik** [Vaskivskyi/ha-asusrouter#683]
### The problem

I have two routers configured in HA. With latest version I noticed for example that temperature for one device is switching between it value and value from other router. But when I look now at graphs I see that problem appear already earlier.
<img width="1145" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/1255379/d1b7baba-5df4-44c1-935b-7d1c04a2a79a">

If you need any additional data please write which one and were to get it.

### Your device model

RT-AX55, TUF-AX5400

### Firmware type

Stock

### Firmware version

 3.0.0.4.386.52041_g0c3a69e, 3.0.0.4.388.23285_g5068da5

### Integration version with the issue

0.23.6

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.10.0

### Diagnostics information

[home-assistant_2023-11-06T07-46-29.886Z.log](https://github.com/Vaskivskyi/ha-asusrouter/files/13263882/home-assistant_2023-11-06T07-46-29.886Z.log)

**Comment by Vaskivskyi** [comment]
Hello. Sorry to hear you are experiencing issues with the latest versions.

Can you please let me know the following:
- Do you have one device set up as a router and one as an AiMesh node in the integration settings?

Also, please, try to check:
- If you disable any of the two integration setups, will the other one work as you expected? Try this with both combinations.
- Is there anything similar in other sensors? E.g. network speed / traffic, RAM etc

**Comment by Cosik** [comment]
`Do you have one device set up as a router and one as an AiMesh node in the integration settings?`
One is router second as AP to extend range. 
<img width="507" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/1255379/09bc9e71-0799-4d9a-98db-778a8eea0ea9">
<img width="208" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/1255379/a1b41227-21f7-41ad-9404-95197ac8d22d">
<img width="214" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/1255379/c677af56-e47c-4bce-bca8-54c011d3174a">

`If you disable any of the two integration setups, will the other one work as you expected? Try this with both combinations.`
When I disable any of router it work correctly

`Is there anything similar in other sensors? E.g. network speed / traffic, RAM etc`
I'm sure that at least RAM, CPU and temperature are the same. Other stuff is not provided or Unavailable.

**Comment by Vaskivskyi** [comment]
@Cosik, Please, check version `0.23.7`and let me know whether the issue persists

**Comment by Cosik** [comment]
@Vaskivskyi thanks, but problem is still visible.

**Comment by Vaskivskyi** [comment]
Sure. Will continue the search

**Comment by Vaskivskyi** [comment]
The issue with mixing data between instances is fixed in version `0.26.0`. Please, check it out. In case you are still experiencing such troubles, reopen this issue or open a new one

**Comment by Cosik** [comment]
@Vaskivskyi it is working now correctly, good job, thank you.
