### ISSUE TITLE
[Bug] Status-LEDs on AP start flashing randomly while configured "off"

### ISSUE THREAD

**Issue by 5a5cha** [Vaskivskyi/ha-asusrouter#709]
### The problem

I recognized a random flashing of the Status-LEDs on the AP.
All LEDs are randomly flashing. Not the same time. One by one.

LEDs are configured as "off" in the Web-UI.

After deactivating the Integration the LEDs remain off.

### Your device model

GT-AX11000

### Firmware type

Merlin

### Firmware version

3004.388.4

### Integration version with the issue

0.24.0b2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.11.2

**Comment by Vaskivskyi** [comment]
Weird, they are doing it one by one and not all at a time, but might be related to #710. If so, this will be fixed as soon as possible

**Comment by Vaskivskyi** [comment]
The other LED issue should be fixed in `0.24.0b3`. Please, check whether the LEDs work as expected for you

**Comment by 5a5cha** [comment]
Bug seems to be fixed.
With 0b3 I'm able to control the LED via light entity and the random flashing is gone, too.

**Comment by Vaskivskyi** [comment]
Please, check your AP logs via Web UI. If LEDs are controlled by integration (the way Asus is doing this), you would see something like this:

```
Nov 20 20:53:45 rc_service: cfg_server 1300:notify_rc start_ctrl_led
```

Please, let me know about your findings.

Merlin does not use the Asus way of handling LEDs (due to historical reasons), and the two ways can turn on and off LEDs independently if using Merlin. But neither should lead to the flashing of LEDs or their switching one-by-one

P.S. Also, please explain in more detail what you mean by flashing - do LEDs turn on - off in terms of seconds? Or do they blink (like the LED on any communication interface showing data transfer)

**Comment by 5a5cha** [comment]
The AP is in AIMesh-Mode and act as an AIMesh node I don't know how to get the log of the node.
Log of the Router itself doesn't show anything like led.

It comes definitely from the integration. After deactivating the integration of the node the leds are off all the time.

uploaded a short video. explains best :-)
https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/1c8b3575-1b1b-4e2d-a63a-f7dd2728439e

**Comment by Vaskivskyi** [comment]
This is extra weird. There is no possibility to control individual LEDs from the API point of view.

You can also check the debug logs of the AsusRouter library through the HA logs. You need lines similar to:

```
2023-11-21 08:14:33.347 DEBUG (MainThread) [asusrouter.modules.service] Service `start_ctrl_led` run with arguments `{'led_val': 1, 'action_mode': 'apply'}`. Result: `{'modify': '1', 'run_service': 'start_ctrl_led'}`
```

If there are many lines like this, please save the log file after some time of "blinking" LEDs and send me via Yevhenii@Vaskivskyi.com. Keep in mind, that the debug log might contain MAC and IP addresses of your devices, as well as device names, so you might not want to publish it here.

If there are no such lines, but the debug logs of both AsusRouter integration and library are present, also send it - anyway we need to find out what happens.

I suppose you are using the AiMesh WebUI interface as an LED state indicator for this AP?

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/a2d1e222-a220-40fe-95a1-e1ab7be7b405)

**Comment by 5a5cha** [comment]
Ok, there are a lot of the following lines in the log file.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/4889d35e-9c89-40e5-ab96-b03ea6b85f8d)

Yes, i've set the LEDs to off in the WebUI.

**Comment by Vaskivskyi** [comment]
Please, check the latest release `0.24.2`

In case if the issue still persists, we would need a new log - there should be more info now in case something is going wrong in this part of the code

**Comment by 5a5cha** [comment]
So watching the LEDs while drinking a cup of coffee the LEDs stayed off.
