### ISSUE TITLE
[Bug] Logger: asusrouter.tools.readers

### ISSUE THREAD

**Issue by c7274864** [Vaskivskyi/ha-asusrouter#715]
### The problem

Hello

`Détails du journal (ERREUR)
Cette erreur provient d'une intégration personnalisée
Logger: asusrouter.tools.readers
Source: custom_components/asusrouter/bridge.py:507
Integration: AsusRouter ([documentation](https://asusrouter.vaskivskyi.com/), [issues](https://github.com/Vaskivskyi/ha-asusrouter/issues))
First occurred: 14:33:52 (1 occurrences)
Last logged: 14:33:52

Unable to decode json content with exception `Expecting property name enclosed in double quotes: line 2 column 1 (char 2)`. Please, copy this end fill in a bug report: { , "wgs_enable":"", "wgs_lanaccess":"", "wgs_addr":"", "wgs_port":"", "wgs_dns":"", "wgs_nat6":"", "wgs_psk":"", "wgs_alive":"", "wgs_priv":"", "wgs_pub":"", "wgs1_c1_enable":"", "wgs1_c1_name":"", "wgs1_c1_addr":"", "wgs1_c1_aips":"", "wgs1_c1_caips":"", "wgs1_c2_enable":"", "wgs1_c2_name":"", "wgs1_c2_addr":"", "wgs1_c2_aips":"", "wgs1_c2_caips":"", "wgs1_c3_enable":"", "wgs1_c3_name":"", "wgs1_c3_addr":"", "wgs1_c3_aips":"", "wgs1_c3_caips":"", "wgs1_c4_enable":"", "wgs1_c4_name":"", "wgs1_c4_addr":"", "wgs1_c4_aips":"", "wgs1_c4_caips":"", "wgs1_c5_enable":"", "wgs1_c5_name":"", "wgs1_c5_addr":"", "wgs1_c5_aips":"", "wgs1_c5_caips":"", "wgs1_c6_enable":"", "wgs1_c6_name":"", "wgs1_c6_addr":"", "wgs1_c6_aips":"", "wgs1_c6_caips":"", "wgs1_c7_enable":"", "wgs1_c7_name":"", "wgs1_c7_addr":"", "wgs1_c7_aips":"", "wgs1_c7_caips":"", "wgs1_c8_enable":"", "wgs1_c8_name":"", "wgs1_c8_addr":"", "wgs1_c8_aips":"", "wgs1_c8_caips":"", "wgs1_c9_enable":"", "wgs1_c9_name":"", "wgs1_c9_addr":"", "wgs1_c9_aips":"", "wgs1_c9_caips":"", "wgs1_c10_enable":"", "wgs1_c10_name":"", "wgs1_c10_addr":"", "wgs1_c10_aips":"", "wgs1_c10_caips":"" }`

### Your device model

RT-AC88U

### Firmware type

Merlin

### Firmware version

386.12_2

### Integration version with the issue

0.24.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.11.2

**Comment by Vaskivskyi** [comment]
Hello. Thanks for your report. This will be fixed as soon as possible.

Sorry for the inconvenience

**Comment by Vaskivskyi** [comment]
Please, check the new version `0.24.1` which is already available via HACS

**Comment by c7274864** [comment]
Hello

I install the new version and let you know

**Comment by Vaskivskyi** [comment]
In case if the issue was not solved, please, reopen this issue
