### ISSUE TITLE
[Bug] Wireless devices are shown as "wired"

### ISSUE THREAD

**Issue by JohnyR** [Vaskivskyi/ha-asusrouter#719]
### The problem

Wireless entities are being shown as `Connection Type = Wired`. Worked fine in `0.24.0b3`.

### Your device model

ZenWiFi ET8

### Firmware type

Stock

### Firmware version

3.0.0.4.388_23759

### Integration version with the issue

0.24.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.11.2

**Comment by Vaskivskyi** [comment]
@JohnyR, please, check the latest release `0.24.2` - the issue should be fixed
