### ISSUE TITLE
[Bug] rx / tx speed attributes missing

### ISSUE THREAD

**Issue by JohnyR** [Vaskivskyi/ha-asusrouter#728]
### The problem

It seems like the RX and TX speed attributes become unavailable after a while. The devices are still connected, but the attributes are null.

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/967548/62845b0d-2342-4bea-8dd4-cbc8bce955fb)
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/967548/75741c8c-aee2-49cd-8654-dd9eecee6d8f)

### Your device model

ZenWiFi ET8

### Firmware type

Stock

### Firmware version

3.0.0.4.388_23759

### Integration version with the issue

0.25.0b0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.11.3

**Comment by Vaskivskyi** [comment]
Hi. Sorry for the delay.

Did it work differently before the `0.25.0b0` update?

Does it happen to some specific devices or any devices? As I see from your snapshot, it was only for 2.4 GHz devices. Did it happen to 5 GHz or 6 GHz ones?

**Comment by JohnyR** [comment]
@Vaskivskyi, I believe that the nulls are coming from the router itself. I logged into the web UI and noticed that many of these devices had `-` for rx/tx values. I don't think it's an issue with your integration. Safe to close, imo.

**Comment by Vaskivskyi** [comment]
Yes, if the Web UI is showing the same behaviour, unfortunately, it cannot be improved by the integration. Good, that this was sorted
