### ISSUE TITLE
Device Tracker Remove[Bug] 

### ISSUE THREAD

**Issue by milandzuris** [Vaskivskyi/ha-asusrouter#729]
### The problem

Hi i dont have device tracker remove service in HA
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/42905545/bf17484b-4a29-4665-819e-e876d34603a3)
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/42905545/96cabc54-8fed-474b-bf9b-9e93a3c5c792)

### Your device model

*

### Firmware type

Stock

### Firmware version

*

### Integration version with the issue

*

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.12.0b1

**Comment by Vaskivskyi** [comment]
Hello. The service was temporarily removed in `0.23.0` due to the compatibility issues with the new backend. It will be added back soon.

I am sorry that docs do not reflect the correct state as for present
