### ISSUE TITLE
[Translation] Missing pt-BR translation

### ISSUE THREAD

**Issue by Vaskivskyi** [Vaskivskyi/ha-asusrouter#73]
Hey, @LeandroIssa,

You have helped with pt-BR translations for the integration. Maybe you can help once more?

The current version of EN strings (https://github.com/Vaskivskyi/ha-asusrouter/blob/main/custom_components/asusrouter/translations/en.json) has all the values which would be needed for the next big release coming this weekend

**Comment by LeandroIssa** [comment]
I made a new translation with everything new!
I'm always available for whatever you need!

**Comment by Vaskivskyi** [comment]
Thanks!
