### ISSUE TITLE
[Bug] Available firmware update not reported correctly

### ISSUE THREAD

**Issue by 5a5cha** [Vaskivskyi/ha-asusrouter#732]
### The problem

In the WebUI the Alert Icon on the right top is flashing because of new firmware available.

Checking the admin page and it shows a new version.
Integration still reports "old" version as actual.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/21234719/9e153dc7-611c-4fa3-8b7c-748604511e61)

Firmware 388.5 is available since +19h. Last "reboot" of the complete HA Server was 25min ago due to a power issue.
So i expected the integration reports also 388.5 as new version.

### Your device model

GT-AX11000

### Firmware type

Merlin

### Firmware version

3004.388.4

### Integration version with the issue

0.24.2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.11.3

**Comment by Vaskivskyi** [comment]
Hello. Please, allow me some time to check this
