### ISSUE TITLE
ZenWiFi Pro ET12 works

### ISSUE THREAD

**Issue by PitHar** [Vaskivskyi/ha-asusrouter#742]
### Anything you want to mention?

As of version 0.26.0 the router is accessible in HA

### Your device model

ZenWiFi Pro ET12

### Firmware type

Stock

### Firmware version

3.0.0.4.388_23013

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello, thanks for your report. The model and FW version will be added to the supported devices list :+1:

**Comment by Vaskivskyi** [comment]
The device was added to the list. Thanks once more for your feedback!
