### ISSUE TITLE
[Bug] Blank Option in Config Entry

### ISSUE THREAD

**Issue by jazzyisj** [Vaskivskyi/ha-asusrouter#752]
### The problem

Blank entry in config dialog.

<img width="296" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/44064559/5f4631f0-92aa-48ae-9c2f-7b535eaafdcd">

### Your device model

RT-AX58U

### Firmware type

Stock

### Firmware version

3.0.0.4.388.23556_gfef4962

### Integration version with the issue

0.27.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

HAOS 2024.1.0b2

### Diagnostics information

[config_entry-asusrouter-be451b4c49c2176bee51cdba905ee5d4.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/13801705/config_entry-asusrouter-be451b4c49c2176bee51cdba905ee5d4.json.txt)

### Additional information

Not sure when this started, I've updated both HA and ASUS recently.

**Comment by Vaskivskyi** [comment]
Hello,

This is not a bug. Unfortunately, there is no `spacer` for the config flow and this was the only way to separate the `Save and Finish` option. I will check, whether there are any new features for config flow to make it look nicer

**Comment by Vaskivskyi** [comment]
Hey. I checked again and there is still no way to have a spacer. But I agree that it looks weird, so the empty option is now removed in the new version. Thanks for your feedback! :+1:

**Comment by jazzyisj** [comment]
Awesome.  Just curious though, wouldn't it make more sense to use a button for the "Save and Finish" option?
Here's an example from another integration (Balboa custom).

<img width="372" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/44064559/cb192c12-b2a0-4a25-af3d-bab70c85592e">
