### ISSUE TITLE
[Bug] Error while setting up asusrouter platform for switch

### ISSUE THREAD

**Issue by jazzyisj** [Vaskivskyi/ha-asusrouter#753]
### The problem

Error on startup.

```
ERROR (MainThread) [homeassistant.components.switch] Error while setting up asusrouter platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/asusrouter/switch.py", line 65, in async_setup_entry
    update_router()
  File "/config/custom_components/asusrouter/switch.py", line 59, in update_router
    add_entities(router, async_add_entities, tracked)
  File "/config/custom_components/asusrouter/switch.py", line 82, in add_entities
    new_tracked.append(ClientInternetSwitch(router, rule))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/switch.py", line 153, in __init__
    self._mac = format_mac(rule.mac)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 330, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
       ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

### Your device model

RT-AX58U

### Firmware type

Stock

### Firmware version

3.0.0.4.388.23556_gfef4962

### Integration version with the issue

0.27.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

HAOS 2024.1.0b2

### Diagnostics information

[config_entry-asusrouter-be451b4c49c2176bee51cdba905ee5d4.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/13801796/config_entry-asusrouter-be451b4c49c2176bee51cdba905ee5d4.json.txt)

### Additional information

I removed Asus Router, restarted HA, and reinstalled Asus Router to eliminate that as the issue.

**Comment by Vaskivskyi** [comment]
Do you have a parental control rule without a mac address?

**Comment by jazzyisj** [comment]
Parental controls disabled on both router and HA.

<img width="336" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/44064559/eb5ffc6a-da9c-4875-847f-738320c34df4">
<img width="296" alt="image" src="https://github.com/Vaskivskyi/ha-asusrouter/assets/44064559/7940a82d-6c92-4862-90c8-3f64ab926f67">

**Comment by Vaskivskyi** [comment]
Please, update to version `0.27.1`. Your issue should be solved now

Also, parental control rules are the ones set on the next tab. They are still saved in the device settings even if turned off. Apparently, one of the rules had issues with MAC address

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/b28ecbd5-c16b-469b-9bcc-c6ca58deee1d)

**Comment by jazzyisj** [comment]
There was a rule under time scheduling.  Must have been something that set up by default, I've never used that feature.  I've deleted it and also updated.  Error gone.  That was fast, I feel like I've had my own on call personal bug fixer today!  Asus Router keeps getting better and better! :-)

Happy New Year to you!
