### ISSUE TITLE
[Bug] Upload/Download for 2.4GHz reversed

### ISSUE THREAD

**Issue by Juddium** [Vaskivskyi/ha-asusrouter#757]
### The problem

It looks like the upload data (total and speed) and download data (total and speed) for 2.4GHz wireless is reversed - the actual upload speed is listed as the download speed, and the actual download speed is listed as the upload speed.

### Your device model

RT-AC88U

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.12_4

### Integration version with the issue

0.27.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.12.4

**Comment by Juddium** [comment]
After looking a little more, I realized this is just me misunderstanding what I was seeing. Apologies for opening a superfluous bug report.

**Comment by Vaskivskyi** [comment]
Hello. Not a problem 🙂 In case you will have any questions or issues with AsusRouter or your Asus device, feel free to ask
