### ISSUE TITLE
AsusRouter integration causing asus Web UI to show disconnected clients as connected 

### ISSUE THREAD

**Issue by jata1** [Vaskivskyi/ha-asusrouter#760]
### The problem

This issue could be related to the improvements that are currently being developed for device tracking in the asusrouter integration.

After installing the integration I have seen some clients show as connected in my asus web based UI.  

### Your device model

RT-AX86S

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.5

### Integration version with the issue

0.27.2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.12.4

### Is there anything useful in the logs?

```txt
will add later
```

### Diagnostics information

will add later

### Additional information

will add later

**Comment by jata1** [comment]
I am starting from a clean install of my entire asus network plus I have fully removed asusrouter integration from HA so I can start with a clean baseline. 

For the last 3 days router/network has been working fine with clients correctly displayed in the asus web UI. 

At this point asusrouter integration is not installed in my HA setup. 

Will add additional to this thread after I setup asusrouter integration to see if I can reproduce the issue.

**Comment by jata1** [comment]
First thing to note is that a number of non-asus devices are identified and there is no way to deselect... This is a different issue but thought I would share :-)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/23280705/d5fb0e95-5a89-4db5-8c40-4688fc93e3eb)

**Comment by Vaskivskyi** [comment]
The integration creates devices only for your router + AiMesh nodes.

Plus (only if set explicitly in the configs) for the clients with parental control rules set, so that entities for them are attached to devices and can be found easier (and are also merged with device trackers.

All others are a result of HA way of handling `device_trackers` - if there is already a device with the same MAC address by any other integration as the created `device_tracker` entity - they will be merged. It's not that AsusRouter creates them, but they are rather shown as provided by two integrations.

You will see such devices in the following way:

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/b0858a6c-fb52-4bd3-8289-acd8c106fdb8)

This behaviour cannot be changed from the integration side. Only if you disable device_tracking all together (so that AsusRouter won't create `device_tracker` entities at all)

**Comment by jata1** [comment]
Thanks but I do not have or want device tracking on my hue bridges or a IR remote blaster and these are the three additional devices that are identified when I install the integration. I have loads of other devices that are not identified and added like this so there is something weird with how this is working - but it's a different issue so let's park it for now

**Comment by jata1** [comment]
Looking at asus web UI (and mobile app) - there is an issue that I can reproduce easily so I hope we can work together to solve it

What I can see is this:
1. connected_devices entity in HA via asusrouter is working well. I can see my devices moving between nodes as expected
2. web and mobile app ui for device list is not updating and retains an out of date status/node for devices that moves between nodes
3. when devices are off the wifi network (away from home) then HA is updating correctly but asus gui does not update
4. logging on the router shows the client move (roam) as a result of rssi on the client (as expected) but the gui is not updated

Just now my wife and her two friends have gone out. I see their devices are correctly updated in HA in connected_devices and device_tracker (wife only as I don't track her friends lol) but all three are showing in the asus web gui and mobile app as here and connected

Below are the logs from my router (i know I should scrub mac addresses but we will need this info) from around the time my wife and her friends went away. Looks as expected i think but the issue is that the asus web gui and mobile app is not updated. 

`Jan  5 08:40:06 wlceventd: wlceventd_proc_event(685): eth6: Auth 5C:50:D9:BA:E1:B1, status: Successful (0), rssi:0
Jan  5 08:40:06 hostapd: eth6: STA 5c:50:d9:ba:e1:b1 IEEE 802.11: associated
Jan  5 08:40:06 wlceventd: wlceventd_proc_event(695): eth6: ReAssoc 5C:50:D9:BA:E1:B1, status: Successful (0), rssi:-59
Jan  5 08:40:06 hostapd: eth6: STA 5c:50:d9:ba:e1:b1 RADIUS: starting accounting session D711AEA434B4765D
Jan  5 08:40:06 hostapd: eth6: STA 5c:50:d9:ba:e1:b1 WPA: pairwise key handshake completed (RSN)
Jan  5 08:40:43 wlceventd: wlceventd_proc_event(685): eth6: Auth 42:96:F6:19:18:CD, status: Successful (0), rssi:0
Jan  5 08:40:43 hostapd: eth6: STA 42:96:f6:19:18:cd IEEE 802.11: associated
Jan  5 08:40:43 wlceventd: wlceventd_proc_event(695): eth6: ReAssoc 42:96:F6:19:18:CD, status: Successful (0), rssi:-54
Jan  5 08:40:43 hostapd: eth6: STA 42:96:f6:19:18:cd RADIUS: starting accounting session 52ACA2CBCDCCE211
Jan  5 08:40:43 hostapd: eth6: STA 42:96:f6:19:18:cd WPA: pairwise key handshake completed (RSN)
Jan  5 08:42:35 roamast: [EXAP]Deauth old sta in 1 0: 42:96:F6:19:18:CD
Jan  5 08:42:35 roamast: eth6: disconnect weak signal strength station [42:96:f6:19:18:cd]
Jan  5 08:42:35 hostapd: eth6: STA 42:96:f6:19:18:cd IEEE 802.11: disassociated
Jan  5 08:42:35 wlceventd: wlceventd_proc_event(645): eth6: Deauth_ind 42:96:F6:19:18:CD, status: 0, reason: Previous authentication no longer valid (2), rssi:-82
Jan  5 08:42:35 hostapd: eth6: STA 42:96:f6:19:18:cd IEEE 802.11: disassociated
Jan  5 08:42:35 wlceventd: wlceventd_proc_event(645): eth6: Deauth_ind 42:96:F6:19:18:CD, status: 0, reason: Previous authentication no longer valid (2), rssi:-82
Jan  5 08:42:35 wlceventd: wlceventd_proc_event(645): eth6: Deauth_ind 42:96:F6:19:18:CD, status: 0, reason: Disassociated because sending station is leaving (or has left) BSS (8), rssi:-82
Jan  5 08:42:35 roamast: eth6: remove client [42:96:f6:19:18:cd] from monitor list
Jan  5 08:42:35 hostapd: eth6: STA 42:96:f6:19:18:cd IEEE 802.11: disassociated
Jan  5 08:42:35 wlceventd: wlceventd_proc_event(645): eth6: Deauth_ind 42:96:F6:19:18:CD, status: 0, reason: Disassociated due to inactivity (4), rssi:-82
Jan  5 08:42:38 wlceventd: wlceventd_proc_event(662): eth6: Disassoc 42:96:F6:19:18:CD, status: 0, reason: Disassociated because sending station is leaving (or has left) BSS (8), rssi:0
Jan  5 08:42:38 hostapd: eth6: STA 42:96:f6:19:18:cd IEEE 802.11: disassociated
Jan  5 08:42:42 hostapd: eth6: STA 5c:50:d9:ba:e1:b1 IEEE 802.11: disassociated
Jan  5 08:42:43 roamast: [EXAP]Deauth old sta in 1 0: 5C:50:D9:BA:E1:B1
Jan  5 08:42:43 roamast: eth6: disconnect weak signal strength station [5c:50:d9:ba:e1:b1]
Jan  5 08:42:43 roamast: eth6: remove client [5c:50:d9:ba:e1:b1] from monitor list
Jan  5 08:42:48 roamast: determine candidate node [A8:5E:45:F1:5E:44](rssi: -45dbm) for client [F8:C3:CC:33:EA:C3](rssi: -66dbm from client)(rssi: -71dbm from ap) to roam
Jan  5 08:42:48 roamast: Roam a client [F8:C3:CC:33:EA:C3], status [0]
Jan  5 08:42:48 hostapd: eth6: STA f8:c3:cc:33:ea:c3 IEEE 802.11: disassociated
Jan  5 08:42:49 roamast: [EXAP]Deauth old sta in 1 0: F8:C3:CC:33:EA:C3
Jan  5 08:42:49 roamast: eth6: disconnect weak signal strength station [f8:c3:cc:33:ea:c3]
Jan  5 08:42:49 roamast: eth6: remove client [f8:c3:cc:33:ea:c3] from monitor list
Jan  5 08:43:19 roamast: [EXAP]Deauth old sta in 1 0: BE:FF:DC:69:78:F9
Jan  5 08:43:19 roamast: eth6: disconnect weak signal strength station [be:ff:dc:69:78:f9]
Jan  5 08:43:19 roamast: eth6: remove client [be:ff:dc:69:78:f9] from monitor list
Jan  5 08:43:22 wlceventd: wlceventd_proc_event(645): eth6: Deauth_ind BE:FF:DC:69:78:F9, status: 0, reason: Previous authentication no longer valid (2), rssi:-84
Jan  5 08:43:22 wlceventd: wlceventd_proc_event(645): eth6: Deauth_ind BE:FF:DC:69:78:F9, status: 0, reason: Disassociated due to inactivity (4), rssi:-84
Jan  5 08:43:22 hostapd: eth6: STA be:ff:dc:69:78:f9 IEEE 802.11: disassociated
Jan  5 08:43:22 hostapd: eth6: STA be:ff:dc:69:78:f9 IEEE 802.11: disassociated
Jan  5 08:43:22 wlceventd: wlceventd_proc_event(645): eth6: Deauth_ind BE:FF:DC:69:78:F9, status: 0, reason: Previous authentication no longer valid (2), rssi:-84
Jan  5 08:43:22 hostapd: eth6: STA be:ff:dc:69:78:f9 IEEE 802.11: disassociated
Jan  5 08:43:23 wlceventd: wlceventd_proc_event(662): eth6: Disassoc BE:FF:DC:69:78:F9, status: 0, reason: Disassociated because sending station is leaving (or has left) BSS (8), rssi:0
Jan  5 08:43:23 hostapd: eth6: STA be:ff:dc:69:78:f9 IEEE 802.11: disassociated`

**Comment by jata1** [comment]
Here is another example that we can use/test using my iphone and apple watch. I can easily move them across my network from node to node and test which node they are actually connected to.

If I move across my house I can see the asus logs roam the clients and the HA connected devices is updated correctly. The issue is that the asus web gui is not updated at all. everything stays the same.

So at the moment, HA is working well but the Asus web GUI is incorrect.

I hope this is helpful. Let me know if I can test anything specific for you.


[iphone roam.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/13836143/iphone.roam.txt)

**Comment by Vaskivskyi** [comment]
It looks like sometimes forcing clients to update can interfere with the Web UI (because Web UI and the integration are trying to do it concurrently). Try disabling the option in the integration config - Connected devices. Just uncheck it and restart your router (so that you start monitoring from a clean state, not from one which is already stuck)

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/46354e00-c1d9-4543-b52b-eb49e54e76ae)

**Comment by Vaskivskyi** [comment]
> Thanks but I do not have or want device tracking on my hue bridges or a IR remote blaster and these are the three additional devices that are identified when I install the integration. I have loads of other devices that are not identified and added like this so there is something weird with how this is working - but it's a different issue so let's park it for now

This is the default behaviour of Home Assistant of how to work with `device_tracker`s. From my side, AsusRouter now (from `0.28.0`) allows filtering for which devices the integration created `device_tracker` entities. But please note, that all of the in-built router integrations (as well as those custom I saw) just add all the `device_tracker`s

**Comment by jata1** [comment]
> It looks like sometimes forcing clients to update can interfere with the Web UI (because Web UI and the integration are trying to do it concurrently). Try disabling the option in the integration config - Connected devices. Just uncheck it and restart your router (so that you start monitoring from a clean state, not from one which is already stuck)
> 
> ![image](https://private-user-images.githubusercontent.com/6554415/294687124-46354e00-c1d9-4543-b52b-eb49e54e76ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzYzNzUsIm5iZiI6MTcwNDU3NjA3NSwicGF0aCI6Ii82NTU0NDE1LzI5NDY4NzEyNC00NjM1NGUwMC1jMWQ5LTQ1NDMtYjUyYi1lYjQ5ZTU0ZTc2YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDZUMjEyMTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTgwZmQyNTcxM2RkN2I5YzVmNTBiMDhjYmIyNjBmMTgzN2VmYTVlMjk4ZDg4YjUzMjk2MTg2NWNjODA0ZmU0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D4k0ceKpQnwzx3LvYJfGXF4Qm6wG07eUEgTK9aslAl8)

Thank you. I have changed the setting for connected devices and rebooted the router then installed 0.28.0. I will now monitor

**Comment by jata1** [comment]
@Vaskivskyi - just an update for you. I have had an internet outage for the last 2-3 days so have not been monitoring this closely. 

Overall I think device tracking is working better and I have not seen any devices stuck in the ASUS web GUI with 'force clients update' disabled.

Will update you again in a few days.

**Comment by jata1** [comment]
@Vaskivskyi - I have been monitoring for the last week and this issue has been resolved by disabling 'force clients update'

I can also confirm that v0.28 has massively improved the home/away device tracking issue. Everything is working well for me at the moment. 

Thanks for all the effort on this project.

**Comment by Vaskivskyi** [comment]
Hey, @jata1, thanks for your confirmation.

The `force client` feature will be adjusted in the integration to prevent such issues for users. Instead of just forcing it with each client poll, it will become an optional `button` entity, which can be triggered by the user whenever needed and with any custom time interval

**Comment by Vaskivskyi** [comment]
With PR #777 this will be handled properly now as described above

The release will be available shortly
