### ISSUE TITLE
[Bug] Block Internet switches don't seem to work

### ISSUE THREAD

**Issue by angrycatmeowmeow** [Vaskivskyi/ha-asusrouter#773]
### The problem

If I use the Asus Router app to block internet to a client, I'll get a "block internet" entity in HA. These entities don't seem to work or update, though. If I turn off Parental Control, the entities are no longer provided by the integration as well. If I block a client in the Asus app, it doesn't reflect in HA, and if I turn it on in HA using the entity, it doesn't reflect in the Asus app.

### Your device model

ET12

### Firmware type

Stock

### Firmware version

3.0.0.4.388.24542_g719e902

### Integration version with the issue

0.28.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2024.1.2

### Is there anything useful in the logs?

```txt
This error originated from a custom integration.

Logger: custom_components.asusrouter.switch
Source: custom_components/asusrouter/switch.py:217
Integration: AsusRouter (documentation, issues)
First occurred: 13:07:27 (6 occurrences)
Last logged: 13:12:23

Unable to set state with an exception: sequence item 0: expected str instance, NoneType found
```

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the late reply. Let's try to sort it out, so the issue can be fixed

When you set the block from the mobile app, does it change in HA to the state `unknown`?

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/50eb6552-9011-4945-a6a9-11b0614bf71f)

Or does it become unavailable? Also, any change of the state in HA can take up to 30 seconds depending on the update interval of the integration

---

In any case, it is supposed to work from HA and change the state in the mobile app.

Can you please turn on debug logging and share the part of the log when you try to set

**Comment by angrycatmeowmeow** [comment]
I've been tooling around this morning and I think it's working correctly, but I was missing a piece.

The `switch.zenwifipro_parental_control` needs to be on.

Blocking a device would cause an entity to be created in HA for that device `switch.device_block_internet`. This entity would only be available when the block was active, and trying to turn the block off through HA would cause it to temporarily turn off, then turn right back on. Turning the block off in the Asus app or GUI would lead to "this entity is no longer provided by the integration" in HA.

What I did is add everything I want to block to parental control-schedule block in the Asus app with no time scheduling. The `switch.device_block_internet` entities immediately came back, and when I flip them in HA it is shown in the Asus app/GUI, and visa-versa. Adding the devices to parental control is key, I didn't realize Asus groups internet blocking under parental controls.

**Comment by Vaskivskyi** [comment]
The new release is already available in HACS and should solve this issue. In case if the issue persists, please, reopen it
