### ISSUE TITLE
[Feature] Wake on LAN

### ISSUE THREAD

**Issue by Richo24** [Vaskivskyi/ha-asusrouter#789]
### The problem

It would be very useful to turn on a NAS from Home Assistant using the Network tool of the ASUS routers, since otherwise with external applications it fails very often, and the router's option never fails.

### Specific device(s)?

None

### Firmware type

None

**Comment by Vaskivskyi** [comment]
Hello

Is it beneficial over the in-built HA Wake on LAN? https://www.home-assistant.io/integrations/wake_on_lan

We need to consider whether it provides user any advantage over the already existing HA features

**Comment by Richo24** [comment]
I can't think of any other reason than better reliability and easier setup.
