### ISSUE TITLE
[Feature] Reboot router + nodes

### ISSUE THREAD

**Issue by Matssa56** [Vaskivskyi/ha-asusrouter#793]
### The problem

Hi, I had some issues with my router and wifi so I reset everything from scratch. I also have a node in aimesh.

When rebooting the router, I see that the node doesn't seem to reboot, so the devices changes to the node and doesn't really come back to the router. 

In the router admin website you need to go under the aimesh parameters to find the button to reboot the full system. The standard reboot doesn't do this, unless you do that from their app (it detects if you have nodes or not and reboots everything).

Feature request : add a button to reboot the whole mesh and not only the router.

Thanks!

### Specific device(s)?

No

### Firmware type

No

**Comment by Vaskivskyi** [comment]
The feature is implemented with a new button in `0.32.0` which is already available in HACS. Please, check it

**Comment by Matssa56** [comment]
> The feature is implemented with a new button in `0.32.0` which is already available in HACS. Please, check it

Hi,
Thanks for your feedback, which buttons is it? Rebuild ai mesh?

**Comment by Vaskivskyi** [comment]
No, the Reboot AiMesh (`button.{device}_reboot_aimesh`) - it mimics the behaviour of the button from the Web UI and should fully restart your network

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/9c9084f9-52d0-483d-8633-c2fbf19f858e)

**Comment by Matssa56** [comment]
I don't see this button, I'll try to install it from scratch and see. I have a AX88U under Merlin and a AX56.
