### ISSUE TITLE
[Feature] The X_boot_time entity is a looong fat "string" and not a TimeStamp or similar, so you cant even use it with "last_updated/change". 

### ISSUE THREAD

**Issue by boheme61** [Vaskivskyi/ha-asusrouter#804]
### The problem

Can the state be changed to a timestamp , which one can template easily, instead of this predefined long String

### Specific device(s)?

None

### Firmware type

None

**Comment by Vaskivskyi** [comment]
Hello. I will check this possibility and get back to you

**Comment by mdisabato** [comment]
If this helps:
What the integration supplies: 2024-03-01T09:33:27+00:00
What a "last updated" attribute looks like, which is supposed to be the right format: 2024-03-01 23:00:00.141389+00:00

I get there is no "tzdata" in the string. 

Thank you.

Michael

**Comment by boheme61** [comment]
Actually this is the string i see in my UI " February  29, 2024 at 01:49 "

And i would prefer a much shorter.
I understand Vaskivskyi argument in regards to to the "uptime status" which many previous(and still use) i.e ( 5 days, 11 hours, 37min "ago")( and counting ) has a bad/not desired impact on the system/hardware.

I.E I could/would "interpret" a "string" without the Year at all or in 2 digits ... I mean if it i.e says October ( I know it was 2023 ) , i would know that even it it just said " Oct " or Even if it said "Mar" ( As there are a few days until Marsh 29 )
And how many, peoples Router does actually Not need a "reboot" once or twice a year ? , So the risk that people ends up in a confused state is quite small

So maybe the sensor could provide 2 strings, or 2 sensors ( i know ! i can make my 0wn template-sensor )
But maybe a short and the long version could be an alternative

October 29, 2024 at 01:49
Oct. 29 at 01.49

I would prefer the latest/shortest

**Comment by boheme61** [comment]
> For me, this also puts the issue into a "non-hurry" state. :)

I ended up with this
```
      {% set date = states('sensor.asusr_boot_time')[:10] | as_timestamp |
      timestamp_custom('%b-%d') %} {% set (h,m,s) =
      states('sensor.asusr_boot_time')[10:19].split(':') | map('int', 0) %}  {%
      set time = utcnow().replace(hour=h, minute=m, second=s) | as_timestamp |
      timestamp_custom('%H:%M') %} {{date}} at {{time}}
```
But as i needed it in an custom:multi-entity-row , inside the "header" of custom:fold-entity-row ( Which is filled with "device_trackers" in custom:mushroom-entity-cards, provided by custom:auto-entities ) btw. LOL
For this, i had to create a template-sensor ( anyways ) ... only haven't figured out howto remove " "

Before:
![03 03 2024_11 55 25_REC](https://github.com/Vaskivskyi/ha-asusrouter/assets/37634316/a45eb1b1-431b-40cb-9830-1eea7905228a)
After:
![03 03 2024_12 29 24_REC](https://github.com/Vaskivskyi/ha-asusrouter/assets/37634316/521af9c3-b828-43db-8439-df0f591d43c8)
![03 03 2024_12 31 00_REC](https://github.com/Vaskivskyi/ha-asusrouter/assets/37634316/431ccb0c-0c88-4f2f-89be-a995ad8e1e26)

So for me, i'll close this FR, as i obviously always need "something else" hmmmm :)
