### ISSUE TITLE
[Bug] Integration can't access Endpoint Service Login in initial setup

### ISSUE THREAD

**Issue by nikotime** [Vaskivskyi/ha-asusrouter#806]
### The problem

I am trying to setup via HACS for the first time but unfortunately fail at an early hurdle. When I go into Integrations, type in my IP address (and also asusrouter.com) it takes me to the username password section but I get an unknown error and in the logs the exception: Original exception: ('Cannot access EndpointService.LOGIN. Failed in `async_connect`', None)

This is the same error with the 'right' and 'wrong' username password setup when trying to test.

### Your device model

RT-AXE7800

### Firmware type

Stock

### Firmware version

3.0.0.4.388_24631

### Integration version with the issue

V0.29.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2024.2.5

### Is there anything useful in the logs?

```txt
No initial info in debug logging.

Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:260
Integration: AsusRouter (documentation, issues)
First occurred: 14:05:36 (17 occurrences)
Last logged: 14:12:58

Error during connection to `192.168.1.1`. Original exception: ('Cannot access EndpointService.LOGIN. Failed in `async_connect`', None)
Error during connection to `www.asusrouter.com`. Original exception: ('Cannot access EndpointService.LOGIN. Failed in `async_connect`', None)
```

**Comment by Vaskivskyi** [comment]
Hello,

do you try to connect using an SSL connection or not? Are you using the standard port for non-SSL (80) / SSL (8443) connection to the device?

The integration connects to the device the same way you are accessing its web UI.

You can check the settings in the Web UI - Administration - System - all the way to the bottom

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/52912104-b199-4d89-a1cf-342ad14c23a2)

**Comment by nikotime** [comment]
Thanks so much, idiotic mistake from my part that my saved password on my IP address login was different from the one from asusrouter.com...funny enough using the correct password made everything work perfectly. Thanks for the great integration!
