### ISSUE TITLE
[Bug]  Addon in wrongly showing firmware update

### ISSUE THREAD

**Issue by Cosik** [Vaskivskyi/ha-asusrouter#813]
### The problem

Addon is showing that there is new firmware for my router TUF-AX5400. I found that it is firmware for some other router. 

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/1255379/dd21b065-cdd2-4bfa-8604-7c85b1a13a32)

### Your device model

TUF-AX5400

### Firmware type

Stock

### Firmware version

3.0.0.4.388.24121_ge887338

### Integration version with the issue

0.30.0 

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2024.3.1

### Diagnostics information

[home-assistant_asusrouter_2024-03-22T21-25-53.406Z.log](https://github.com/Vaskivskyi/ha-asusrouter/files/14728684/home-assistant_asusrouter_2024-03-22T21-25-53.406Z.log)

**Comment by Vaskivskyi** [comment]
Hello. There seems to be an issue with a beta firmware reported as an available update.

Can you please check, whether in the device settings you have set to receive beta versions?

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/edb2c26e-c1bd-48a5-9ed4-52d26728c0e8)

**Comment by Cosik** [comment]
Hi, yes, on it I had enabled beta firmware checking.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/1255379/7e29716a-caf0-4a07-9433-363b624d93bb)

**Comment by gitcak** [comment]
I'm having the same issue with the ET8. Seems to be showing the XT8 firmware as the update.
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/19296476/942338cc-15d9-4cde-88ca-f59de0428e64)
