### ISSUE TITLE
Show Merlin firmware on GT-AXE16000

### ISSUE THREAD

**Issue by alsoszaa** [Vaskivskyi/ha-asusrouter#820]
### The problem

Not sure if this is a bug or a feature. I use the Merlin firmware on my AXE16000 and I love your home assistant add-on. I use the firmware available, and latest firmware features of your add-on. But it's currently telling me that there is a new firmware version available which I have the latest Merlin version right now, but then points to the stock firmware version. Is there a way for your code to see that I am on Merlin and then do a check for the latest Merlin firmware instead of the stock?

### Specific device(s)?

No

### Firmware type

Yes

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the late reply. Can you please post how does the string for the current and new FW look in the HA update entity

An example:

![Image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/9a333e6d-28c9-455b-afb6-9b5da51ba803)

AsusRouter takes the data from your device directly - from the data available in the Web UI under `Administration - Firmware upgrade`. So there should be some issue with the currently saved data on your device. You can try to manually "Check for update" if you did not yet.
