### ISSUE TITLE
[Bug] Latest Merlin 3004.388.7 version not working with RT-AX58U

### ISSUE THREAD

**Issue by sesardelaisla** [Vaskivskyi/ha-asusrouter#825]
### The problem

After installing latest Merlin version, integration is no longer working nor providing entities. Reloading integration or restarting HASS does not fix it. Trying to remove and re-add the HUB (router) doesn’t work either. Router adding flow execution is possible (it seems it can login). However, entities are not added and integration displays the “failed to setup” error:

![IMG_6354](https://github.com/Vaskivskyi/ha-asusrouter/assets/81921573/9381f9a5-e854-419b-831e-4776aebda125)

Could developers look into this, please?

TIA

### Your device model

RT-AX58U

### Firmware type

Merlin

### Firmware version

3004.388.7

### Integration version with the issue

0.30.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

core-2024.5.2

**Comment by mihsu81** [comment]
This is fixed in 0.31.0

**Comment by sesardelaisla** [comment]
Just tested and it is working again. Thanks!
