### ISSUE TITLE
Secondary WAN incorrect status [Bug] 

### ISSUE THREAD

**Issue by kamilnadzieja** [Vaskivskyi/ha-asusrouter#827]
### The problem

Hi, 

I'm using Asus RT-AX88U with Dual Wan enabled (second wan is via usb lte dongle). As you can see in the screenshot below entity "Secondary WAN" is set as "Connected" although it is not in reality (look at the secondary WAN IP):

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/60479769/83ccb0ec-5c45-46b8-90a7-c5a514bd1d91)

On the router configuration page the status of the secondary wan is "Cold - Standby":

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/60479769/7611e0bd-5f0c-4c3d-aeee-77488a842834)

Question - is it possible to get the value "Disconnected" in this integration given the fact that secondary wan is actually disconnected?

Thanks!

### Your device model

RT-AX88U

### Firmware type

Merlin

### Firmware version

3004.388.7

### Integration version with the issue

0.31

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2024.5.3

**Comment by Vaskivskyi** [comment]
Can you please show what does the attribute `link` look like? Unfortunately, I don't have LTE dongles, but when tested with phone and tethering, it works as expected. Might be, USB modems report differently

![Image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/4a419db1-fa17-438e-9b6e-0b96b645348a)
![Image](https://github.com/Vaskivskyi/ha-asusrouter/assets/6554415/67ec9cf0-9224-402b-93b1-5fac2df80827)

**Comment by kamilnadzieja** [comment]
Here:
![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/60479769/d4bbb8ed-807a-4fde-90e4-63f36fbd3604)

**Comment by kamilnadzieja** [comment]
I do not observe any issues - defect to be closed
