### ISSUE TITLE
[Device support] RT-AC88U

### ISSUE THREAD

**Issue by ijavid** [Vaskivskyi/ha-asusrouter#828]
### Anything you want to mention?

Unable to setup RT-AC88U router with the latest Merlin firmware **386.13_0**:
```
Unknown error of type '<class 'asusrouter.error.AsusRouterConnectionError'>' during connection to `192.168.0.1`: ('Cannot connect to 192.168.0.1. Failed in `_send_request`', None)
```
Downgraded to **386.12_2** setup went ok but unable to initialize the device.
```
Cannot get clients for 192.168.0.1: ('Cannot connect to 192.168.0.1. Failed in `_send_request`', None)
Cannot get available network interfaces for 192.168.0.1: ('Cannot connect to 192.168.0.1. Failed in `_send_request`', None)
```
Removed the device, reinstalled the integration and rebooted everything, now the same as the initial error: unable to add integration. 
```
Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:269
Unknown error of type '<class 'asusrouter.error.AsusRouterConnectionError'>' during connection to `192.168.0.1`: ('Cannot connect to 192.168.0.1. Failed in `_send_request`', None)
```

Authentication Method HTTP, Port 80, Login Captcha OFF, WAN Access OFF, SSH Lan only. 
HA 2024.5.4 running in a VM (OS 12.3) on the same subnet as the router. 

### Your device model

RT-AC88U

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.13_0
3.0.0.4.386.12_2

### Does everything work well?

No

**Comment by ijavid** [comment]
Switched to Authentication Method to BOTH (HTTP + HTTPS). Now it works as expected when using SSL.

**Comment by ijavid** [comment]
Debug logs of the following flow: ERROR -> Use SSL connection [ON] -> OK -> Use SSL connection [OFF] -> ERROR

[logs.log](https://github.com/Vaskivskyi/ha-asusrouter/files/15381804/logs.log)

**Comment by Vaskivskyi** [comment]
Hello, @ijavid,

can you please check whether you get any more info when trying to connect on HTTP with the newer integration version `0.32.0`? The exception logging was improved, so it should say more now instead of just `Cannot connect to xxx.xxx.xxx.xxx`

**Comment by Vaskivskyi** [comment]
Hello. Please, reopen this issue (or create a new one) if you want to continue troubleshooting. If the integration works fine for you - that would be good
