### ISSUE TITLE
[Feature] New parameter\sensor to implement in the integration

### ISSUE THREAD

**Issue by idrostasi** [Vaskivskyi/ha-asusrouter#837]
### The problem

Hello,

as suggested in a topic I recently open, I’d want to know if there will be the chance to implement the sensors which read the dsl features.
If I connect to my modem and go into the menu and click first on “1”, then on “2”, I see the real speed of my internet connection (“3”), that in this moment is 151619 kbps in download and 21600 kbps in upload:

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/14802638/2bd32492-2686-4b51-838a-f0ce333cc9d1)

So it would be nice if the integration could also read those two parameters.

### Specific device(s)?

None

### Firmware type

None

**Comment by Vaskivskyi** [comment]
Hello. I will check what data can be fetched from the API and exposed to HA. I will come back to you when there is any update or question

**Comment by GaryHuang-ASUS** [comment]
Hello, I have submitted the relevant data capture in PR [#530](https://github.com/Vaskivskyi/asusrouter/pull/530).

**Comment by Vaskivskyi** [comment]
Thanks to Gary, the feature has been successfully added to AsusRouter. It will be available with the next integration release 🙂

**Comment by idrostasi** [comment]
Hello, it seems that it doesn't read the unit of measure anymore after the last home assistant core update.
I saw that in this mushroom chips I created:

![Image](https://github.com/user-attachments/assets/2bb1b338-5bdc-440b-a928-08b5a2104cef)

before I remember there were kb/s or something similar after the value, now it's gone.
