### ISSUE TITLE
[ASUS BRT-AC828 & ASUS RP-AX56 support] 

### ISSUE THREAD

**Issue by egric** [Vaskivskyi/ha-asusrouter#842]
### Anything you want to mention?

Thanks for the work done! I installed your ha-asus router. However, it did not start with version 0.32.1. I got a 500 error. But it started with version 0.32.0 and works very well. You can safely add the ASUS BRT-AC 828 router and the ASUS RP-AX 56 repeater to the list of supported devices

### Your device model

BRT-AC828 

### Firmware type

Stock

### Firmware version

3.0.0.4.382_70348

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Thanks for your report! :+1: The devices have been added
