### ISSUE TITLE
Router RT-AC68U error

### ISSUE THREAD

**Issue by pepe59** [Vaskivskyi/ha-asusrouter#85]
Thank you in advance for a great component.
I have no idea if I have something wrong or it's a mistake.
Everything works fine, but there is an error in the HA log.
Asus RT-AC68U + AiMesh Router Asus RT-AC66U B1
HA all updated to the latest version.

```
Logger: asusrouter.util.parsers
Source: /usr/local/lib/python3.9/site-packages/asusrouter/util/parsers.py:171
First occurred: 11:11:27 (24 occurrences)
Last logged: 11:22:59

Failed parsing value 'is_private_subnet'. Please report this issue. Exception summary: ("Wrong value 3 of type <class 'str'>", None)
```

**Comment by Vaskivskyi** [comment]
Hey, @pepe59,

Thanks for your feedback! 👍🏻 

This seems to be a problem with the library behind the integration. I'll make the needed corrections and let you know. Should not take too much time

**Comment by Vaskivskyi** [comment]
@pepe59,

The new release 0.3.1 of the integration should fix this error. If you don't see the update yet in your HACS, you may restart the HACS service (or all the HomeAssistant), so the database will update and show the update for AsusRouter integration.

If you will experience any other problems with the integration, please open a new issue, so it will be easier to track.

**Comment by pepe59** [comment]
I really appreciate your approach.
After updating the components everything works perfectly.
The error is cleared. I think we can close the issue and add a router Asus RT-AC68U + AiMesh Asus RT-AC66U B1 to the supported. 
Thank you

**Comment by Vaskivskyi** [comment]
Great! In case, something else will be causing any trouble, just open a new issue. Have a nice day! 🙂
