### ISSUE TITLE
[Bug] Missing colors module

### ISSUE THREAD

**Issue by VladFlorinIlie** [Vaskivskyi/ha-asusrouter#869]
### The problem

Hello,

After updating to 0.33.2, I receive the following error at HA startup:

`Setup failed for custom integration 'asusrouter': Unable to import component: No module named 'asusrouter.modules.color'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/asusrouter/__init__.py", line 13, in <module>
    from .router import ARDevice
  File "/config/custom_components/asusrouter/router.py", line 35, in <module>
    from .bridge import ARBridge
  File "/config/custom_components/asusrouter/bridge.py", line 71, in <module>
    from .modules.aura import aura_to_ha
  File "/config/custom_components/asusrouter/modules/aura.py", line 15, in <module>
    from asusrouter.modules.color import ColorRGBB
ModuleNotFoundError: No module named 'asusrouter.modules.color'`

Last working version seems to be 0.32.1

### Your device model

RT-AX88U Pro

### Firmware type

Merlin

### Firmware version

3004.388.8_2

### Integration version with the issue

0.33.2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2024.8.3

**Comment by VladFlorinIlie** [comment]
It seems that completely removing the integration and reinstalling it fixes the problem. I will close this issue.

**Comment by Vaskivskyi** [comment]
Hey. Good that it's solved. Looks like some backend update issue. Maybe just the Pypi package didn't get updated and HA decided to start without it

**Comment by Matthieu-Em** [comment]
Hello, same issue here but fully reinstall the integration does not fix the issue :(

**Comment by Vaskivskyi** [comment]
@Matthieu-Em, do you see any errors in the log about installing the requirements? E.g.

![image](https://github.com/user-attachments/assets/c1c95cd0-2969-4903-85f3-6f43609d8bca)

Also, did you restart your Home Assistant instance after upgrading the integration?

**Comment by Matthieu-Em** [comment]
> @Matthieu-Em, do you see any errors in the log about installing the requirements? E.g.
> 
> ![image](https://private-user-images.githubusercontent.com/6554415/365381353-c1c95cd0-2969-4903-85f3-6f43609d8bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MjQ1NDYsIm5iZiI6MTcyNTcyNDI0NiwicGF0aCI6Ii82NTU0NDE1LzM2NTM4MTM1My1jMWM5NWNkMC0yOTY5LTQ5MDMtODVmMy02ZjQzNjA5ZDhiY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDdUMTU1MDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE2M2E5ZTc3YzNlMjY2ZTE5NjU3ZDc1NDgwYmVlOTY4ZjQ4NzAyYWNlMWQwNjZlMTJkNmM4MzljNDQzNGFkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UlhdLpy-gYEfluEd_o89XGf2Tu13rHv9tyEnFYGx_iE)
> 
> Also, did you restart your Home Assistant instance after upgrading the integration?

No this error is not present
Yes i have restarted, I'm currently trying to fix it even a downgrade is no more working.
Thanks for your reply :)

**Comment by Matthieu-Em** [comment]
Here we go now in the log I get:
homeassistant.requirements.RequirementsNotFound: Requirements for asusrouter not found: ['asusrouter==2.0.0.dev0'].

**Comment by Vaskivskyi** [comment]
@Matthieu-Em, what is the way you used to install the integration? Please, use either installation through HACS or from the `main` branch from GitHub. Don't use the `dev` branch (except if you want to build and install the backend manually for your HA)

**Comment by Matthieu-Em** [comment]
> @Matthieu-Em, what is the way you used to install the integration? Please, use either installation through HACS or from the `main` branch from GitHub. Don't use the `dev` branch (except if you want to build and install the backend manually for your HA)

Ok I restart again from scratch with HACS, during UI configuration I get:
 Le flux de configuration n'a pas pu être chargé: {"message":"Invalid handler specified"} 

with in the log:
2024-09-07 18:19:14.785 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration asusrouter: No module named 'asusrouter.modules.color'

**Comment by Vaskivskyi** [comment]
Do you use Home Assistant Core or Docker or HA OS? Do you have console access to the environment with your HA? E.g. can you run `python3 -m pip show asusrouter` to check what version of the backend is installed?

**Comment by Matthieu-Em** [comment]
> Do you use Home Assistant Core or Docker or HA OS? Do you have console access to the environment with your HA? E.g. can you run `python3 -m pip show asusrouter` to check what version of the backend is installed?

It is running under HAOS:
`asusrouter # pwd
/root/homeassistant/custom_components/asusrouter
asusrouter # python3 -m pip show asusrouter
WARNING: Package(s) not found: asusrouter`

**Comment by Vaskivskyi** [comment]
Weird. But I don't know exactly how does HAOS work. In any case, you can try manually install the correct backend with:

```
python3 -m pip install asusrouter==1.13.0
```

You would see whether it works or gives any errors

**Comment by Matthieu-Em** [comment]
> Weird. But I don't know exactly how does HAOS work. In any case, you can try manually install the correct backend with:
> 
> ```
> python3 -m pip install asusrouter==1.13.0
> ```
> 
> You would see whether it works or gives any errors

Unfortunately it is not easy:
`asusrouter # python3 -m pip install asusrouter==1.13.0

error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.`

**Comment by Matthieu-Em** [comment]
> > Weird. But I don't know exactly how does HAOS work. In any case, you can try manually install the correct backend with:
> > ```
> > python3 -m pip install asusrouter==1.13.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You would see whether it works or gives any errors
> 
> Unfortunately it is not easy: `asusrouter # python3 -m pip install asusrouter==1.13.0
> 
> error: externally-managed-environment
> 
> × This environment is externally managed ╰─> The system-wide python installation should be maintained using the system package manager (apk) only.
> 
> ```
> If the package in question is not packaged already (and hence installable via
> "apk add py3-somepackage"), please consider installing it inside a virtual
> environment, e.g.:
> 
> python3 -m venv /path/to/venv
> . /path/to/venv/bin/activate
> pip install mypackage
> 
> To exit the virtual environment, run:
> 
> deactivate
> 
> The virtual environment is not deleted, and can be re-entered by re-sourcing
> the activate file.
> 
> To automatically manage virtual environments, consider using pipx (from the
> pipx package).
> ```
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages. hint: See PEP 668 for the detailed specification.`

Don't know if it is the reason but installing the package throught:
https://github.com/home-assistant/addons-development/tree/master/custom_deps
Make it work with the latest version... weird behavior.
Thanks a lot for your help and the integration @Vaskivskyi

**Comment by Vaskivskyi** [comment]
Good that it works now :+1:
