### ISSUE TITLE
[Bug] AttributeError: type object 'AsusData' has no attribute 'DSL'

### ISSUE THREAD

**Issue by Morriz** [Vaskivskyi/ha-asusrouter#872]
### The problem

After upgrade the add-on does not start

### Your device model

RT-AX16000

### Firmware type

Merlin

### Firmware version

3004.388.8_2_rog

### Integration version with the issue

0.34.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2024.9.1 Supervisor 2024.08.0 Operating System 13.1 Frontend 20240906.0

### Is there anything useful in the logs?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: September 11, 2024 at 11:34:10 AM (2 occurrences)
Last logged: 12:41:12 PM

Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 446, in setup
    await self._init_sensor_coordinators()
  File "/config/custom_components/asusrouter/router.py", line 827, in _init_sensor_coordinators
    available_sensors = await self.bridge.async_get_available_sensors()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 212, in async_get_available_sensors
    SENSORS: await self._get_sensors_modern(AsusData.DSL),
                                            ^^^^^^^^^^^^
AttributeError: type object 'AsusData' has no attribute 'DSL'
```

**Comment by Morriz** [comment]
closing as this was gone after a hard reboot. Could you trigger such after an update that requires it?

**Comment by Vaskivskyi** [comment]
Hey, @Morriz,

after you installed the update - did you restart the HA or just reloaded the integration when you saw the import error? And what exactly do you mean by the hard reboot later which fixed it? Something more complex than just clicking "restart my HA"?

Looks like HAOS users have some issues lately with updating the dependencies and it would be nice to find out why. Unfortunately, I don't have OS, just docker and core HA installations, so I cannot check it by myself currently.

**Comment by Morriz** [comment]
Well, the "normal" routine that suggests a restart after it is needed, is only restarting HA, which is not a reboot. It surely could be HAOS related, but then you as devs should be able to determine what kind of reboot (soft vs hard) is needed if that is how it is designed. Or something is wrong in core which orchestrates the reloading of containers but does not reload new config? I also think some design issues arose from the new core architecture that were not anticipated. I am also not sure if this happens in the realm of addon-land.
